#!/usr/bin/env python3
"""src/ 配下のコードファイル先頭に日本語の説明コメントが存在することを保証する pre-commit hook。

src/CLAUDE.md 規約「コードファイルの先頭には、必ず日本語でファイルの説明コメントを記載すること」の
最低限自動化版。各行の 1 行上に日本語コメント、までは AI レビューに任せる。

対象拡張子と言語別のコメント記号:
    .go        // ...
    .rs        // ...
    .cs        // ...
    .ts/.tsx   // ...
    .proto     // ...
    .py        # ...
    .sh        # ...

許容パターン:
    - 1 行目が shebang (#!) の場合は 2 行目以降から探索
    - SPDX-License-Identifier 行や Apache 2.0 ヘッダコメントブロックは「説明コメント」の前にあってよい
    - 連続する複数のコメント行のうち、いずれかに日本語（CJK Unified Ideographs / ひらがな / カタカナ）が含まれていれば OK

例外:
    - 自動生成ファイル（先頭に `// Code generated`、`// DO NOT EDIT`、`# Code generated` 等）はスキップ

Usage:
    tools/git-hooks/japanese-header-guard.py [<file> ...]
    pre-commit から呼ばれる場合、stdin から filenames を取らず引数で受け取る
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# 言語別のコメント記号（行頭から）
COMMENT_PREFIXES: dict[str, tuple[str, ...]] = {
    ".go": ("//", "/*"),
    ".rs": ("//", "/*"),
    ".cs": ("//", "/*"),
    ".ts": ("//", "/*"),
    ".tsx": ("//", "/*"),
    ".js": ("//", "/*"),
    ".jsx": ("//", "/*"),
    ".proto": ("//", "/*"),
    ".py": ("#",),
    ".sh": ("#",),
    ".bash": ("#",),
}

# 自動生成マーカー: 先頭近くにこれが含まれるなら hook をスキップ
GENERATED_MARKERS = (
    "Code generated",
    "DO NOT EDIT",
    "@generated",
    "DO NOT MODIFY",
    "AUTOGENERATED",
)

# スキップ系ヘッダ（説明コメント以前に来てよい）
SKIP_HEADER_PATTERNS = (
    re.compile(r"^\s*//\s*SPDX-License-Identifier"),
    re.compile(r"^\s*#\s*SPDX-License-Identifier"),
    re.compile(r"^\s*//\s*Copyright"),
    re.compile(r"^\s*#\s*Copyright"),
    re.compile(r"^\s*/\*\s*$"),
    re.compile(r"^\s*\*"),  # block comment 中の各行
    re.compile(r"^\s*\*/\s*$"),
)

# CJK 検出: ひらがな / カタカナ / CJK 統合漢字
CJK_PATTERN = re.compile(r"[぀-ゟ゠-ヿ一-鿿]")


def is_comment_line(line: str, prefixes: tuple[str, ...]) -> bool:
    stripped = line.lstrip()
    return any(stripped.startswith(p) for p in prefixes)


def is_blank(line: str) -> bool:
    return line.strip() == ""


def is_generated(text: str, n_lines: int = 5) -> bool:
    """先頭 n 行に自動生成マーカーがあれば True"""
    head = "\n".join(text.splitlines()[:n_lines])
    return any(m in head for m in GENERATED_MARKERS)


def has_japanese_header(path: Path) -> tuple[bool, str]:
    """戻り値: (OK か, 理由)"""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        return True, f"read skipped: {e}"

    if is_generated(text):
        return True, "generated file (skipped)"

    suffix = path.suffix
    prefixes = COMMENT_PREFIXES.get(suffix)
    if prefixes is None:
        return True, "extension not targeted"

    lines = text.splitlines()
    if not lines:
        return False, "empty file"

    idx = 0
    # shebang をスキップ
    if lines[0].startswith("#!"):
        idx = 1

    # 空行 / SPDX / Copyright / block comment marker をスキップしながら、
    # 連続するコメント行群を採取する
    found_comment_block = False
    block_text_parts: list[str] = []
    while idx < len(lines):
        line = lines[idx]
        if is_blank(line):
            if found_comment_block:
                # コメントブロックが終わった
                break
            idx += 1
            continue
        if any(p.match(line) for p in SKIP_HEADER_PATTERNS):
            # スキップ系ヘッダだが、コメントなので block にも追加（CJK 検出対象に）
            block_text_parts.append(line)
            found_comment_block = True
            idx += 1
            continue
        if is_comment_line(line, prefixes):
            block_text_parts.append(line)
            found_comment_block = True
            idx += 1
            continue
        # コメント以外の行が来た → 探索終了
        break

    if not found_comment_block:
        return False, "no header comment block found at top of file"

    block_text = "\n".join(block_text_parts)
    if CJK_PATTERN.search(block_text):
        return True, "ok"
    return False, "header comment exists but contains no Japanese (CJK) characters"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Ensure src/ code files have a Japanese header comment block."
    )
    parser.add_argument("files", nargs="*", help="files to check (passed by pre-commit)")
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress per-file output, print only summary",
    )
    args = parser.parse_args()

    if not args.files:
        return 0

    failed: list[tuple[Path, str]] = []
    for f in args.files:
        path = Path(f)
        if not path.is_file():
            continue
        ok, reason = has_japanese_header(path)
        if not ok:
            failed.append((path, reason))

    if failed:
        print("[japanese-header-guard] 違反検出:")
        for path, reason in failed:
            print(f"  - {path.as_posix()}: {reason}")
        print(
            "\n対処: ファイル先頭に日本語の説明コメントブロックを追加してください。"
            "\n例（Go の場合）:"
            "\n  // 本ファイルは tier1 facade の Log API ハンドラ実装。"
            "\n  // Dapr Go SDK を経由して OTel Log signal を collector へ送る責務を持つ。"
        )
        return 1

    if not args.quiet:
        print(f"[japanese-header-guard] OK ({len(args.files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
