name: k1s0_flutter_workspace
description: k1s0 Flutter Framework - Shared packages for Flutter applications
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  melos: ^6.0.0
