apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k1s0-observability

commonLabels:
  app.kubernetes.io/part-of: k1s0-observability
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - otel-collector/
  - jaeger/
  - prometheus/
  - loki/
  - grafana/
