//! L3 compose aggregator
//!
//! プロジェクト内の全 feature サービスの compose.yaml を走査し、
//! include ディレクティブを使って統合する。

use std::path::{Path, PathBuf};

use crate::error::{CliError, Result};

/// compose.yaml の走査結果
#[derive(Debug, Clone)]
pub struct ComposeService {
    /// サービス名（feature_name）
    pub name: String,
    /// compose.yaml のパス
    pub compose_path: PathBuf,
    /// monorepo compose のパス（存在する場合）
    pub monorepo_compose_path: Option<PathBuf>,
}

/// プロジェクト内の全 feature サービスの compose.yaml を走査する
pub fn discover_compose_files(project_root: &Path) -> Result<Vec<ComposeService>> {
    let feature_dir = project_root.join("feature");
    if !feature_dir.exists() {
        return Ok(vec![]);
    }

    let mut services = Vec::new();

    // feature/{backend,frontend}/{lang}/{name}/ を走査
    for service_type_dir in &["backend", "frontend"] {
        let type_path = feature_dir.join(service_type_dir);
        if !type_path.exists() {
            continue;
        }

        // 言語ディレクトリを走査
        let lang_entries = std::fs::read_dir(&type_path)
            .map_err(|e| CliError::io(format!("ディレクトリの読み込みに失敗: {}", e)))?;

        for lang_entry in lang_entries {
            let lang_entry = lang_entry
                .map_err(|e| CliError::io(format!("ディレクトリエントリの読み込みに失敗: {}", e)))?;
            let lang_path = lang_entry.path();
            if !lang_path.is_dir() {
                continue;
            }

            // サービスディレクトリを走査
            let service_entries = std::fs::read_dir(&lang_path)
                .map_err(|e| CliError::io(format!("ディレクトリの読み込みに失敗: {}", e)))?;

            for service_entry in service_entries {
                let service_entry = service_entry
                    .map_err(|e| CliError::io(format!("ディレクトリエントリの読み込みに失敗: {}", e)))?;
                let service_path = service_entry.path();
                if !service_path.is_dir() {
                    continue;
                }

                let compose_path = service_path.join("compose.yaml");
                if compose_path.exists() {
                    let name = service_path
                        .file_name()
                        .unwrap_or_default()
                        .to_string_lossy()
                        .to_string();

                    let monorepo_path = service_path.join("compose.monorepo.yaml");

                    services.push(ComposeService {
                        name,
                        compose_path,
                        monorepo_compose_path: if monorepo_path.exists() {
                            Some(monorepo_path)
                        } else {
                            None
                        },
                    });
                }
            }
        }
    }

    Ok(services)
}

/// 発見されたサービスから include 形式の統合 compose.yaml を生成する
pub fn generate_aggregate_compose(
    services: &[ComposeService],
    monorepo: bool,
) -> String {
    let mut output = String::new();
    output.push_str("# k1s0 auto-generated aggregate compose\n");
    output.push_str("# Generated by `k1s0 docker up --all`\n\n");

    if services.is_empty() {
        output.push_str("# No services found\n");
        return output;
    }

    output.push_str("include:\n");
    for service in services {
        let path = if monorepo {
            service
                .monorepo_compose_path
                .as_ref()
                .unwrap_or(&service.compose_path)
        } else {
            &service.compose_path
        };

        // project_name でサービス名衝突を回避
        output.push_str(&format!(
            "  - path: {}\n    project_directory: {}\n    env_file: []\n",
            path.display(),
            path.parent().unwrap_or(Path::new(".")).display()
        ));
    }

    output.push_str("\nnetworks:\n");
    output.push_str("  k1s0-network:\n");
    output.push_str("    external: true\n");

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_discover_empty_project() {
        let temp = TempDir::new().unwrap();
        let result = discover_compose_files(temp.path()).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_discover_with_services() {
        let temp = TempDir::new().unwrap();
        let service_dir = temp.path().join("feature/backend/rust/my-service");
        std::fs::create_dir_all(&service_dir).unwrap();
        std::fs::write(service_dir.join("compose.yaml"), "services:\n  app:\n    build: .\n").unwrap();

        let result = discover_compose_files(temp.path()).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].name, "my-service");
    }

    #[test]
    fn test_discover_multiple_services() {
        let temp = TempDir::new().unwrap();

        let svc1 = temp.path().join("feature/backend/rust/svc-a");
        std::fs::create_dir_all(&svc1).unwrap();
        std::fs::write(svc1.join("compose.yaml"), "services:\n  app:\n    build: .\n").unwrap();

        let svc2 = temp.path().join("feature/backend/go/svc-b");
        std::fs::create_dir_all(&svc2).unwrap();
        std::fs::write(svc2.join("compose.yaml"), "services:\n  app:\n    build: .\n").unwrap();
        std::fs::write(svc2.join("compose.monorepo.yaml"), "services:\n  app:\n    build:\n      context: ../../../../\n").unwrap();

        let result = discover_compose_files(temp.path()).unwrap();
        assert_eq!(result.len(), 2);
        assert!(result.iter().any(|s| s.monorepo_compose_path.is_some()));
    }

    #[test]
    fn test_generate_aggregate_compose() {
        let services = vec![
            ComposeService {
                name: "user-api".to_string(),
                compose_path: PathBuf::from("feature/backend/rust/user-api/compose.yaml"),
                monorepo_compose_path: None,
            },
            ComposeService {
                name: "admin-ui".to_string(),
                compose_path: PathBuf::from("feature/frontend/react/admin-ui/compose.yaml"),
                monorepo_compose_path: Some(PathBuf::from("feature/frontend/react/admin-ui/compose.monorepo.yaml")),
            },
        ];

        let output = generate_aggregate_compose(&services, false);
        assert!(output.contains("include:"));
        assert!(output.contains("user-api/compose.yaml"));
        assert!(output.contains("admin-ui/compose.yaml"));
        assert!(output.contains("k1s0-network"));
        assert!(output.contains("external: true"));

        let output_mono = generate_aggregate_compose(&services, true);
        assert!(output_mono.contains("admin-ui/compose.monorepo.yaml"));
    }

    #[test]
    fn test_generate_aggregate_empty() {
        let output = generate_aggregate_compose(&[], false);
        assert!(output.contains("No services found"));
    }
}
