-- k1s0 database initialization script
-- Generated by `k1s0 init`
-- Add database setup here (roles, extensions, schemas, etc.)

-- Enable common extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create application schema
CREATE SCHEMA IF NOT EXISTS app;
