"""tools/lock_yaml_generator/generate_signals.py

signals.lock.yaml 生成器。
src/tier1/lock/signals_input.yaml を読み込み、5 signal class の観測実装状況を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 status: pending）。

catalog SoT: src/tier1/schema/observability/signals.yaml
catalog が存在する場合、宣言された signal id が全て drill 済みであることを検証する。
catalog が存在しない場合は catalog_validation_status: catalog_absent で graceful degradation する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT
from tools.lock_yaml_generator.lib.catalog_validator import (
    load_catalog,
    validate_catalog_against_input,
    build_catalog_metadata,
)

# signals_input.yaml の想定名
_INPUT_NAME = "signals_input.yaml"

# catalog SoT パス（REPO_ROOT 相対）
_CATALOG_CLASSES_PATH = "src/tier1/schema/observability/signals.yaml"
_CATALOG_SCENARIOS_PATH = "src/tier1/schema/observability/dimensions.yaml"

# 5 signal class 定義（03_観測適合仕様.md の v1 signal class セットと一致する）
_SIGNAL_CLASSES: list[dict[str, str]] = [
    # logs: ClickHouse logs table が SoR
    {"signal_id": "logs", "sor": "clickhouse_logs", "collector": "otel_collector"},
    # metrics: Prometheus が SoR
    {"signal_id": "metrics", "sor": "prometheus", "collector": "otel_collector"},
    # traces: ClickHouse traces table が SoR（Jaeger v2 UI 経由）
    {"signal_id": "traces", "sor": "clickhouse_traces", "collector": "otel_collector_loadbalancing"},
    # profiles: Parca が SoR（eBPF / native pull）
    {"signal_id": "profiles", "sor": "parca", "collector": "parca_agent"},
    # audit: ClickHouse audit table が SoR（PostgreSQL audit_local → Audit relay 経由）
    {"signal_id": "audit", "sor": "clickhouse_audit", "collector": "audit_relay"},
]


class SignalsGenerator(BaseGenerator):
    """signals.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "signals.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/signals_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 signal class リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        catalog SoT (observability/signals.yaml) が存在する場合は cross-validation を実行する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # signals キーを読み込む
        raw_signals: list[dict[str, Any]] = inputs.get("signals", [])

        if raw_signals:
            # 入力データから signals を正規化する
            signals = self._normalize_signals(raw_signals)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            signals = self._build_skeleton()

        # catalog SoT のパスを解決する
        classes_path = REPO_ROOT / _CATALOG_CLASSES_PATH
        scenarios_path = REPO_ROOT / _CATALOG_SCENARIOS_PATH

        # catalog yaml を読み込む（不在時は None）
        classes_catalog = load_catalog(classes_path)
        scenarios_catalog = load_catalog(scenarios_path)

        # signals catalog の cross-validation: signals[].id vs input signals[].signal_id
        classes_result = validate_catalog_against_input(
            catalog=classes_catalog,
            input_data=inputs,
            class_key="signals",
            input_id_key="signal_id",
            input_list_key="signals",
            catalog_path=classes_path,
            catalog_id_key="id",
        )

        # dimensions catalog は signal id との対応がないため passed 扱いとする
        scenarios_result = validate_catalog_against_input(
            catalog=scenarios_catalog,
            input_data={},
            class_key="layers",
            input_id_key="id",
            input_list_key=None,
            catalog_path=scenarios_path,
            catalog_id_key="id",
        )
        # dimensions は drill 対象外なので常に passed とする
        if scenarios_catalog is not None:
            scenarios_result = {
                "status": "passed",
                "missing": [],
                "catalog_sot_hash": scenarios_result.get("catalog_sot_hash"),
            }

        # metadata を構築する
        catalog_meta = build_catalog_metadata(
            classes_result=classes_result,
            scenarios_result=scenarios_result,
            classes_path=_CATALOG_CLASSES_PATH,
            scenarios_path=_CATALOG_SCENARIOS_PATH,
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_signals.py"
            ),
            "total_signals": len(signals),
            "generated_at":  generated_at,
            "metadata":      catalog_meta,
            "signals":       signals,
        }

    @staticmethod
    def _normalize_signals(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """signal エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "signal_id":  str(entry.get("signal_id", "")),
                "sor":        str(entry.get("sor", "")),
                "collector":  str(entry.get("collector", "")),
                "status":     str(entry.get("status", "pending")),
                "notes":      str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """5 signal class のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for sig in _SIGNAL_CLASSES:
            result.append({
                "signal_id":  sig["signal_id"],
                "sor":        sig["sor"],
                "collector":  sig["collector"],
                "status":     "pending",
                "notes":      "",
            })
        return result
