# k1s0-proof: PROOF-cross_bff-prog-002 -> IMPL-cross_bff-0002
"""tools/lock_yaml_generator/generate_backends.py

backends.lock.yaml 生成器。
src/tier1/lock/backends_input.yaml を読み込み、5 key_class のバックエンド検証結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。

catalog SoT: src/tier1/schema/key_management/classes.yaml / src/tier1/schema/key_management/scenarios.yaml
catalog が存在する場合、宣言された key_class id が全て drill 済みであることを検証する。
catalog が存在しない場合は catalog_validation_status: catalog_absent で graceful degradation する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT
from tools.lock_yaml_generator.lib.catalog_validator import (
    load_catalog,
    validate_catalog_against_input,
    build_catalog_metadata,
)

# backends_input.yaml の想定名
_INPUT_NAME = "backends_input.yaml"

# catalog SoT パス（REPO_ROOT 相対）
_CATALOG_CLASSES_PATH = "src/tier1/schema/key_management/classes.yaml"
_CATALOG_SCENARIOS_PATH = "src/tier1/schema/key_management/scenarios.yaml"

# 5 key_class 定義（05_鍵管理適合仕様.md の v1 key_class セットと一致する）
_KEY_CLASSES: list[dict[str, str]] = [
    # DEK: column-level 暗号化用データ暗号化鍵
    {"key_class": "v1_data_dek", "backend": "software_kms_wrapped", "purpose": "data_encryption"},
    # KEK: DEK をラップする鍵暗号化鍵（HSM PKCS#11 + Shamir M-of-N）
    {"key_class": "v1_data_kek", "backend": "hsm_pkcs11_shamir_distributed", "purpose": "kek_wrapping"},
    # JWT 署名鍵（Keycloak OIDC / DPoP / token exchange）
    {"key_class": "v1_token_signing", "backend": "hsm_pkcs11", "purpose": "signing_jwt"},
    # 監査ログ年次 root 署名鍵（外部公証付き）
    {"key_class": "v1_audit_root_signing", "backend": "hsm_pkcs11", "purpose": "signing_audit_root"},
    # mTLS ワークロード ID（SPIRE SVID）
    {"key_class": "v1_mtls_workload", "backend": "spire", "purpose": "mtls_identity"},
]


class BackendsGenerator(BaseGenerator):
    """backends.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "backends.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/backends_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 key_class のバックエンドリストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        catalog SoT (key_management/classes.yaml) が存在する場合は cross-validation を実行する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # backends キーを読み込む
        raw_backends: list[dict[str, Any]] = inputs.get("backends", [])

        if raw_backends:
            # 入力データから backends を正規化する
            backends = self._normalize_backends(raw_backends)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            backends = self._build_skeleton()

        # catalog SoT のパスを解決する
        classes_path = REPO_ROOT / _CATALOG_CLASSES_PATH
        scenarios_path = REPO_ROOT / _CATALOG_SCENARIOS_PATH

        # catalog yaml を読み込む（不在時は None）
        classes_catalog = load_catalog(classes_path)
        scenarios_catalog = load_catalog(scenarios_path)

        # key_classes catalog の cross-validation: key_classes[].id vs input backends[].key_class
        classes_result = validate_catalog_against_input(
            catalog=classes_catalog,
            input_data=inputs,
            class_key="key_classes",
            input_id_key="key_class",
            input_list_key="backends",
            catalog_path=classes_path,
            catalog_id_key="id",
        )

        # scenarios catalog の cross-validation（scenarios id と drill id の対応がないため passed 扱い）
        scenarios_result = validate_catalog_against_input(
            catalog=scenarios_catalog,
            input_data={},
            class_key="scenarios",
            input_id_key="id",
            input_list_key=None,
            catalog_path=scenarios_path,
            catalog_id_key="id",
        )
        # scenarios は drill 対象外なので常に passed とする
        if scenarios_catalog is not None:
            scenarios_result = {
                "status": "passed",
                "missing": [],
                "catalog_sot_hash": scenarios_result.get("catalog_sot_hash"),
            }

        # metadata を構築する
        catalog_meta = build_catalog_metadata(
            classes_result=classes_result,
            scenarios_result=scenarios_result,
            classes_path=_CATALOG_CLASSES_PATH,
            scenarios_path=_CATALOG_SCENARIOS_PATH,
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_backends.py"
            ),
            "total_backends": len(backends),
            "generated_at":   generated_at,
            "metadata":       catalog_meta,
            "backends":       backends,
        }

    @staticmethod
    def _normalize_backends(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """backend エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "key_class":   str(entry.get("key_class", "")),
                "backend":     str(entry.get("backend", "")),
                "purpose":     str(entry.get("purpose", "")),
                "drill_state": str(entry.get("drill_state", "pending")),
                "notes":       str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """5 key_class のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for kc in _KEY_CLASSES:
            result.append({
                "key_class":   kc["key_class"],
                "backend":     kc["backend"],
                "purpose":     kc["purpose"],
                "drill_state": "pending",
                "notes":       "",
            })
        return result
