# k1s0-proof: PROOF-security-prog-001 -> IMPL-security-0001
# k1s0-impl: IMPL-security-0001 realizes=FR-security-001
"""tools/lock_yaml_generator/generate_threat_model.py

threat_model.lock.yaml 生成器。
src/security/threat_model/catalog/cells.yaml を読み込み cells リストを正規化する。
存在しない場合は total_cells=625 で全 cell を
mitigation_status: explicit_unreachable のスケルトンで生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# cells.yaml の想定パス
_CELLS_YAML = REPO_ROOT / "src/security/threat_model/catalog/cells.yaml"

# スケルトン生成パラメータ
_TOTAL_CELLS = 625


class ThreatModelGenerator(BaseGenerator):
    """threat_model.lock.yaml 生成器。"""

    OUTPUT_NAME = "threat_model.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/security/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/security/threat_model/catalog/cells.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _CELLS_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_CELLS_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """cells リストを正規化して artifact dict を返す。
        inputs が空の場合は 625 cell スケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_cells: list[dict[str, Any]] = inputs.get("cells", [])

        if raw_cells:
            cells = self._normalize_cells(raw_cells)
        else:
            cells = self._build_skeleton()

        # open 件数を集計（mitigation_status == "open"）
        open_count = sum(1 for c in cells if c.get("mitigation_status") == "open")

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_threat_model.py"
            ),
            "total_cells":  len(cells),
            "open_count":   open_count,
            "generated_at": generated_at,
            "cells":        cells,
        }

    @staticmethod
    def _normalize_cells(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """cells エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "cell_id":           str(entry.get("cell_id", "")),
                "threat_class":      str(entry.get("threat_class", "")),
                "mitigation_status": str(entry.get("mitigation_status", "explicit_unreachable")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """625 cell のスケルトンを生成する（全 cell explicit_unreachable）。"""
        result: list[dict[str, Any]] = []
        for index in range(1, _TOTAL_CELLS + 1):
            result.append({
                "cell_id":           f"threat_{index:04d}",
                "threat_class":      "unclassified",
                "mitigation_status": "explicit_unreachable",
            })
        return result
