"""tools/lock_yaml_generator/generate_transport_migration.py

transport_migration.lock.yaml 生成器。
src/tier1/lock/transport_migration_input.yaml を読み込み、Bidi transport switch drill 履歴を正規化する。
存在しない場合はフォールバックスケルトンを生成する（drills: []）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# transport_migration_input.yaml の想定名
_INPUT_NAME = "transport_migration_input.yaml"


class TransportMigrationGenerator(BaseGenerator):
    """transport_migration.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "transport_migration.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/transport_migration_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から transport_migration_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """transport migration drill リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # drills キーを読み込む
        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        # drills が存在する場合は正規化する、存在しない場合は空リストを使用する
        if raw_drills:
            # 入力データから drills を正規化する
            drills = self._normalize_drills(raw_drills)
        else:
            # フォールバック: 空リストを使用する
            drills = []

        # green_count: drill_result が green の drill 数
        green_count = sum(
            1 for d in drills if d.get("drill_result") == "green"
        )
        # status: green_count >= 1 なら green、それ以外は red
        status = "green" if green_count >= 1 else "red"

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_transport_migration.py"
            ),
            # drill 総数
            "total_drills": len(drills),
            # green drill 数
            "green_count": green_count,
            # 全体ステータス（green / red）
            "status": status,
            # 生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
            # 正規化済み drill 一覧
            "drills": drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """transport migration drill エントリを正規化する。"""
        # 正規化済み drill エントリのリストを初期化する
        result: list[dict[str, Any]] = []
        # 各 drill エントリを正規化する
        for entry in raw:
            # 正規化済みエントリを構築する
            result.append({
                # drill_id: ドリル識別子
                "drill_id": str(entry.get("drill_id", "")),
                # from_adapter: 移行元アダプター名
                "from_adapter": str(entry.get("from_adapter", "")),
                # to_adapter: 移行先アダプター名
                "to_adapter": str(entry.get("to_adapter", "")),
                # conformance_classes_tested: テストした適合クラスのリスト
                "conformance_classes_tested": list(entry.get("conformance_classes_tested", [])),
                # drill_result: ドリル実行結果（green / red）
                "drill_result": str(entry.get("drill_result", "pending")),
                # drilled_at: ドリル実行日時（ISO 8601）
                "drilled_at": str(entry.get("drilled_at", "")),
            })
        # 正規化済み drill リストを返す
        return result


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    TransportMigrationGenerator().emit(REPO_ROOT / "src/tier1/lock")
