# k1s0-proof: PROOF-formal-prog-001 -> IMPL-formal-0001
# k1s0-impl: IMPL-formal-0001 realizes=FR-formal-001
"""tools/lock_yaml_generator/generate_proof_matrix.py

proof_matrix.lock.yaml 生成器。
src/formal/proof_matrix/matrix.yaml を読み込み cells リストを正規化する。
存在しない場合は空の cells リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# matrix.yaml の想定パス
_MATRIX_YAML = REPO_ROOT / "src/formal/proof_matrix/matrix.yaml"


class ProofMatrixGenerator(BaseGenerator):
    """proof_matrix.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "proof_matrix.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/formal/proof_matrix/matrix.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # matrix.yaml が存在する場合は読み込む
        if _MATRIX_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_MATRIX_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """cells リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # cells リストを inputs から取得する (なければ空リスト)
        raw_cells: list[dict[str, Any]] = inputs.get("cells", [])
        # cells リストを正規化する
        cells = [
            {
                # cell 識別子
                "cell_id": str(c.get("cell_id", "")),
                # axis 識別子
                "axis": str(c.get("axis", "")),
                # proof_class
                "proof_class": str(c.get("proof_class", "")),
                # cell 状態
                "cell_state": str(c.get("cell_state", "v1_unverified_handled")),
            }
            for c in raw_cells
            if isinstance(c, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_proof_matrix.py"
            ),
            # cell 総数
            "total_cells": len(cells),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # cell リスト
            "cells": cells,
        }
