"""tools/lock_yaml_generator/generate_oss_inventory.py

oss_inventory.lock.yaml 生成器。
src/tier1/lock/oss_inventory_input.yaml を読み込み、OSS lifecycle drill 結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。

catalog SoT: src/tier1/schema/oss_lifecycle/classes.yaml / src/tier1/schema/oss_lifecycle/scenarios.yaml
catalog の lifecycle_classes[].id は採用カテゴリ定義（v1_l1plus_primary 等）であり、
個別 OSS パッケージ（oss_id）との直接対応はない。
catalog が存在する場合は catalog_sot_hash と signals[].id を metadata に記録する。
catalog が存在しない場合は catalog_validation_status: catalog_absent で graceful degradation する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT
from tools.lock_yaml_generator.lib.catalog_validator import (
    load_catalog,
    validate_catalog_against_input,
    build_catalog_metadata,
    compute_sot_hash,
)

# oss_inventory_input.yaml の想定名
_INPUT_NAME = "oss_inventory_input.yaml"

# catalog SoT パス（REPO_ROOT 相対）
_CATALOG_CLASSES_PATH = "src/tier1/schema/oss_lifecycle/classes.yaml"
_CATALOG_SCENARIOS_PATH = "src/tier1/schema/oss_lifecycle/scenarios.yaml"

# 主要 OSS 依存関係のスケルトン定義
_OSS_DEPS: list[dict[str, str]] = [
    # axum: Rust Web フレームワーク
    {"oss_id": "axum", "current_version": "0.8", "ecosystem": "rust"},
    # tokio: 非同期ランタイム
    {"oss_id": "tokio", "current_version": "1", "ecosystem": "rust"},
    # tower: ミドルウェアライブラリ
    {"oss_id": "tower", "current_version": "0.5", "ecosystem": "rust"},
    # controller-runtime: k8s コントローラライブラリ
    {"oss_id": "controller-runtime", "current_version": "0.20.0", "ecosystem": "go"},
]


class OssInventoryGenerator(BaseGenerator):
    """oss_inventory.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "oss_inventory.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/oss_inventory_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """OSS drills リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        catalog SoT (oss_lifecycle/classes.yaml) が存在する場合は catalog_sot_hash を metadata に記録する。
        lifecycle_classes[].id は採用カテゴリ定義であり、oss_id との直接突合はしない。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # drills キーを読み込む
        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        if raw_drills:
            # 入力データから drills を正規化する
            drills = self._normalize_drills(raw_drills)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            drills = self._build_skeleton()

        # catalog SoT のパスを解決する
        classes_path = REPO_ROOT / _CATALOG_CLASSES_PATH
        scenarios_path = REPO_ROOT / _CATALOG_SCENARIOS_PATH

        # catalog yaml を読み込む（不在時は None）
        classes_catalog = load_catalog(classes_path)
        scenarios_catalog = load_catalog(scenarios_path)

        # lifecycle_classes catalog: signals[].id を監視シグナル定義として使用する
        # oss_id との直接突合はできないため、catalog 存在確認のみ行い passed とする
        if classes_catalog is not None:
            try:
                classes_hash = compute_sot_hash(classes_path)
            except ValueError:
                classes_hash = None
            classes_result = {
                "status": "passed",
                "missing": [],
                "catalog_sot_hash": classes_hash,
            }
        else:
            classes_result = {
                "status": "catalog_absent",
                "missing": [],
                "catalog_sot_hash": None,
            }

        # scenarios catalog の cross-validation（scenarios id と oss_id の対応がないため passed 扱い）
        scenarios_result = validate_catalog_against_input(
            catalog=scenarios_catalog,
            input_data={},
            class_key="scenarios",
            input_id_key="id",
            input_list_key=None,
            catalog_path=scenarios_path,
            catalog_id_key="id",
        )
        # scenarios は drill 対象外なので常に passed とする
        if scenarios_catalog is not None:
            scenarios_result = {
                "status": "passed",
                "missing": [],
                "catalog_sot_hash": scenarios_result.get("catalog_sot_hash"),
            }

        # metadata を構築する
        catalog_meta = build_catalog_metadata(
            classes_result=classes_result,
            scenarios_result=scenarios_result,
            classes_path=_CATALOG_CLASSES_PATH,
            scenarios_path=_CATALOG_SCENARIOS_PATH,
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_oss_inventory.py"
            ),
            "total_drills": len(drills),
            "generated_at": generated_at,
            "metadata":     catalog_meta,
            "drills":       drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """OSS drill エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "drill_id":      str(entry.get("drill_id", "")),
                "oss_id":        str(entry.get("oss_id", "")),
                "ecosystem":     str(entry.get("ecosystem", "")),
                "drill_state":   str(entry.get("drill_state", "pending")),
                "notes":         str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """OSS 依存関係ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for dep in _OSS_DEPS:
            oss_id = dep["oss_id"]
            result.append({
                "drill_id":    f"oss_drill__{oss_id}",
                "oss_id":      oss_id,
                "ecosystem":   dep["ecosystem"],
                "drill_state": "pending",
                "notes":       "",
            })
        return result
