"""tools/lock_yaml_generator/generate_preservation_substrates.py

preservation_substrates.lock.yaml 生成器。
src/data/preservation/classes.yaml を読み込み、5 preservation_class と substrates リストを返す。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# classes.yaml の想定パス
_CLASSES_YAML = REPO_ROOT / "src/data/preservation/classes.yaml"

# 5 preservation_class 定義
_PRESERVATION_CLASSES: list[dict[str, Any]] = [
    {
        "class_id":    "v1_local_only",
        "class_name":  "v1_local_only",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_zone_redundant",
        "class_name":  "v1_zone_redundant",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_cross_region",
        "class_name":  "v1_cross_region",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_cross_region_with_archive",
        "class_name":  "v1_cross_region_with_archive",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_global_replicated",
        "class_name":  "v1_global_replicated",
        "drill_state": "pending",
    },
]


class PreservationSubstratesGenerator(BaseGenerator):
    """preservation_substrates.lock.yaml 生成器。"""

    OUTPUT_NAME = "preservation_substrates.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/data/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/data/preservation/classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _CLASSES_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_CLASSES_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 preservation_class + substrates リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_classes: list[dict[str, Any]] = inputs.get("classes", [])
        raw_substrates: list[dict[str, Any]] = inputs.get("substrates", [])

        if len(raw_classes) >= 5:
            classes = self._normalize_classes(raw_classes)
        else:
            classes = list(_PRESERVATION_CLASSES)

        # substrates リストを正規化（入力がなければ空）
        substrates = self._normalize_substrates(raw_substrates)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_preservation_substrates.py"
            ),
            "total_classes":    len(classes),
            "total_substrates": len(substrates),
            "generated_at":     generated_at,
            "classes":          classes,
            "substrates":       substrates,
        }

    @staticmethod
    def _normalize_classes(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """preservation_class エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "class_id":    str(entry.get("class_id", "")),
                "class_name":  str(entry.get("class_name", "")),
                "drill_state": str(entry.get("drill_state", "pending")),
            })
        return result

    @staticmethod
    def _normalize_substrates(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """substrates エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "substrate_id": str(entry.get("substrate_id", "")),
                "class_id":     str(entry.get("class_id", "")),
                "description":  str(entry.get("description", "")),
                "status":       str(entry.get("status", "pending")),
            })
        return result
