"""tools/lock_yaml_generator/generate_idp_capabilities.py

idp_capabilities.lock.yaml 生成器。
src/tier1/lock/idp_capabilities_input.yaml を読み込み、認証 IdP capability 一覧を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 status: pending）。

catalog SoT: src/tier1/schema/auth/classes.yaml / src/tier1/schema/auth/scenarios.yaml
catalog が存在する場合、宣言された auth_class id が全て drill 済みであることを検証する。
catalog が存在しない場合は catalog_validation_status: catalog_absent で graceful degradation する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT
from tools.lock_yaml_generator.lib.catalog_validator import (
    load_catalog,
    validate_catalog_against_input,
    build_catalog_metadata,
)

# idp_capabilities_input.yaml の想定名
_INPUT_NAME = "idp_capabilities_input.yaml"

# catalog SoT パス（REPO_ROOT 相対）
_CATALOG_CLASSES_PATH = "src/tier1/schema/auth/classes.yaml"
_CATALOG_SCENARIOS_PATH = "src/tier1/schema/auth/scenarios.yaml"

# 04_認証適合仕様.md §v1 auth_class セット（5 class）に基づく IdP capability 定義
_IDP_CAPABILITIES: list[dict[str, str]] = [
    # v1_human_session: OIDC code flow + DPoP 鍵束縛（RFC 9449）、rotating refresh
    {"idp_id": "v1_human_session", "auth_protocol": "oidc_dpop_bound"},
    # v1_workload_jwt: K8s ServiceAccount projection or SPIFFE/SPIRE SVID、短 TTL
    {"idp_id": "v1_workload_jwt", "auth_protocol": "jwt_svid"},
    # v1_device_attest: TPM / HSM / WebAuthn platform authenticator device cert、長 TTL、one_shot refresh
    {"idp_id": "v1_device_attest", "auth_protocol": "jwt_attested"},
    # v1_federated_exchange: RFC 8693 token exchange、audience-restricted 短命 JWT
    {"idp_id": "v1_federated_exchange", "auth_protocol": "token_exchange"},
    # v1_emergency_step_up: break-glass、always step_up + always step_up WebAuthn/FIDO2、<10m、no refresh
    {"idp_id": "v1_emergency_step_up", "auth_protocol": "oidc_dpop_stepup"},
]


class IdpCapabilitiesGenerator(BaseGenerator):
    """idp_capabilities.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "idp_capabilities.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/idp_capabilities_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """IdP capabilities リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        catalog SoT (auth/classes.yaml) が存在する場合は cross-validation を実行する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # capabilities キーを読み込む
        raw_caps: list[dict[str, Any]] = inputs.get("capabilities", [])

        if raw_caps:
            # 入力データから capabilities を正規化する
            capabilities = self._normalize_caps(raw_caps)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            capabilities = self._build_skeleton()

        # catalog SoT のパスを解決する
        classes_path = REPO_ROOT / _CATALOG_CLASSES_PATH
        scenarios_path = REPO_ROOT / _CATALOG_SCENARIOS_PATH

        # catalog yaml を読み込む（不在時は None）
        classes_catalog = load_catalog(classes_path)
        scenarios_catalog = load_catalog(scenarios_path)

        # auth_classes catalog の cross-validation: auth_classes[].id vs input capabilities[].idp_id
        classes_result = validate_catalog_against_input(
            catalog=classes_catalog,
            input_data=inputs,
            class_key="auth_classes",
            input_id_key="idp_id",
            input_list_key="capabilities",
            catalog_path=classes_path,
            catalog_id_key="id",
        )

        # scenarios catalog の cross-validation（scenarios id と drill id の対応がないため passed 扱い）
        scenarios_result = validate_catalog_against_input(
            catalog=scenarios_catalog,
            input_data={},
            class_key="scenarios",
            input_id_key="id",
            input_list_key=None,
            catalog_path=scenarios_path,
            catalog_id_key="id",
        )
        # scenarios は drill 対象外なので常に passed とする
        if scenarios_catalog is not None:
            scenarios_result = {
                "status": "passed",
                "missing": [],
                "catalog_sot_hash": scenarios_result.get("catalog_sot_hash"),
            }

        # metadata を構築する
        catalog_meta = build_catalog_metadata(
            classes_result=classes_result,
            scenarios_result=scenarios_result,
            classes_path=_CATALOG_CLASSES_PATH,
            scenarios_path=_CATALOG_SCENARIOS_PATH,
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_idp_capabilities.py"
            ),
            "total_capabilities": len(capabilities),
            "generated_at":       generated_at,
            "metadata":           catalog_meta,
            "capabilities":       capabilities,
        }

    @staticmethod
    def _normalize_caps(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """IdP capability エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "idp_id":        str(entry.get("idp_id", "")),
                "auth_protocol": str(entry.get("auth_protocol", "")),
                "status":        str(entry.get("status", "pending")),
                "notes":         str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """IdP ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for cap in _IDP_CAPABILITIES:
            result.append({
                "idp_id":        cap["idp_id"],
                "auth_protocol": cap["auth_protocol"],
                "status":        "pending",
                "notes":         "",
            })
        return result
