"""tools/lock_yaml_generator/generate_second_industry_stub.py

second_industry_stub.lock.yaml 生成器。
src/tier2/pack/_stub_service/ の物理存在を確認し、
第二業界 stub の compile_status を lock artifact として生成する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# stub サービスディレクトリのパス
_STUB_SERVICE_PATH = REPO_ROOT / "src/tier2/pack/_stub_service"

# manufacturing pack との diff スクリプトパス
_DIFF_SCRIPT_PATH = REPO_ROOT / "src/tier2/pack/diff_stub_vs_manufacturing.sh"

# stub サービスのパス文字列（artifact に記録する）
_STUB_PATH = "src/tier2/pack/_stub_service"


class SecondIndustryStubGenerator(BaseGenerator):
    """second_industry_stub.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "second_industry_stub.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/pack/_stub_service/ ディレクトリの存在を確認する。
        存在する場合はディレクトリパスを返す。存在しない場合は空 dict を返す。
        """
        # stub ディレクトリの存在を確認する
        if _STUB_SERVICE_PATH.exists() and _STUB_SERVICE_PATH.is_dir():
            # ディレクトリが存在することを示すフラグを返す
            return {"stub_dir_exists": True}
        # ディレクトリが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """第二業界スタブのコンパイル状態を表す artifact dict を返す。
        stub ディレクトリと diff スクリプトが揃っている場合は compile_status='green'。
        """
        # 生成日時を記録する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # stub ディレクトリの存在確認
        stub_exists = inputs.get("stub_dir_exists", False)
        # diff スクリプトの存在確認
        diff_script_exists = _DIFF_SCRIPT_PATH.exists()
        # stub と diff スクリプトが揃っている場合は green
        compile_status = "green" if (stub_exists and diff_script_exists) else "declared"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_second_industry_stub.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # コンパイルステータス（stub + diff スクリプトの物理存在で決定する）
            "compile_status": compile_status,
            # stub サービスのパス
            "stub_service_path": str(_STUB_SERVICE_PATH),
            # diff スクリプトの存在フラグ
            "diff_script_exists": diff_script_exists,
        }
