"""tools/lock_yaml_generator/generate_capabilities.py

capabilities.lock.yaml 生成器。
src/tier1/lock/capabilities_input.yaml を読み込む。
存在しない場合は conformance_classes=5, adapters=8, total_cells=40 のスケルトンを生成する。
全 status: pending。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# capabilities_input.yaml は lock_dir 内に置かれる
_INPUT_NAME = "capabilities_input.yaml"

# スケルトン定義
_CONFORMANCE_CLASSES: list[str] = [
    "v1_bidi_streaming",
    "v1_unary_rpc",
    "v1_server_streaming",
    "v1_client_streaming",
    "v1_connect_protocol",
]

_ADAPTERS: list[str] = [
    "grpc_go",
    "grpc_java",
    "grpc_python",
    "grpc_node",
    "connect_go",
    "connect_web",
    "grpc_web",
    "dotnet_grpc",
]


class CapabilitiesGenerator(BaseGenerator):
    """capabilities.lock.yaml 生成器。"""

    OUTPUT_NAME = "capabilities.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/capabilities_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """conformance_classes × adapters の cell matrix を構築する。
        inputs が空の場合はスケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_cells: list[dict[str, Any]] = inputs.get("cells", [])

        if raw_cells:
            cells = self._normalize_cells(raw_cells)
        else:
            cells = self._build_skeleton()

        total_cells = len(cells)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_capabilities.py"
            ),
            "conformance_classes": len(_CONFORMANCE_CLASSES),
            "adapters":            len(_ADAPTERS),
            "total_cells":         total_cells,
            "generated_at":        generated_at,
            "cells":               cells,
        }

    @staticmethod
    def _normalize_cells(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """capabilities cells エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "cell_id":            str(entry.get("cell_id", "")),
                "conformance_class":  str(entry.get("conformance_class", "")),
                "adapter":            str(entry.get("adapter", "")),
                "status":             str(entry.get("status", "pending")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """conformance_classes × adapters = 5 × 8 = 40 cell のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for cc in _CONFORMANCE_CLASSES:
            for adapter in _ADAPTERS:
                cell_id = f"{cc}__{adapter}"
                result.append({
                    "cell_id":           cell_id,
                    "conformance_class": cc,
                    "adapter":           adapter,
                    "status":            "pending",
                })
        return result
