"""tools/lock_yaml_generator/generate_ops_ownership_table.py

ops 軸の ownership_table.lock.yaml 生成器。
src/ops/ownership/table.yaml を読み込み entries リストを正規化する。
存在しない場合は空の entries リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# table.yaml の想定パス
_TABLE_YAML = REPO_ROOT / "src/ops/ownership/table.yaml"


class OpsOwnershipTableGenerator(BaseGenerator):
    """ops 軸の ownership_table.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "ownership_table.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/ops/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/ops/ownership/table.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # table.yaml が存在する場合は読み込む
        if _TABLE_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_TABLE_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """entries リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # entries リストを inputs から取得する (なければ空リスト)
        raw_entries: list[dict[str, Any]] = inputs.get("entries", [])
        # entries リストを正規化する
        entries = [
            {
                # エントリ識別子
                "entry_id": str(e.get("entry_id", "")),
                # サービス名
                "service": str(e.get("service", "")),
                # dev オーナー
                "dev_owner": str(e.get("dev_owner", "unassigned")),
                # ops オーナー
                "ops_owner": str(e.get("ops_owner", "unassigned")),
            }
            for e in raw_entries
            if isinstance(e, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_ops_ownership_table.py"
            ),
            # entry 総数
            "total_entries": len(entries),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # entry リスト
            "entries": entries,
        }
