# k1s0-proof: PROOF-security-prog-003 -> IMPL-security-0003
# k1s0-impl: IMPL-security-0003 realizes=FR-security-003
"""tools/lock_yaml_generator/generate_mitigation_bindings.py

mitigation_bindings.lock.yaml 生成器。
src/security/threat_model/mitigation_bindings.yaml を読み込み bindings リストを正規化する。
存在しない場合は空の bindings リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# mitigation_bindings.yaml の想定パス
_BINDINGS_YAML = REPO_ROOT / "src/security/threat_model/mitigation_bindings.yaml"


class MitigationBindingsGenerator(BaseGenerator):
    """mitigation_bindings.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "mitigation_bindings.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/security/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/security/threat_model/mitigation_bindings.yaml を読み込む。"""
        # mitigation_bindings.yaml が存在する場合は読み込む
        if _BINDINGS_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_BINDINGS_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """bindings リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # bindings リストを inputs から取得する (なければ空リスト)
        raw_bindings: list[dict[str, Any]] = inputs.get("bindings", [])
        # bindings リストを正規化する
        bindings = [
            {
                # binding 識別子
                "binding_id": str(b.get("binding_id", "")),
                # 対象 threat_class
                "threat_class": str(b.get("threat_class", "")),
                # mitigation クラス
                "mitigation_class": str(b.get("mitigation_class", "")),
                # 状態
                "status": str(b.get("status", "bound")),
            }
            for b in raw_bindings
            if isinstance(b, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_mitigation_bindings.py"
            ),
            # binding 総数
            "total_bindings": len(bindings),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # binding リスト
            "bindings": bindings,
        }
