# k1s0-proof: PROOF-infra-prog-001 -> IMPL-infra-0001
# k1s0-impl: IMPL-infra-0001 realizes=FR-infra-001
"""tools/lock_yaml_generator/generate_topology_class.py

topology_class.lock.yaml 生成器。
src/infra/topology/classes.yaml を読み込み、5 topology_class を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# classes.yaml の想定パス
_CLASSES_YAML = REPO_ROOT / "src/infra/topology/classes.yaml"

# 5 topology_class 定義
_TOPOLOGY_CLASSES: list[dict[str, Any]] = [
    {
        "class_id":   "v1_single_zone",
        "class_name": "v1_single_zone",
        "drill_state": "pending",
    },
    {
        "class_id":   "v1_multi_zone_per_cluster",
        "class_name": "v1_multi_zone_per_cluster",
        "drill_state": "pending",
    },
    {
        "class_id":   "v1_active_passive_dr",
        "class_name": "v1_active_passive_dr",
        "drill_state": "pending",
    },
    {
        "class_id":   "v1_multi_region_active_passive",
        "class_name": "v1_multi_region_active_passive",
        "drill_state": "pending",
    },
    {
        "class_id":   "v1_multi_region_active_active",
        "class_name": "v1_multi_region_active_active",
        "drill_state": "pending",
    },
]


class TopologyClassGenerator(BaseGenerator):
    """topology_class.lock.yaml 生成器。"""

    OUTPUT_NAME = "topology_class.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/infra/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/infra/topology/classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _CLASSES_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_CLASSES_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 topology_class を正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # topology_classes または classes キーを受け入れる
        raw_classes: list[dict[str, Any]] = inputs.get("topology_classes", inputs.get("classes", []))

        if len(raw_classes) >= 5:
            classes = self._normalize_classes(raw_classes)
        else:
            # 5 class 揃っていなければフォールバック
            classes = list(_TOPOLOGY_CLASSES)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_topology_class.py"
            ),
            "total_classes": len(classes),
            "generated_at":  generated_at,
            "classes":       classes,
        }

    @staticmethod
    def _normalize_classes(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """topology_class エントリを正規化する。class_id を class_name の代替として受け入れる。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            # class_name が無い場合は class_id を使う
            class_id = str(entry.get("class_id", ""))
            result.append({
                "class_id":    class_id,
                "class_name":  str(entry.get("class_name", class_id)),
                "drill_state": str(entry.get("drill_state", "pending")),
            })
        return result
