# k1s0-proof: PROOF-cross_pii-prog-002 -> IMPL-cross_pii-0002
"""tools/lock_yaml_generator/generate_scenario_catalog.py

scenario_catalog.lock.yaml 生成器。
src/security/threat_model/scenarios.yaml を読み込み scenarios リストを正規化する。
存在しない場合は空の scenarios リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# scenarios.yaml の想定パス
_SCENARIOS_YAML = REPO_ROOT / "src/security/threat_model/scenarios.yaml"


class ScenarioCatalogGenerator(BaseGenerator):
    """scenario_catalog.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "scenario_catalog.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/security/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/security/threat_model/scenarios.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # scenarios.yaml が存在する場合は読み込む
        if _SCENARIOS_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_SCENARIOS_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """scenarios リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # scenarios リストを inputs から取得する (なければ空リスト)
        raw_scenarios: list[dict[str, Any]] = inputs.get("scenarios", [])
        # scenarios リストを正規化する
        scenarios = [
            {
                # シナリオ識別子
                "scenario_id": str(s.get("scenario_id", "")),
                # actor クラス
                "actor_class": str(s.get("actor_class", "")),
                # 状態
                "status": str(s.get("status", "active")),
            }
            for s in raw_scenarios
            if isinstance(s, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_scenario_catalog.py"
            ),
            # scenario 総数
            "total_scenarios": len(scenarios),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # scenario リスト
            "scenarios": scenarios,
        }
