"""tools/lock_yaml_generator/generate_enforcement_points.py

enforcement_points.lock.yaml 生成器。
src/tier1/lock/enforcement_points_input.yaml を読み込み、テナント容量 drill 結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# enforcement_points_input.yaml の想定名
_INPUT_NAME = "enforcement_points_input.yaml"

# 09_テナント容量適合仕様.md §v1 quota_class セット（5 class）に基づく enforcement point 定義
_ENFORCEMENT_LAYERS: list[dict[str, str]] = [
    # v1_per_tenant_qps: Envoy Local Rate Limit filter、burst 2x 許容、reject_429
    {"layer_id": "v1_per_tenant_qps", "layer_type": "transport"},
    # v1_per_tenant_concurrency: Library token bucket（in-process）、queue_with_timeout
    {"layer_id": "v1_per_tenant_concurrency", "layer_type": "library"},
    # v1_per_tenant_volume: storage layer（Rook+Ceph / CloudNativePG / ClickHouse / Kafka）、overflow_to_cold
    {"layer_id": "v1_per_tenant_volume", "layer_type": "storage"},
    # v1_per_tenant_compute: OSS native quota（Temporal / KEDA / pgvector）、shed_by_priority
    {"layer_id": "v1_per_tenant_compute", "layer_type": "infrastructure"},
    # v1_global_fair_queue: broker layer（Kafka partition rebalance / Istio destination rule）、partition_rebalance
    {"layer_id": "v1_global_fair_queue", "layer_type": "broker"},
]


class EnforcementPointsGenerator(BaseGenerator):
    """enforcement_points.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "enforcement_points.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/enforcement_points_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """enforcement drills リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # drills キーを読み込む
        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        if raw_drills:
            # 入力データから drills を正規化する
            drills = self._normalize_drills(raw_drills)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            drills = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_enforcement_points.py"
            ),
            "total_drills": len(drills),
            "generated_at": generated_at,
            "drills":       drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """enforcement drill エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "drill_id":   str(entry.get("drill_id", "")),
                "layer_id":   str(entry.get("layer_id", "")),
                "layer_type": str(entry.get("layer_type", "")),
                "drill_state": str(entry.get("drill_state", "pending")),
                "notes":      str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """enforcement layer ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for layer in _ENFORCEMENT_LAYERS:
            layer_id = layer["layer_id"]
            result.append({
                "drill_id":   f"capacity_drill__{layer_id}",
                "layer_id":   layer_id,
                "layer_type": layer["layer_type"],
                "drill_state": "pending",
                "notes":      "",
            })
        return result
