# k1s0-proof: PROOF-data-prog-003 -> IMPL-data-0002
# k1s0-impl: IMPL-data-0002 realizes=FR-data-002
"""tools/lock_yaml_generator/generate_restore_drill.py

restore_drill.lock.yaml 生成器。
src/data/preservation/drill.yaml を読み込み、drills リストを正規化する。
存在しない場合は 5 preservation_class に対応する 5 drill entry のスケルトンを生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# drill.yaml の想定パス
_DRILL_YAML = REPO_ROOT / "src/data/preservation/drill.yaml"

# 5 preservation_class（スケルトン生成用）
_PRESERVATION_CLASSES: list[str] = [
    "v1_local_only",
    "v1_zone_redundant",
    "v1_cross_region",
    "v1_cross_region_with_archive",
    "v1_global_replicated",
]


class RestoreDrillGenerator(BaseGenerator):
    """restore_drill.lock.yaml 生成器。"""

    OUTPUT_NAME = "restore_drill.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/data/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/data/preservation/drill.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _DRILL_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_DRILL_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """drills リストを正規化して artifact dict を返す。
        inputs が空の場合は 5 preservation_class に対応するスケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        if raw_drills:
            drills = self._normalize_drills(raw_drills)
        else:
            drills = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_restore_drill.py"
            ),
            "total_drills": len(drills),
            "generated_at": generated_at,
            "drills":       drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """drill エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "drill_id":           str(entry.get("drill_id", "")),
                "preservation_class": str(entry.get("preservation_class", "")),
                "drill_state":        str(entry.get("drill_state", "pending")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """5 preservation_class に対応するスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for pc in _PRESERVATION_CLASSES:
            result.append({
                "drill_id":           f"restore__{pc}",
                "preservation_class": pc,
                "drill_state":        "pending",
            })
        return result
