"""tools/lock_yaml_generator/generate_manufacturing_stress.py

manufacturing_stress.lock.yaml 生成器。
src/test/playwright/manufacturing_stress/ 配下の 9 spec ディレクトリを走査し、
各 spec の conformance_class と assertion_ids を記録した lock.yaml を生成する。
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT


# spec ディレクトリ → (spec_name, conformance_class) のマッピングを定義する
_SPEC_CATALOG: list[tuple[str, str, str]] = [
    ("01_equipment_remote", "設備リモート操作", "v1_interactive"),
    ("02_line_monitoring", "ライン稼働監視", "v1_live_snapshot"),
    ("03_quality_inspection", "品質検査結果配信", "v1_event_feed"),
    ("04_scada_telemetry", "SCADA テレメトリ収集", "v1_bulk_upload"),
    ("05_drawing_review", "図面 collaborative review", "v1_interactive"),
    ("06_inventory_display", "在庫最新値表示", "v1_live_snapshot"),
    ("07_order_subscription", "受注 sub", "v1_event_feed"),
    ("08_alarm_delivery", "警報配信", "v1_alert"),
    ("09_measurement_stream", "計量装置連続データ", "v1_bulk_upload"),
]

# spec ファイル内の conformanceAssert アノテーションを抽出する正規表現を定義する
_ASSERT_PATTERN = re.compile(
    r"@conformanceAssert\(\[([^\]]+)\]\)",
    re.DOTALL,
)


class ManufacturingStressGenerator(BaseGenerator):
    """manufacturing_stress.lock.yaml 生成器。

    9 spec ディレクトリを走査して spec 情報を収集し、
    各 spec の conformance_class と assertion_ids を lock.yaml に記録する。
    """

    # 出力ファイル名を定義する
    OUTPUT_NAME = "manufacturing_stress.lock.yaml"
    # 入力として必要なファイルはない（ディレクトリ走査のみ）
    REQUIRED_INPUTS: list[str] = []
    # JSON Schema パスは未設定
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリは tier1/lock を使用する
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """入力として lock_dir を渡すコンテナを返す。"""
        # lock_dir を inputs に格納して build_artifact に渡す
        return {"lock_dir": lock_dir}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """manufacturing_stress 9 spec の情報を収集して artifact dict を返す。"""
        # manufacturing_stress ディレクトリのパスを組み立てる
        stress_dir = REPO_ROOT / "src" / "test" / "playwright" / "manufacturing_stress"

        # 9 spec の情報を収集するリストを初期化する
        specs: list[dict[str, Any]] = []

        # _SPEC_CATALOG の各 spec を処理する
        for dir_name, spec_name, conformance_class in _SPEC_CATALOG:
            # spec ディレクトリのパスを組み立てる
            spec_dir = stress_dir / dir_name
            # spec ファイルを検索する（*.spec.ts を探す）
            spec_files = list(spec_dir.glob("*.spec.ts"))
            # spec ファイルが存在するかどうかを確認する
            spec_exists = len(spec_files) > 0

            # assertion_ids を収集するリストを初期化する
            assertion_ids: list[str] = []

            # spec ファイルが存在する場合は conformanceAssert を抽出する
            if spec_exists:
                for spec_file in spec_files:
                    # spec ファイルの内容を読み込む
                    content = spec_file.read_text(encoding="utf-8")
                    # conformanceAssert アノテーションを抽出する
                    for m in _ASSERT_PATTERN.finditer(content):
                        # 各 assertion id を抽出して正規化する
                        raw_ids = m.group(1)
                        for id_raw in raw_ids.split(","):
                            # 前後の空白とクォートを除去して追加する
                            clean = id_raw.strip().strip('"').strip("'").strip()
                            if clean and clean not in assertion_ids:
                                assertion_ids.append(clean)

            # spec 情報を辞書に格納する
            spec_entry: dict[str, Any] = {
                # spec ディレクトリ名を記録する
                "dir_name": dir_name,
                # spec 名称（日本語）を記録する
                "spec_name": spec_name,
                # conformance クラスを記録する
                "conformance_class": conformance_class,
                # spec ファイルが存在するかどうかを記録する
                "spec_implemented": spec_exists,
                # spec ファイルのパスを記録する（存在しない場合は None）
                "spec_path": str(spec_files[0].relative_to(REPO_ROOT)) if spec_files else None,
                # 抽出した assertion_ids を記録する
                "assertion_ids": assertion_ids,
            }
            specs.append(spec_entry)

        # 実装済み spec の数を集計する
        implemented_count = sum(1 for s in specs if s["spec_implemented"])
        # 全 spec が実装済みかどうかを確認する
        all_implemented = implemented_count == 9
        # overall status を決定する
        overall_status = "green" if all_implemented else "yellow"

        # artifact dict を組み立てて返す
        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_manufacturing_stress.py"
            ),
            # overall status を記録する（9/9 実装済みで green）
            "status": overall_status,
            # 実装済み spec 数を記録する
            "implemented_count": implemented_count,
            # 全 spec 数を記録する
            "total_count": 9,
            # ship blocker 宣言: 01_Bidi 適合仕様 §158-160
            "ship_blocker_ref": "docs/04_詳細設計/01_適合仕様/01_Bidi適合仕様.md §158-160",
            # 各 spec の詳細情報を記録する
            "specs": specs,
        }
