"""tools/lock_yaml_generator/generate_second_industry_stub.py

# second_industry_stub.lock.yaml 生成器。
# src/tier2/pack/_stub_service/ ディレクトリを確認し、
# 第二業界スタブサービスのコンパイル状態を lock artifact として生成する。
# ディレクトリが存在しない場合は compile_status='declared' を返す。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# _stub_service ディレクトリの想定パス
_STUB_SERVICE_DIR = REPO_ROOT / "src/tier2/pack/_stub_service"

# stub サービスのパス文字列（artifact に記録する）
_STUB_PATH = "src/tier2/pack/_stub_service"


class SecondIndustryStubGenerator(BaseGenerator):
    """second_industry_stub.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "second_industry_stub.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/pack/_stub_service/ ディレクトリの存在を確認する。
        存在する場合はディレクトリパスを返す。存在しない場合は空 dict を返す。
        """
        # _stub_service ディレクトリが存在する場合は存在フラグを返す
        if _STUB_SERVICE_DIR.exists() and _STUB_SERVICE_DIR.is_dir():
            # ディレクトリが存在することを示すフラグを返す
            return {"stub_service_dir_exists": True}
        # ディレクトリが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """第二業界スタブのコンパイル状態を表す artifact dict を返す。
        ディレクトリが存在しない場合は compile_status='declared'。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # _stub_service ディレクトリの存在を確認する
        stub_service_exists = inputs.get("stub_service_dir_exists", False)

        # ディレクトリの存在に関わらず compile_status は declared とする
        # （物理コンパイル検証は Stage 3 で実施）
        compile_status = "declared"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_second_industry_stub.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # コンパイルステータス（物理検証は Stage 3 で実施）
            "compile_status": compile_status,
            # stub サービスのパス
            "stub_path": _STUB_PATH,
            # stub サービスディレクトリの存在状態
            "stub_service_dir_exists": stub_service_exists,
        }
