"""tools/lock_yaml_generator/generate_test_matrix.py

# test_matrix.lock.yaml 生成器。
# src/tier3/test_matrix.yaml を読み込み、
# テストシナリオの宣言状態を lock artifact として生成する。
# 各 scenario の status は 'declared' (物理実装は Stage 4 で実施)。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# test_matrix.yaml の想定パス
_TEST_MATRIX_YAML = REPO_ROOT / "src/tier3/test_matrix.yaml"


class TestMatrixGenerator(BaseGenerator):
    """test_matrix.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "test_matrix.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier3/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier3/test_matrix.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # ファイルが存在する場合のみ読み込む
        if _TEST_MATRIX_YAML.exists():
            # PyYAML を使って YAML を読み込む
            import yaml  # type: ignore
            # テキストを読み込んで YAML パースする
            raw = yaml.safe_load(_TEST_MATRIX_YAML.read_text(encoding="utf-8"))
            # dict であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """テストシナリオの宣言状態を表す artifact dict を返す。
        全 scenario の status は 'declared' (物理実装は Stage 4 で実施)。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # scenarios キーからシナリオ一覧を取得する
        raw_scenarios: list[dict[str, Any]] = inputs.get("scenarios", [])

        # シナリオが存在する場合は正規化して declared を付与する
        if raw_scenarios:
            # 各シナリオを正規化して declared として登録する
            scenarios = [
                {
                    # scenario_id: 元データの scenario_id を使用
                    "scenario_id": str(entry.get("scenario_id", "")),
                    # status: 物理実装は Stage 4 のため declared とする
                    "status": "declared",
                }
                for entry in raw_scenarios
            ]
        else:
            # フォールバック: スケルトンシナリオを使用する
            scenarios = [
                # 発注承認シナリオのスケルトン
                {"scenario_id": "s01_order_approval_st_advance",         "status": "declared"},
                # offline 記録シナリオのスケルトン
                {"scenario_id": "s02_factory_offline_5_items_pq_resume", "status": "declared"},
            ]

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_test_matrix.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # 総シナリオ数
            "total_scenarios": len(scenarios),
            # シナリオ一覧（全て declared）
            "scenarios": scenarios,
        }
