"""tools/lock_yaml_generator/generate_performance_baseline.py

performance_baseline.lock.yaml 生成器。
src/test/performance/baselines.yaml を読み込み baselines リストを正規化する。
存在しない場合は空の baselines リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# baselines.yaml の想定パス
_BASELINES_YAML = REPO_ROOT / "src/test/performance/baselines.yaml"


class PerformanceBaselineGenerator(BaseGenerator):
    """performance_baseline.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "performance_baseline.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/performance/baselines.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # baselines.yaml が存在する場合は読み込む
        if _BASELINES_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_BASELINES_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """baselines リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # baselines リストを inputs から取得する (なければ空リスト)
        raw_baselines: list[dict[str, Any]] = inputs.get("baselines", [])
        # baselines リストを正規化する
        baselines = [
            {
                # baseline 識別子
                "baseline_id": str(b.get("baseline_id", "")),
                # メトリクス名
                "metric": str(b.get("metric", "")),
                # 基準値
                "threshold": b.get("threshold", 0),
                # 単位
                "unit": str(b.get("unit", "")),
                # 状態
                "status": str(b.get("status", "active")),
            }
            for b in raw_baselines
            if isinstance(b, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_performance_baseline.py"
            ),
            # baseline 総数
            "total_baselines": len(baselines),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # baseline リスト
            "baselines": baselines,
        }
