"""tools/lock_yaml_generator/generate_repository_layout.py

repository_layout.lock.yaml 生成器。
ARCHITECTURE.md から root allowlist を読み込み、実際のファイル一覧と比較して
violations リストを構築する。ARCHITECTURE.md が見つからなければ status: yellow。
違反がなければ green、違反があれば red。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# root で許可されるファイル名（固定 allowlist）
_ALLOWED_ROOT_FILES: frozenset[str] = frozenset({
    "CLAUDE.md",
    "README.md",
    "LICENSE",
    "ARCHITECTURE.md",
    ".claudeignore",
    ".gitignore",
    "Makefile",
    "pyproject.toml",
    "requirements.txt",
    # uv パッケージマネージャが生成するロックファイル
    "uv.lock",
})

# root で許可されるディレクトリ名（dot-prefix hidden dir はスキップ）
_ALLOWED_ROOT_DIRS: frozenset[str] = frozenset({
    "src",
    "docs",
    "tools",
    "img",
    ".github",
    ".claude",
    ".git",
})

_ARCHITECTURE_MD = REPO_ROOT / "ARCHITECTURE.md"


class RepositoryLayoutGenerator(BaseGenerator):
    """repository_layout.lock.yaml 生成器。"""

    OUTPUT_NAME = "repository_layout.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/_meta/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """ARCHITECTURE.md を読み込み、root allowlist を抽出する。
        また実際のリポジトリ root のファイル・ディレクトリ一覧も取得する。
        """
        result: dict[str, Any] = {}

        # ARCHITECTURE.md の存在確認と内容取得
        if _ARCHITECTURE_MD.exists():
            result["architecture_md_found"] = True
            result["architecture_md_content"] = _ARCHITECTURE_MD.read_text(encoding="utf-8")
        else:
            result["architecture_md_found"] = False
            result["architecture_md_content"] = ""

        # リポジトリ root の実際のエントリを取得（隠しファイルを含む）
        root_entries: list[dict[str, Any]] = []
        for p in REPO_ROOT.iterdir():
            root_entries.append({
                "name":     p.name,
                "is_dir":  p.is_dir(),
                "is_file": p.is_file(),
            })
        result["root_entries"] = root_entries

        return result

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """violations リストを構築して artifact dict を返す。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        if not inputs.get("architecture_md_found", False):
            return {
                "_AUTO_GENERATED": (
                    "DO NOT EDIT. Generated by"
                    " tools/lock_yaml_generator/generate_repository_layout.py"
                ),
                "status":       "yellow",
                "detail":       "ARCHITECTURE.md not found (pending)",
                "violations":   [],
                "generated_at": generated_at,
            }

        # root エントリを検査して違反を収集
        root_entries: list[dict[str, Any]] = inputs.get("root_entries", [])
        violations: list[dict[str, Any]] = []

        for entry in root_entries:
            name = entry["name"]
            is_dir = entry["is_dir"]
            is_file = entry["is_file"]

            if is_dir:
                # dot-prefix 隠しディレクトリ（.git/.venv/.pytest_cache 等）はスキップ
                if name.startswith("."):
                    continue
                if name not in _ALLOWED_ROOT_DIRS:
                    violations.append({
                        "name":   name,
                        "type":   "directory",
                        "reason": f"root directory '{name}' is not in allowed list",
                    })
            elif is_file:
                if name not in _ALLOWED_ROOT_FILES:
                    violations.append({
                        "name":   name,
                        "type":   "file",
                        "reason": f"root file '{name}' is not in allowed list",
                    })

        status = "green" if not violations else "red"
        detail = (
            "no violations detected"
            if not violations
            else f"{len(violations)} violation(s) detected"
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_repository_layout.py"
            ),
            "status":           status,
            "detail":           detail,
            "violations_count": len(violations),
            "violations":       violations,
            "generated_at":     generated_at,
        }
