"""tools/lock_yaml_generator/generate_abac_opa.py

# abac_opa.lock.yaml 生成器。
# src/tier2/abac/delegation_policy.yaml を読み込み、
# OPA ポリシーの宣言状態を lock artifact として生成する。
# ファイルが存在しない場合は 2 policy のスケルトンを生成する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# delegation_policy.yaml の想定パス
_DELEGATION_POLICY_YAML = REPO_ROOT / "src/tier2/abac/delegation_policy.yaml"

# OPA bundle ディレクトリのパス
_OPA_BUNDLE_PATH = "src/tier2/abac/opa/bundle"

# フォールバック用 2 policy スケルトン定義
_SKELETON_POLICIES: list[dict[str, Any]] = [
    # 管理者委譲ポリシーのスケルトン
    {"policy_id": "admin-delegation",       "status": "declared"},
    # テナント境界ポリシーのスケルトン
    {"policy_id": "tenant-boundary-check",  "status": "declared"},
]


class AbacOpaGenerator(BaseGenerator):
    """abac_opa.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "abac_opa.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/abac/delegation_policy.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # ファイルが存在する場合のみ読み込む
        if _DELEGATION_POLICY_YAML.exists():
            # PyYAML を使って YAML を読み込む
            import yaml  # type: ignore
            # テキストを読み込んで YAML パースする
            raw = yaml.safe_load(_DELEGATION_POLICY_YAML.read_text(encoding="utf-8"))
            # dict であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """OPA ポリシーの宣言状態を表す artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        OPA bundle ディレクトリとポリシーの物理存在を確認して status を決定する。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # OPA bundle ディレクトリとポリシーの物理存在を確認する
        opa_bundle_path = REPO_ROOT / _OPA_BUNDLE_PATH
        # bundle manifest.json の存在確認
        manifest_exists = (opa_bundle_path / "manifest.json").exists()
        # policies/ ディレクトリの存在確認
        policies_dir_exists = (opa_bundle_path / "policies").is_dir()
        # tests/ ディレクトリの存在確認
        tests_dir_exists = (opa_bundle_path / "tests").is_dir()
        # 全て存在する場合は green、そうでない場合は declared
        bundle_status = "green" if (manifest_exists and policies_dir_exists) else "declared"

        # delegation_rules から permitted roles を読み込んでポリシー一覧を構築する
        delegation_rules = inputs.get("delegation_rules", {})
        # allowed_delegation_roles キーを確認する
        allowed_roles: list[str] = delegation_rules.get("allowed_delegation_roles", [])

        # ロールが存在する場合はポリシーエントリを生成する
        if allowed_roles:
            # 委譲ポリシーを bundle_status で登録する
            policies = [
                # 管理者委譲ポリシー（delegation_policy.yaml から読み込み）
                {"policy_id": "admin-delegation",      "status": bundle_status},
                # テナント境界チェックポリシー
                {"policy_id": "tenant-boundary-check", "status": bundle_status},
            ]
        else:
            # フォールバック: bundle_status でスケルトンを使用する
            policies = [
                # 管理者委譲ポリシーのスケルトン（bundle 物理存在で status を決定する）
                {"policy_id": "admin-delegation",      "status": bundle_status},
                # テナント境界ポリシーのスケルトン（bundle 物理存在で status を決定する）
                {"policy_id": "tenant-boundary-check", "status": bundle_status},
            ]

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_abac_opa.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # OPA ポリシー一覧
            "policies": policies,
            # OPA bundle ディレクトリのパス
            "opa_bundle_path": _OPA_BUNDLE_PATH,
            # bundle 物理存在フラグ（manifest.json の存在）
            "manifest_exists": manifest_exists,
            # policies/ ディレクトリの物理存在フラグ
            "policies_dir_exists": policies_dir_exists,
            # tests/ ディレクトリの物理存在フラグ
            "tests_dir_exists": tests_dir_exists,
        }
