"""tools/lock_yaml_generator/generate_migration.py

migration.lock.yaml 生成器。
src/tier2/tenant_isolation/table_classes.yaml を読み込み、
4 table class の RLS / audit / outbox 設定を集約した lock artifact を生成する。
存在しない場合はフォールバックスケルトンを生成する（全 rls_enabled: false）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# table_classes.yaml の想定パス
_TABLE_CLASSES_YAML = REPO_ROOT / "src/tier2/tenant_isolation/table_classes.yaml"

# 4 table class のスケルトン定義
_TABLE_CLASSES: list[dict[str, Any]] = [
    {
        "class_id":        "tenant_scoped",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
    {
        "class_id":        "tenant_master",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
    {
        "class_id":        "platform_global",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
    {
        "class_id":        "pii_segregated",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
]


class MigrationGenerator(BaseGenerator):
    """migration.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "migration.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/tenant_isolation/table_classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _TABLE_CLASSES_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_TABLE_CLASSES_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """4 table class の RLS / audit / outbox 設定を集約して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # table_classes キーを読み込む
        raw_classes: list[dict[str, Any]] = inputs.get("table_classes", [])

        if len(raw_classes) >= 4:
            # 入力データから classes を正規化する
            classes = self._normalize_classes(raw_classes)
        else:
            # フォールバック: スケルトンを使用する
            classes = list(_TABLE_CLASSES)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_migration.py"
            ),
            "total_classes": len(classes),
            "generated_at":  generated_at,
            "classes":       classes,
        }

    @staticmethod
    def _normalize_classes(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """table class エントリを正規化する。boolean を文字列に変換する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            # boolean 値を 'true' / 'false' 文字列に正規化する（DSL の == 比較に合わせる）
            rls_enabled = entry.get("rls_enabled", False)
            audit_required = entry.get("audit_required", False)
            outbox_required = entry.get("outbox_required", False)
            pgaudit_required = entry.get("pgaudit_required", False)
            result.append({
                "class_id":        str(entry.get("class_id", "")),
                "rls_enabled":     "true" if rls_enabled else "false",
                "audit_required":  "true" if audit_required else "false",
                "outbox_required": "true" if outbox_required else "false",
                "pgaudit_required":"true" if pgaudit_required else "false",
                "description":     str(entry.get("description", "")),
            })
        return result
