# k1s0-proof: PROOF-test-prog-004 -> IMPL-test-0004
# k1s0-impl: IMPL-test-0004 realizes=FR-test-004
"""tools/lock_yaml_generator/generate_mutation_score.py

mutation_score.lock.yaml 生成器。
src/test/mutation/score.yaml を読み込み mutants リストを正規化する。
存在しない場合は空の mutants リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# score.yaml の想定パス
_SCORE_YAML = REPO_ROOT / "src/test/mutation/score.yaml"


class MutationScoreGenerator(BaseGenerator):
    """mutation_score.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "mutation_score.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/mutation/score.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # score.yaml が存在する場合は読み込む
        if _SCORE_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_SCORE_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """mutants リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # mutants リストを inputs から取得する (なければ空リスト)
        raw_mutants: list[dict[str, Any]] = inputs.get("mutants", [])
        # mutation_score を inputs から取得する (なければ 0.0)
        mutation_score = float(inputs.get("mutation_score", 0.0))
        # mutants リストを正規化する
        mutants = [
            {
                # mutant 識別子
                "mutant_id": str(m.get("mutant_id", "")),
                # ターゲットファイル
                "target_file": str(m.get("target_file", "")),
                # 変異の種類
                "mutation_type": str(m.get("mutation_type", "")),
                # 状態 (killed / survived)
                "status": str(m.get("status", "killed")),
            }
            for m in raw_mutants
            if isinstance(m, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_mutation_score.py"
            ),
            # mutant 総数
            "total_mutants": len(mutants),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # mutation score (0.0 - 1.0)
            "mutation_score": mutation_score,
            # mutant リスト
            "mutants": mutants,
        }
