# k1s0-proof: PROOF-client-prog-003 -> IMPL-client-0003
"""tools/lock_yaml_generator/generate_sdk_conformance.py

# sdk_conformance.lock.yaml 生成器。
# src/client/scenarios.yaml を読み込み、SDK 適合検証の
# 宣言状態を lock artifact として生成する。
# scenarios.yaml が存在しない場合は total_scenarios=0 のスケルトンを使用する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# scenarios.yaml の想定パス
_SCENARIOS_YAML = REPO_ROOT / "src/client/scenarios.yaml"


class SdkConformanceGenerator(BaseGenerator):
    """sdk_conformance.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "sdk_conformance.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/client/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/client/scenarios.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # ファイルが存在する場合のみ読み込む
        if _SCENARIOS_YAML.exists():
            # PyYAML を使って YAML を読み込む
            import yaml  # type: ignore
            # テキストを読み込んで YAML パースする
            raw = yaml.safe_load(_SCENARIOS_YAML.read_text(encoding="utf-8"))
            # dict であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """SDK 適合検証の宣言状態を表す artifact dict を返す。
        scenarios.yaml が存在しない場合は total_scenarios=0。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # scenarios キーからシナリオ一覧を取得する
        raw_scenarios: list[dict[str, Any]] = inputs.get("scenarios", [])

        # シナリオ数を算出する（存在しない場合は 0）
        total_scenarios = len(raw_scenarios)

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_sdk_conformance.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # SDK 適合検証のステータス（物理検証は Stage 5 で実施）
            "conformance_status": "declared",
            # シナリオ数（scenarios.yaml が存在しない場合は 0）
            "total_scenarios": total_scenarios,
        }
