# k1s0-proof: PROOF-formal-prog-002 -> IMPL-formal-0002
# k1s0-impl: IMPL-formal-0002 realizes=FR-formal-002
"""tools/lock_yaml_generator/generate_proof_status.py

proof_status.lock.yaml 生成器。
proof_inventory.lock.yaml を読み込み、各 obligation の cell_state を引き継いで
cells リストを構築する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT


class ProofStatusGenerator(BaseGenerator):
    """proof_status.lock.yaml 生成器。"""

    OUTPUT_NAME = "proof_status.lock.yaml"
    REQUIRED_INPUTS: list[str] = ["proof_inventory.lock.yaml"]
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """proof_inventory.lock.yaml を読み込む。"""
        return self.load_lock(lock_dir, "proof_inventory.lock.yaml")

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """proof_inventory の obligations から cells リストを構築する。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        obligations: list[dict[str, Any]] = inputs.get("obligations", [])

        # 各 obligation の cell_state を引き継ぐ
        cells: list[dict[str, Any]] = []
        for ob in obligations:
            cells.append({
                "obligation_id": str(ob.get("obligation_id", "")),
                "axis_name":     str(ob.get("axis_name", "")),
                "proof_class":   str(ob.get("proof_class", "")),
                "cell_state":    str(ob.get("cell_state", "v1_unverified_handled")),
            })

        # サマリ集計
        verified_count = sum(
            1 for c in cells if c["cell_state"] == "v1_baseline_verified"
        )
        unverified_count = len(cells) - verified_count

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_proof_status.py"
            ),
            "total_cells":      len(cells),
            "verified_count":   verified_count,
            "unverified_count": unverified_count,
            "generated_at":     generated_at,
            "cells":            cells,
        }
