# k1s0-proof: PROOF-cross_edge-prog-002 -> IMPL-cross_edge-0002
# k1s0-impl: IMPL-cross_edge-0002 realizes=FR-cross_edge-002
"""tools/lock_yaml_generator/generate_otel_semconv.py

otel_semconv.lock.yaml 生成器。
src/tier3/observability/semconv_tier3_ext.yaml を読み込み、
tier3_ext SemConv namespace の属性定義を検証して lock を生成する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# semconv 定義 YAML のパス
_SEMCONV_YAML = REPO_ROOT / "src/tier3/observability/semconv_tier3_ext.yaml"


class OtelSemconvGenerator(BaseGenerator):
    """otel_semconv.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "otel_semconv.lock.yaml"
    # 必須入力なし（semconv_tier3_ext.yaml を直接読む）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier3/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier3/observability/semconv_tier3_ext.yaml を読み込む。
        ファイルが存在しない場合は空 dict を返す。
        """
        # semconv 定義ファイルが存在するか確認する
        if _SEMCONV_YAML.exists():
            import yaml
            # YAML テキストを読み込んで dict に変換する
            raw = yaml.safe_load(_SEMCONV_YAML.read_text(encoding="utf-8"))
            # dict 型の場合そのまま返し、それ以外は空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """tier3_ext SemConv namespace の属性定義を検証して artifact dict を返す。"""
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # namespace 名を取得する
        namespace = inputs.get("namespace", "tier3_ext")
        # バージョンを取得する
        version = inputs.get("version", "unknown")
        # 属性リストを取得する
        attributes = inputs.get("attributes", [])
        # 実装根拠リストを取得する
        evidence = inputs.get("implementation_evidence", [])

        # 各根拠パスの存在を確認する
        verified_evidence = []
        for e in evidence:
            # リポジトリルートからの相対パスを絶対パスに変換する
            path = REPO_ROOT / e.get("path", "")
            # パスの存在有無を記録する
            verified_evidence.append({
                "path": e.get("path"),
                "description": e.get("description"),
                "exists": path.exists(),
            })

        # 全根拠パスが存在するか確認する
        all_evidence_exists = all(e["exists"] for e in verified_evidence)
        # 属性数を取得する
        attribute_count = len(attributes)

        # status を決定する（根拠全存在 かつ 属性数 4 以上 → green）
        status = "green" if all_evidence_exists and attribute_count >= 4 else "red"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_otel_semconv.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # tier3_ext namespace 名
            "namespace": namespace,
            # semconv バージョン
            "version": version,
            # 属性定義数
            "attribute_count": attribute_count,
            # 全根拠パスが存在するか
            "all_evidence_exists": all_evidence_exists,
            # 総合ステータス
            "status": status,
            # 根拠パスの存在確認結果
            "evidence": verified_evidence,
        }
