"""tools/lock_yaml_generator/generate_api_neutrality.py

# api_neutrality.lock.yaml 生成器。
# src/tier2/api_snapshot/ ディレクトリを確認し、
# API 中立性（4 言語対応）の宣言状態を lock artifact として生成する。
# api_snapshot/ が存在しない場合は neutrality_status='declared' を返す。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# api_snapshot ディレクトリの想定パス
_API_SNAPSHOT_DIR = REPO_ROOT / "src/tier2/api_snapshot"

# API 中立性の対象言語一覧（4 言語等価強度）
_BASELINE_LANGUAGES: list[str] = ["rust", "go", "csharp", "typescript"]


class ApiNeutralityGenerator(BaseGenerator):
    """api_neutrality.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "api_neutrality.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/api_snapshot/ ディレクトリの存在を確認する。
        存在する場合はディレクトリパスを返す。存在しない場合は空 dict を返す。
        """
        # api_snapshot ディレクトリが存在する場合は存在フラグを返す
        if _API_SNAPSHOT_DIR.exists() and _API_SNAPSHOT_DIR.is_dir():
            # ディレクトリが存在することを示すフラグを返す
            return {"api_snapshot_dir_exists": True}
        # ディレクトリが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """API 中立性の宣言状態を表す artifact dict を返す。
        api_snapshot ディレクトリが存在しない場合は neutrality_status='declared'。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # api_snapshot ディレクトリの存在を確認する
        api_snapshot_exists = inputs.get("api_snapshot_dir_exists", False)

        # ディレクトリが存在する場合は宣言済み、存在しない場合も declared とする
        # （物理 API スナップショット検証は Stage 3 で実施）
        neutrality_status = "declared"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_api_neutrality.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # API 中立性のステータス（物理検証は Stage 3 で実施）
            "neutrality_status": neutrality_status,
            # 対象言語一覧（4 言語等価強度）
            "baseline_languages": _BASELINE_LANGUAGES,
            # api_snapshot ディレクトリの存在状態
            "api_snapshot_dir_exists": api_snapshot_exists,
        }
