"""tools/lock_yaml_generator/generate_capabilities.py

capabilities.lock.yaml 生成器。
src/tier1/lock/capabilities_input.yaml を読み込む。

01_Bidi適合仕様.md §adapter↔class supports 対応 に基づき、
5 conformance_class × 8 adapter の全 40 cell を構築する。
supports 行列に含まれない cell は status: not_applicable となる（手書き禁止）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

_INPUT_NAME = "capabilities_input.yaml"

# 01_Bidi適合仕様.md §v1 conformance_class セット（5 class）
_CONFORMANCE_CLASSES: list[str] = [
    "v1_interactive",
    "v1_alert",
    "v1_event_feed",
    "v1_live_snapshot",
    "v1_bulk_upload",
]

# 01_Bidi適合仕様.md §capabilities.lock.yaml adapter 定義（8 adapter）
_ADAPTERS: list[str] = [
    "grpc_native",
    "connect_bidi",
    "web_transport",
    "sse_paired",
    "paired_post_sse",
    "long_poll",
    "webhook",
    "messaging_bridge",
]

# 01_Bidi適合仕様.md §adapter↔class supports 対応 — adapter → supports 集合
_SUPPORTS: dict[str, set[str]] = {
    "grpc_native":      {"v1_interactive", "v1_alert", "v1_event_feed", "v1_live_snapshot", "v1_bulk_upload"},
    "connect_bidi":     {"v1_interactive", "v1_alert", "v1_event_feed", "v1_live_snapshot", "v1_bulk_upload"},
    "web_transport":    {"v1_interactive", "v1_alert", "v1_event_feed", "v1_live_snapshot", "v1_bulk_upload"},
    "sse_paired":       {"v1_alert", "v1_event_feed", "v1_live_snapshot"},
    "paired_post_sse":  {"v1_interactive", "v1_alert", "v1_event_feed", "v1_live_snapshot"},
    "long_poll":        {"v1_event_feed"},
    "webhook":          {"v1_alert", "v1_event_feed", "v1_live_snapshot"},
    "messaging_bridge": {"v1_event_feed", "v1_live_snapshot", "v1_bulk_upload"},
}


class CapabilitiesGenerator(BaseGenerator):
    """capabilities.lock.yaml 生成器。"""

    OUTPUT_NAME = "capabilities.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/capabilities_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """conformance_classes × adapters の cell matrix を構築する。

        applicable cell の status は inputs の status_map から読む。
        not_applicable cell は _SUPPORTS 行列から自動決定（input 禁止）。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_cells: list[dict[str, Any]] = inputs.get("cells", [])
        status_map: dict[str, str] = {
            str(c.get("cell_id", "")): str(c.get("status", "pending"))
            for c in raw_cells
        }

        cells = self._build_cells(status_map)
        applicable = [c for c in cells if c["status"] != "not_applicable"]

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_capabilities.py"
            ),
            "conformance_classes": len(_CONFORMANCE_CLASSES),
            "adapters":            len(_ADAPTERS),
            "total_cells":         len(cells),
            "applicable_cells":    len(applicable),
            "generated_at":        generated_at,
            "cells":               cells,
        }

    @classmethod
    def _build_cells(cls, status_map: dict[str, str]) -> list[dict[str, Any]]:
        """spec の supports 行列から全 40 cell を構築する。

        applicable cell は status_map に status があればそれを使用、無ければ pending。
        not_applicable cell は _SUPPORTS から自動決定。
        """
        result: list[dict[str, Any]] = []
        for cc in _CONFORMANCE_CLASSES:
            for adapter in _ADAPTERS:
                cell_id = f"{cc}__{adapter}"
                if cc in _SUPPORTS.get(adapter, set()):
                    status = status_map.get(cell_id, "pending")
                else:
                    status = "not_applicable"
                result.append({
                    "cell_id":           cell_id,
                    "conformance_class": cc,
                    "adapter":           adapter,
                    "status":            status,
                })
        return result
