"""tools/lock_yaml_generator/generate_regression_corpus.py

regression_corpus.lock.yaml 生成器。
src/test/lock/regression_corpus_input.yaml を読み込み、entries リストを正規化する。
存在しない場合は空 entries + total_count=0 を返す。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# regression_corpus_input.yaml は lock_dir 内に置かれる
_INPUT_NAME = "regression_corpus_input.yaml"


class RegressionCorpusGenerator(BaseGenerator):
    """regression_corpus.lock.yaml 生成器。"""

    OUTPUT_NAME = "regression_corpus.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/lock/regression_corpus_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """entries リストを正規化して artifact dict を返す。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_entries: list[dict[str, Any]] = inputs.get("entries", [])
        entries = self._normalize_entries(raw_entries)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_regression_corpus.py"
            ),
            "total_count":  len(entries),
            "generated_at": generated_at,
            "entries":      entries,
        }

    @staticmethod
    def _normalize_entries(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """regression_corpus entries を正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "corpus_id":     str(entry.get("corpus_id", "")),
                "axis_name":     str(entry.get("axis_name", "")),
                "test_scenario": str(entry.get("test_scenario", "")),
                "status":        str(entry.get("status", "pending")),
            })
        return result
