# k1s0-proof: PROOF-ops-prog-002 -> IMPL-ops-0002
# k1s0-impl: IMPL-ops-0002 realizes=FR-ops-002
"""tools/lock_yaml_generator/generate_alert_catalog.py

alert_catalog.lock.yaml 生成器。
src/ops/alerts/catalog.yaml を読み込み alerts リストを正規化する。
存在しない場合は空の alerts リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# catalog.yaml の想定パス
_CATALOG_YAML = REPO_ROOT / "src/ops/alerts/catalog.yaml"


class AlertCatalogGenerator(BaseGenerator):
    """alert_catalog.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "alert_catalog.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/ops/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/ops/alerts/catalog.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # catalog.yaml が存在する場合は読み込む
        if _CATALOG_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_CATALOG_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """alerts リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # alerts リストを inputs から取得する (なければ空リスト)
        raw_alerts: list[dict[str, Any]] = inputs.get("alerts", [])
        # alerts リストを正規化する
        alerts = [
            {
                # alert 識別子
                "alert_id": str(a.get("alert_id", "")),
                # alert 名
                "alert_name": str(a.get("alert_name", "")),
                # signal_class への参照
                "signal_class": str(a.get("signal_class", "")),
                # 状態
                "status": str(a.get("status", "active")),
            }
            for a in raw_alerts
            if isinstance(a, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_alert_catalog.py"
            ),
            # alert 総数
            "total_alerts": len(alerts),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # alert リスト
            "alerts": alerts,
        }
