"""tools/lock_yaml_generator/generate_chaos_blueprints.py

chaos_blueprints.lock.yaml 生成器。
src/test/chaos/blueprints.yaml を読み込み blueprints リストを正規化する。
存在しない場合は空の blueprints リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# blueprints.yaml の想定パス
_BLUEPRINTS_YAML = REPO_ROOT / "src/test/chaos/blueprints.yaml"


class ChaosBlueprintsGenerator(BaseGenerator):
    """chaos_blueprints.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "chaos_blueprints.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/chaos/blueprints.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # blueprints.yaml が存在する場合は読み込む
        if _BLUEPRINTS_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_BLUEPRINTS_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """blueprints リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # blueprints リストを inputs から取得する (なければ空リスト)
        raw_blueprints: list[dict[str, Any]] = inputs.get("blueprints", [])
        # blueprints リストを正規化する
        blueprints = [
            {
                # blueprint 識別子
                "blueprint_id": str(b.get("blueprint_id", "")),
                # chaos エンジン
                "chaos_engine": str(b.get("chaos_engine", "litmus")),
                # 対象 verification_class
                "verification_class": str(b.get("verification_class", "")),
                # 状態
                "status": str(b.get("status", "pending")),
            }
            for b in raw_blueprints
            if isinstance(b, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_chaos_blueprints.py"
            ),
            # blueprint 総数
            "total_blueprints": len(blueprints),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # blueprint リスト
            "blueprints": blueprints,
        }
