"""tools/lock_yaml_generator/generate_sdk_inventory.py

# sdk_inventory.lock.yaml 生成器。
# src/client/classes.yaml を読み込み、SDK パッケージ一覧の
# supply chain 状態を lock artifact として生成する。
# classes.yaml が存在しない場合は 5 class のスケルトンを使用する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# classes.yaml の想定パス
_CLASSES_YAML = REPO_ROOT / "src/client/classes.yaml"

# フォールバック用 5 class スケルトン定義
_SKELETON_CLASSES: list[dict[str, Any]] = [
    # ブラウザ SPA クラスのスケルトン
    {"class_id": "browser_spa",  "display_name": "Browser SPA"},
    # Tauri デスクトップクラスのスケルトン
    {"class_id": "tauri",        "display_name": "Tauri Desktop"},
    # .NET Framework クラスのスケルトン
    {"class_id": "dotnet_fw",    "display_name": ".NET Framework"},
    # フル native クラスのスケルトン
    {"class_id": "full_native",  "display_name": "Full Native"},
    # 薄い API クライアントクラスのスケルトン
    {"class_id": "thin_api",     "display_name": "Thin API Client"},
]


class SdkInventoryGenerator(BaseGenerator):
    """sdk_inventory.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "sdk_inventory.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/client/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/client/classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # ファイルが存在する場合のみ読み込む
        if _CLASSES_YAML.exists():
            # PyYAML を使って YAML を読み込む
            import yaml  # type: ignore
            # テキストを読み込んで YAML パースする
            raw = yaml.safe_load(_CLASSES_YAML.read_text(encoding="utf-8"))
            # dict であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """SDK パッケージ一覧の supply chain 状態を表す artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # classes キーからクラス一覧を取得する（複数のキー名に対応）
        raw_classes: list[dict[str, Any]] = (
            inputs.get("classes") or
            inputs.get("sdk_classes") or
            []
        )

        # クラスが存在する場合は正規化する、存在しない場合はスケルトンを使用する
        if len(raw_classes) >= 5:
            # 入力データを正規化して supply chain 状態を初期化する
            packages = self._normalize_packages(raw_classes)
        else:
            # フォールバック: スケルトンを使用して全項目を初期値で登録する
            packages = [
                {
                    # class_id: スケルトンの class_id を使用
                    "class_id":               entry["class_id"],
                    # display_name: スケルトンの display_name を使用
                    "display_name":           entry["display_name"],
                    # cosign_signed: Stage 5 で 'true' にする予定（現時点は 'false'）
                    "cosign_signed":          "false",
                    # grype_high: Stage 5 で検証予定
                    "grype_high":             "pending",
                    # slsa_level: Stage 5 で L3 にする予定（現時点は L0）
                    "slsa_level":             "L0",
                    # build_provenance_class: Stage 5 で attested にする予定
                    "build_provenance_class": "declared",
                }
                for entry in _SKELETON_CLASSES
            ]

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_sdk_inventory.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # SDK パッケージ一覧（supply chain 状態）
            "packages": packages,
        }

    @staticmethod
    def _normalize_packages(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """SDK class エントリを正規化して supply chain 状態を初期化する。"""
        # 結果リストを初期化する
        result: list[dict[str, Any]] = []
        # 各クラスエントリを正規化する
        for entry in raw:
            # 各フィールドを初期値で設定する
            result.append({
                # class_id: 元データの class_id を使用
                "class_id":               str(entry.get("class_id", "")),
                # display_name: 元データの display_name を使用
                "display_name":           str(entry.get("display_name", "")),
                # cosign_signed: Stage 5 で 'true' にする予定（現時点は 'false'）
                "cosign_signed":          "false",
                # grype_high: Stage 5 で検証予定
                "grype_high":             "pending",
                # slsa_level: Stage 5 で L3 にする予定（現時点は L0）
                "slsa_level":             "L0",
                # build_provenance_class: Stage 5 で attested にする予定
                "build_provenance_class": "declared",
            })
        # 正規化した結果を返す
        return result
