"""tools/lock_yaml_generator/generate_csp_sri.py

csp_sri.lock.yaml 生成器。
src/tier3/lock/csp_sri_input.yaml を読み込み、
CSP unsafe-inline/eval 禁止 と SRI 必須の assertion 状態を検証する。
17_セキュリティアーキテクチャ.md §CSP + SRI 対応。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# 入力 YAML ファイル名
_INPUT_NAME = "csp_sri_input.yaml"


class CspSriGenerator(BaseGenerator):
    """csp_sri.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "csp_sri.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier3/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier3/lock/csp_sri_input.yaml を読み込む。
        ファイルが存在しない場合は空 dict を返す。
        """
        # lock_dir からの相対パスで入力 YAML を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """CSP + SRI assertion 状態を集計して artifact dict を返す。"""
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # assertion リストを取得する
        assertions = inputs.get("assertions", [])
        # assertion の総数を計算する
        total = len(assertions)
        # 合格した assertion 数（status == green）を計算する
        passed = sum(1 for a in assertions if a.get("status") == "green")
        # 失敗した assertion 数を計算する
        failed = total - passed

        # status を決定する（失敗なし かつ assertion 数 3 以上 → green）
        status = "green" if failed == 0 and total >= 3 else "red"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_csp_sri.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # assertion の総数
            "total_assertions": total,
            # 合格した assertion 数
            "passed": passed,
            # 失敗した assertion 数
            "failed": failed,
            # 総合ステータス
            "status": status,
            # 各 assertion の詳細
            "assertions": assertions,
        }
