"""tools/lock_yaml_generator/generate_clock_inventory.py

clock_inventory.lock.yaml 生成器。
src/infra/clock/inventory.yaml を読み込み nodes リストを正規化する。
存在しない場合は空の nodes リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# inventory.yaml の想定パス
_INVENTORY_YAML = REPO_ROOT / "src/infra/clock/inventory.yaml"


class ClockInventoryGenerator(BaseGenerator):
    """clock_inventory.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "clock_inventory.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/infra/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/infra/clock/inventory.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # inventory.yaml が存在する場合は読み込む
        if _INVENTORY_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_INVENTORY_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """nodes リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # nodes リストを inputs から取得する (なければ空リスト)
        raw_nodes: list[dict[str, Any]] = inputs.get("nodes", [])
        # nodes リストを正規化する
        nodes = [
            {
                # ノード識別子
                "node_id": str(n.get("node_id", "")),
                # clock_integrity_class
                "clock_integrity_class": str(n.get("clock_integrity_class", "")),
                # sync_protocol
                "sync_protocol": str(n.get("sync_protocol", "")),
            }
            for n in raw_nodes
            if isinstance(n, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_clock_inventory.py"
            ),
            # node 総数
            "total_nodes": len(nodes),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # node リスト
            "nodes": nodes,
        }
