"""tools/lock_yaml_generator/generate_flaky_quarantine.py

flaky_quarantine.lock.yaml 生成器。
src/test/flaky/quarantine.yaml を読み込み quarantined リストを正規化する。
存在しない場合は空の quarantined リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# quarantine.yaml の想定パス
_QUARANTINE_YAML = REPO_ROOT / "src/test/flaky/quarantine.yaml"


class FlakyQuarantineGenerator(BaseGenerator):
    """flaky_quarantine.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "flaky_quarantine.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/flaky/quarantine.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # quarantine.yaml が存在する場合は読み込む
        if _QUARANTINE_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_QUARANTINE_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """quarantined リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # quarantined リストを inputs から取得する (なければ空リスト)
        raw_quarantined: list[dict[str, Any]] = inputs.get("quarantined", [])
        # quarantined リストを正規化する
        quarantined = [
            {
                # テスト識別子
                "test_id": str(q.get("test_id", "")),
                # quarantine 理由
                "reason": str(q.get("reason", "")),
                # quarantine 開始日
                "quarantined_at": str(q.get("quarantined_at", "")),
                # ticket 参照
                "ticket": str(q.get("ticket", "")),
            }
            for q in raw_quarantined
            if isinstance(q, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_flaky_quarantine.py"
            ),
            # quarantine 総数
            "total_quarantined": len(quarantined),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # quarantined リスト
            "quarantined": quarantined,
        }
