"""tools/lock_yaml_generator/generate_migration.py

migration.lock.yaml 生成器。
src/tier2/tenant_isolation/table_classes.yaml を読み込み、
4 table class の RLS / audit / outbox 設定を集約した lock artifact を生成する。
存在しない場合はフォールバックスケルトンを生成する（全 rls_enabled: false）。

また src/tier2/migrations/ 配下の各 .sql ファイルのヘッダコメントを解析し、
migration ごとのメタデータを migrations: 配列として出力する。
"""

from __future__ import annotations

import datetime
import re
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# table_classes.yaml の想定パス
_TABLE_CLASSES_YAML = REPO_ROOT / "src/tier2/tenant_isolation/table_classes.yaml"

# migrations ディレクトリのパス（.sql ファイルを格納する）
_MIGRATIONS_DIR = REPO_ROOT / "src/tier2/migrations"

# SQL ヘッダコメントから抽出するフィールド名と正規表現パターン
_SQL_HEADER_PATTERNS: dict[str, re.Pattern[str]] = {
    "migration_id": re.compile(r"^--\s*migration_id:\s*(.+)$", re.MULTILINE),
    "description":  re.compile(r"^--\s*description:\s*(.+)$", re.MULTILINE),
    "safety_level": re.compile(r"^--\s*safety_level:\s*(.+)$", re.MULTILINE),
    "table_class":  re.compile(r"^--\s*table_class:\s*(.+)$", re.MULTILINE),
    "applied_at":   re.compile(r"^--\s*applied_at:\s*(.+)$", re.MULTILINE),
}

# 4 table class のスケルトン定義
_TABLE_CLASSES: list[dict[str, Any]] = [
    {
        "class_id":        "tenant_scoped",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
    {
        "class_id":        "tenant_master",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
    {
        "class_id":        "platform_global",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
    {
        "class_id":        "pii_segregated",
        "rls_enabled":     "false",
        "audit_required":  "false",
        "outbox_required": "false",
    },
]


class MigrationGenerator(BaseGenerator):
    """migration.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "migration.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/tenant_isolation/table_classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _TABLE_CLASSES_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_TABLE_CLASSES_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """4 table class の RLS / audit / outbox 設定を集約して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        また src/tier2/migrations/ の各 .sql ファイルヘッダを解析して migrations: 配列を追加する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # table_classes キーを読み込む
        raw_classes: list[dict[str, Any]] = inputs.get("table_classes", [])

        if len(raw_classes) >= 4:
            # 入力データから classes を正規化する
            classes = self._normalize_classes(raw_classes)
        else:
            # フォールバック: スケルトンを使用する
            classes = list(_TABLE_CLASSES)

        # src/tier2/migrations/ の .sql ファイルヘッダを解析する
        migrations = self._parse_sql_migrations()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_migration.py"
            ),
            "total_classes":    len(classes),
            "total_migrations": len(migrations),
            "generated_at":     generated_at,
            "classes":          classes,
            "migrations":       migrations,
        }

    @staticmethod
    def _parse_sql_migrations() -> list[dict[str, Any]]:
        """src/tier2/migrations/ 配下の .sql ファイルを昇順に走査し、
        各ファイルのヘッダコメントから migration メタデータを抽出して返す。
        ヘッダが存在しないフィールドはデフォルト値を使用する。
        """
        result: list[dict[str, Any]] = []
        # .sql ファイルをファイル名の昇順でソートして処理する
        if not _MIGRATIONS_DIR.exists():
            return result
        sql_files = sorted(_MIGRATIONS_DIR.glob("*.sql"))
        for sql_path in sql_files:
            # ファイルの内容を読み込む（ヘッダは先頭 30 行以内に存在する前提）
            content = sql_path.read_text(encoding="utf-8")
            entry: dict[str, Any] = {"file": sql_path.name}
            # 各ヘッダフィールドを正規表現で抽出する
            for field, pattern in _SQL_HEADER_PATTERNS.items():
                match = pattern.search(content)
                if match:
                    # コメント末尾の空白を取り除いて格納する
                    entry[field] = match.group(1).strip()
                else:
                    # フィールドが存在しない場合のデフォルト値を設定する
                    if field == "migration_id":
                        # ファイル名から拡張子を除いた値をフォールバックとして使用する
                        entry[field] = sql_path.stem
                    elif field == "applied_at":
                        entry[field] = "2026-05-17T00:00:00Z"
                    else:
                        entry[field] = ""
            result.append(entry)
        return result

    @staticmethod
    def _normalize_classes(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """table class エントリを正規化する。boolean を文字列に変換する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            # boolean 値を 'true' / 'false' 文字列に正規化する（DSL の == 比較に合わせる）
            rls_enabled = entry.get("rls_enabled", False)
            audit_required = entry.get("audit_required", False)
            outbox_required = entry.get("outbox_required", False)
            pgaudit_required = entry.get("pgaudit_required", False)
            # tenant_id_required: テナント ID 列の要否（spec 10 §purpose_check の前提条件）
            tenant_id_required = entry.get("tenant_id_required", False)
            # allowed_purpose: この class のテーブルが許可されるアクセス目的の一覧
            allowed_purpose: list[str] = list(entry.get("allowed_purpose", []))
            # purpose_check: pii_segregated のみ true（RLS が app.purpose の値で挙動を変える）
            purpose_check = entry.get("purpose_check", False)
            result.append({
                "class_id":           str(entry.get("class_id", "")),
                "rls_enabled":        "true" if rls_enabled else "false",
                "audit_required":     "true" if audit_required else "false",
                "outbox_required":    "true" if outbox_required else "false",
                "pgaudit_required":   "true" if pgaudit_required else "false",
                "tenant_id_required": bool(tenant_id_required),
                "allowed_purpose":    allowed_purpose,
                "purpose_check":      bool(purpose_check),
                "description":        str(entry.get("description", "")),
            })
        return result
