# k1s0-proof: PROOF-meta-prog-003 -> IMPL-meta-0003
# k1s0-impl: IMPL-meta-0003 realizes=FR-meta-003
"""tools/lock_yaml_generator/generate_ownership_table.py

ownership_table.lock.yaml 生成器。
src/_meta/ownership/ownership.yaml から services リストを読み込み正規化する。
存在しない場合は 19 軸に対応する skeleton (全 owner: unassigned) を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# ownership.yaml の想定パス
_OWNERSHIP_YAML = REPO_ROOT / "src/_meta/ownership/ownership.yaml"

# 19 軸名（スケルトン生成用）
_AXIS_NAMES = [
    "tier1", "tier2", "tier3", "infra", "data",
    "security", "ops", "client", "test", "formal",
    "cross_http2", "cross_kek", "cross_schema", "cross_fsm",
    "cross_slo", "cross_bff", "cross_pii", "cross_edge", "meta",
]

# 4 オーナー軸
_OWNER_AXES = ["dev_owner", "ops_owner", "security_owner", "data_owner"]


class OwnershipTableGenerator(BaseGenerator):
    """ownership_table.lock.yaml 生成器。"""

    OUTPUT_NAME = "ownership_table.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/_meta/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/_meta/ownership/ownership.yaml を読み込む。存在しない場合は空 dict。"""
        if _OWNERSHIP_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_OWNERSHIP_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """services リストを正規化して artifact dict を返す。
        inputs が空の場合は 19 軸スケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_services: list[dict[str, Any]] = inputs.get("services", [])

        if raw_services:
            services = self._normalize_services(raw_services)
        else:
            # 19 軸スケルトン: 全 owner を unassigned に設定
            services = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_ownership_table.py"
            ),
            "services_count": len(services),
            "generated_at":   generated_at,
            "services":       services,
        }

    @staticmethod
    def _normalize_services(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """services エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            normalized: dict[str, Any] = {
                "service_id": str(entry.get("service_id", "")),
            }
            # 4 オーナー軸を補完
            for axis in _OWNER_AXES:
                normalized[axis] = str(entry.get(axis, "unassigned"))
            result.append(normalized)
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """19 軸に対応する unassigned スケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for name in _AXIS_NAMES:
            entry: dict[str, Any] = {"service_id": name}
            for axis in _OWNER_AXES:
                entry[axis] = "unassigned"
            result.append(entry)
        return result
