# k1s0-proof: PROOF-security-prog-002 -> IMPL-security-0002
# k1s0-impl: IMPL-security-0002 realizes=FR-security-002
"""tools/lock_yaml_generator/generate_provenance_attestation.py

provenance_attestation.lock.yaml 生成器。
src/security/provenance/attestations.yaml を読み込み attestations リストを正規化する。
存在しない場合は空の attestations リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# attestations.yaml の想定パス
_ATTESTATIONS_YAML = REPO_ROOT / "src/security/provenance/attestations.yaml"


class ProvenanceAttestationGenerator(BaseGenerator):
    """provenance_attestation.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "provenance_attestation.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/security/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/security/provenance/attestations.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # attestations.yaml が存在する場合は読み込む
        if _ATTESTATIONS_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_ATTESTATIONS_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """attestations リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # attestations リストを inputs から取得する (なければ空リスト)
        raw_attestations: list[dict[str, Any]] = inputs.get("attestations", [])
        # attestations リストを正規化する
        attestations = [
            {
                # attestation 識別子
                "attestation_id": str(a.get("attestation_id", "")),
                # artifact 識別子
                "artifact_id": str(a.get("artifact_id", "")),
                # predicate タイプ
                "predicate_type": str(a.get("predicate_type", "")),
                # 状態
                "status": str(a.get("status", "verified")),
            }
            for a in raw_attestations
            if isinstance(a, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_provenance_attestation.py"
            ),
            # attestation 総数
            "total_attestations": len(attestations),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # attestation リスト
            "attestations": attestations,
        }
