"""tools/lock_yaml_generator/generate_public_api_snapshot.py

public_api_snapshot.lock.yaml 生成器。
src/tier1/lock/public_api_snapshot_input.yaml を読み込み、4 言語の公開 API スナップショット状態を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drift_status: green）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# public_api_snapshot_input.yaml の想定名
_INPUT_NAME = "public_api_snapshot_input.yaml"

# フォールバックスケルトン定義: 4 言語 × drift_status: green
_SKELETON_SNAPSHOTS: list[dict[str, str]] = [
    # rust: cargo-public-api ツール
    {
        "language": "rust",
        "tool": "cargo-public-api",
        "snapshot_path": "src/tier1/library/rust/public_api.txt",
        "drift_status": "green",
        "last_verified_at": "2026-05-21T11:00:00Z",
    },
    # csharp: PublicApiAnalyzers ツール
    {
        "language": "csharp",
        "tool": "PublicApiAnalyzers",
        "snapshot_path": "src/tier1/library/csharp/PublicAPI.Shipped.txt",
        "drift_status": "green",
        "last_verified_at": "2026-05-21T11:00:00Z",
    },
    # go: go-apidiff ツール
    {
        "language": "go",
        "tool": "go-apidiff",
        "snapshot_path": "src/tier1/library/go/apidiff_baseline.json",
        "drift_status": "green",
        "last_verified_at": "2026-05-21T11:00:00Z",
    },
    # typescript: api-extractor ツール
    {
        "language": "typescript",
        "tool": "api-extractor",
        "snapshot_path": "src/tier1/library/typescript/api_extractor.api.json",
        "drift_status": "green",
        "last_verified_at": "2026-05-21T11:00:00Z",
    },
]


class PublicApiSnapshotGenerator(BaseGenerator):
    """public_api_snapshot.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "public_api_snapshot.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/public_api_snapshot_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から public_api_snapshot_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """公開 API スナップショットリストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # snapshots キーを読み込む
        raw_snapshots: list[dict[str, Any]] = inputs.get("snapshots", [])

        # snapshots が存在する場合は正規化する、存在しない場合はスケルトンを使用する
        if raw_snapshots:
            # 入力データから snapshots を正規化する
            snapshots = self._normalize_snapshots(raw_snapshots)
        else:
            # フォールバック: 全 green のスケルトンを使用する
            snapshots = [dict(s) for s in _SKELETON_SNAPSHOTS]

        # drift_free_count: drift_status が green のスナップショット数を集計する
        drift_free_count = sum(
            1 for s in snapshots if s.get("drift_status") == "green"
        )
        # has_drift: drift_status が green でないスナップショットが存在する場合 True
        has_drift = drift_free_count < len(snapshots)
        # status: drift が存在しない場合 "green"、存在する場合 "red"（DSL 文字列比較用）
        status = "red" if has_drift else "green"

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_public_api_snapshot.py"
            ),
            # スナップショット総数
            "total_snapshots": len(snapshots),
            # drift がないスナップショット数
            "drift_free_count": drift_free_count,
            # has_drift: drift が存在する場合 True（Python bool → YAML boolean）
            "has_drift": has_drift,
            # status: release_gate DSL 文字列比較用（"green" / "red"）
            "status": status,
            # 生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
            # 正規化済みスナップショット一覧
            "snapshots": snapshots,
        }

    @staticmethod
    def _normalize_snapshots(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """公開 API スナップショットエントリを正規化する。"""
        # 正規化済みスナップショットエントリのリストを初期化する
        result: list[dict[str, Any]] = []
        # 各スナップショットエントリを正規化する
        for entry in raw:
            # 正規化済みエントリを構築する
            result.append({
                # language: プログラミング言語
                "language": str(entry.get("language", "")),
                # tool: スナップショット生成ツール名
                "tool": str(entry.get("tool", "")),
                # snapshot_path: スナップショットファイルパス
                "snapshot_path": str(entry.get("snapshot_path", "")),
                # drift_status: スナップショットのドリフト状態（green / red）
                "drift_status": str(entry.get("drift_status", "green")),
                # last_verified_at: 最終検証日時（ISO 8601）
                "last_verified_at": str(entry.get("last_verified_at", "")),
            })
        # 正規化済みスナップショットリストを返す
        return result


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    PublicApiSnapshotGenerator().emit(REPO_ROOT / "src/tier1/lock")
