"""tools/lock_yaml_generator/generate_scheduler_argo.py

# scheduler_argo.lock.yaml 生成器。
# src/tier2/scheduler/argo/ ディレクトリの *.yaml ファイル一覧を読み込み、
# Argo Workflow の宣言状態を lock artifact として生成する。
# ファイルが 0 本の場合は 2 workflow のスケルトンを生成する（status: 'declared'）。
# ファイルが存在する場合は各 workflow を green として登録する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# Argo ワークフロー YAML ディレクトリの想定パス
_ARGO_DIR = REPO_ROOT / "src/tier2/scheduler/argo"

# フォールバック用 2 workflow スケルトン定義
_SKELETON_WORKFLOWS: list[dict[str, Any]] = [
    # バッチワークフローのスケルトン
    {"name": "batch-workflow",   "status": "declared"},
    # クリーンアップワークフローのスケルトン
    {"name": "cleanup-workflow", "status": "declared"},
]


class SchedulerArgoGenerator(BaseGenerator):
    """scheduler_argo.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "scheduler_argo.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/scheduler/argo/ ディレクトリの *.yaml ファイル一覧を読み込む。
        ディレクトリが存在しない場合は空 dict を返す。
        """
        # ディレクトリが存在する場合のみスキャンする
        if _ARGO_DIR.exists() and _ARGO_DIR.is_dir():
            # *.yaml ファイルの一覧を取得してソートする
            yaml_files = sorted(_ARGO_DIR.glob("*.yaml"))
            # ファイル名のリストを返す
            return {"yaml_files": [f.name for f in yaml_files]}
        # ディレクトリが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Argo Workflow の宣言状態を表す artifact dict を返す。
        ファイルが存在する場合は green、存在しない場合は declared を使用する。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # yaml_files キーからファイル一覧を取得する
        yaml_files: list[str] = inputs.get("yaml_files", [])

        # ファイルが存在する場合は green として登録する
        if yaml_files:
            # 各ファイルを workflow エントリとして green で登録する
            workflows = [
                {
                    # ファイル名から .yaml 拡張子を除去してワークフロー名とする
                    "name":   f.replace(".yaml", ""),
                    # ファイルが存在するため green とする
                    "status": "green",
                }
                for f in yaml_files
            ]
        else:
            # フォールバック: スケルトンを使用する（ファイル 0 本の場合）
            workflows = list(_SKELETON_WORKFLOWS)

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_scheduler_argo.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # ワークフロー一覧
            "workflows": workflows,
        }
