"""tools/lock_yaml_generator/generate_clock_drill.py

clock_drill.lock.yaml 生成器。
src/infra/clock/drills.yaml を読み込み drills リストを正規化する。
存在しない場合は空の drills リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# drills.yaml の想定パス
_DRILLS_YAML = REPO_ROOT / "src/infra/clock/drills.yaml"


class ClockDrillGenerator(BaseGenerator):
    """clock_drill.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "clock_drill.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/infra/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/infra/clock/drills.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # drills.yaml が存在する場合は読み込む
        if _DRILLS_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_DRILLS_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """drills リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # drills リストを inputs から取得する (なければ空リスト)
        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])
        # drills リストを正規化する
        drills = [
            {
                # drill 識別子
                "drill_id": str(d.get("drill_id", "")),
                # drill クラス
                "drill_class": str(d.get("drill_class", "skew_injection")),
                # drill 状態
                "drill_state": str(d.get("drill_state", "pending")),
            }
            for d in raw_drills
            if isinstance(d, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_clock_drill.py"
            ),
            # drill 総数
            "total_drills": len(drills),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # drill リスト
            "drills": drills,
        }
