"""tools/lock_yaml_generator/generate_kani_cbmc_pin.py

kani_cbmc_pin.lock.yaml 生成器。
src/formal/pins/kani_cbmc.yaml を読み込み pins リストを正規化する。
存在しない場合は空の pins リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# kani_cbmc.yaml の想定パス
_KANI_YAML = REPO_ROOT / "src/formal/pins/kani_cbmc.yaml"


class KaniCbmcPinGenerator(BaseGenerator):
    """kani_cbmc_pin.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "kani_cbmc_pin.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/formal/pins/kani_cbmc.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # kani_cbmc.yaml が存在する場合は読み込む
        if _KANI_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_KANI_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """pins リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # pins リストを inputs から取得する (なければ空リスト)
        raw_pins: list[dict[str, Any]] = inputs.get("pins", [])
        # pins リストを正規化する
        pins = [
            {
                # ツール名 (kani / cbmc)
                "tool": str(p.get("tool", "")),
                # ピンされたバージョン
                "version": str(p.get("version", "")),
                # コミットハッシュ
                "commit_hash": str(p.get("commit_hash", "")),
                # 状態
                "status": str(p.get("status", "pinned")),
            }
            for p in raw_pins
            if isinstance(p, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_kani_cbmc_pin.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # pin リスト
            "pins": pins,
        }
