"""tools/lock_yaml_generator/generate_api_snapshot.py

api_snapshot.lock.yaml 生成器。
src/tier1/lock/api_snapshot_input.yaml を読み込み、proto 2 層（public/admin）の API スナップショット状態を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 buf_breaking_status: no_breaking_changes）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# api_snapshot_input.yaml の想定名
_INPUT_NAME = "api_snapshot_input.yaml"

# フォールバックスケルトン定義: 2 層（public/admin）× no_breaking_changes
_SKELETON_LAYERS: list[dict[str, str]] = [
    # public: k1s0.tier1 パッケージプレフィックス
    {
        "proto_layer": "public",
        "package_prefix": "k1s0.tier1",
        "buf_breaking_status": "no_breaking_changes",
        "last_diff_at": "2026-05-21T11:00:00Z",
    },
    # admin: k1s0.tier1.admin パッケージプレフィックス
    {
        "proto_layer": "admin",
        "package_prefix": "k1s0.tier1.admin",
        "buf_breaking_status": "no_breaking_changes",
        "last_diff_at": "2026-05-21T11:00:00Z",
    },
]


class ApiSnapshotGenerator(BaseGenerator):
    """api_snapshot.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "api_snapshot.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/api_snapshot_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から api_snapshot_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """proto API スナップショット層リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # layers キーを読み込む
        raw_layers: list[dict[str, Any]] = inputs.get("layers", [])

        # layers が存在する場合は正規化する、存在しない場合はスケルトンを使用する
        if raw_layers:
            # 入力データから layers を正規化する
            layers = self._normalize_layers(raw_layers)
        else:
            # フォールバック: 全 no_breaking_changes のスケルトンを使用する
            layers = [dict(s) for s in _SKELETON_LAYERS]

        # breaking_change_count: buf_breaking_status が no_breaking_changes でない層の数
        breaking_change_count = sum(
            1 for layer in layers if layer.get("buf_breaking_status") != "no_breaking_changes"
        )
        # status: breaking_change_count が 0 なら green、それ以外は red
        status = "green" if breaking_change_count == 0 else "red"

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_api_snapshot.py"
            ),
            # 層の総数
            "total_layers": len(layers),
            # breaking change が検出された層の数
            "breaking_change_count": breaking_change_count,
            # 全体ステータス（green / red）
            "status": status,
            # 生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
            # 正規化済み層一覧
            "layers": layers,
        }

    @staticmethod
    def _normalize_layers(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """proto API スナップショット層エントリを正規化する。"""
        # 正規化済み層エントリのリストを初期化する
        result: list[dict[str, Any]] = []
        # 各層エントリを正規化する
        for entry in raw:
            # 正規化済みエントリを構築する
            result.append({
                # proto_layer: proto 層識別子（public / admin）
                "proto_layer": str(entry.get("proto_layer", "")),
                # package_prefix: proto パッケージプレフィックス
                "package_prefix": str(entry.get("package_prefix", "")),
                # buf_breaking_status: buf breaking check の結果
                "buf_breaking_status": str(entry.get("buf_breaking_status", "no_breaking_changes")),
                # last_diff_at: 最終 diff 実行日時（ISO 8601）
                "last_diff_at": str(entry.get("last_diff_at", "")),
            })
        # 正規化済み層リストを返す
        return result


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    ApiSnapshotGenerator().emit(REPO_ROOT / "src/tier1/lock")
