"""tools/lock_yaml_generator/generate_oss_inventory.py

oss_inventory.lock.yaml 生成器。
src/tier1/lock/oss_inventory_input.yaml を読み込み、OSS lifecycle drill 結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# oss_inventory_input.yaml の想定名
_INPUT_NAME = "oss_inventory_input.yaml"

# 主要 OSS 依存関係のスケルトン定義
_OSS_DEPS: list[dict[str, str]] = [
    # axum: Rust Web フレームワーク
    {"oss_id": "axum", "current_version": "0.8", "ecosystem": "rust"},
    # tokio: 非同期ランタイム
    {"oss_id": "tokio", "current_version": "1", "ecosystem": "rust"},
    # tower: ミドルウェアライブラリ
    {"oss_id": "tower", "current_version": "0.5", "ecosystem": "rust"},
    # controller-runtime: k8s コントローラライブラリ
    {"oss_id": "controller-runtime", "current_version": "0.20.0", "ecosystem": "go"},
]


class OssInventoryGenerator(BaseGenerator):
    """oss_inventory.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "oss_inventory.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/oss_inventory_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """OSS drills リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # drills キーを読み込む
        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        if raw_drills:
            # 入力データから drills を正規化する
            drills = self._normalize_drills(raw_drills)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            drills = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_oss_inventory.py"
            ),
            "total_drills": len(drills),
            "generated_at": generated_at,
            "drills":       drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """OSS drill エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "drill_id":      str(entry.get("drill_id", "")),
                "oss_id":        str(entry.get("oss_id", "")),
                "ecosystem":     str(entry.get("ecosystem", "")),
                "drill_state":   str(entry.get("drill_state", "pending")),
                "notes":         str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """OSS 依存関係ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for dep in _OSS_DEPS:
            oss_id = dep["oss_id"]
            result.append({
                "drill_id":    f"oss_drill__{oss_id}",
                "oss_id":      oss_id,
                "ecosystem":   dep["ecosystem"],
                "drill_state": "pending",
                "notes":       "",
            })
        return result
