"""tools/lock_yaml_generator/generate_clock_integrity.py

clock_causality_proof.lock.yaml 生成器。
src/infra/clock_integrity/classes.yaml を読み込み、5 clock_integrity_class を返す。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# classes.yaml の想定パス
_CLASSES_YAML = REPO_ROOT / "src/infra/clock_integrity/classes.yaml"

# 5 clock_integrity_class 定義
_CLOCK_CLASSES: list[dict[str, Any]] = [
    {
        "class_id":    "v1_intra_rack_ptp",
        "class_name":  "v1_intra_rack_ptp",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_dc_chrony_stratum1",
        "class_name":  "v1_dc_chrony_stratum1",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_multi_region_ntp",
        "class_name":  "v1_multi_region_ntp",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_legacy_skew_tolerant",
        "class_name":  "v1_legacy_skew_tolerant",
        "drill_state": "pending",
    },
    {
        "class_id":    "v1_air_gapped_legacy",
        "class_name":  "v1_air_gapped_legacy",
        "drill_state": "pending",
    },
]


class ClockIntegrityGenerator(BaseGenerator):
    """clock_causality_proof.lock.yaml 生成器。"""

    OUTPUT_NAME = "clock_causality_proof.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/infra/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/infra/clock_integrity/classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _CLASSES_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_CLASSES_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 clock_integrity_class を正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_classes: list[dict[str, Any]] = inputs.get("classes", [])

        if len(raw_classes) >= 5:
            classes = self._normalize_classes(raw_classes)
        else:
            classes = list(_CLOCK_CLASSES)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_clock_integrity.py"
            ),
            "total_classes": len(classes),
            "generated_at":  generated_at,
            "classes":       classes,
        }

    @staticmethod
    def _normalize_classes(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """clock_integrity_class エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "class_id":    str(entry.get("class_id", "")),
                "class_name":  str(entry.get("class_name", "")),
                "drill_state": str(entry.get("drill_state", "pending")),
            })
        return result
