"""tools/lock_yaml_generator/generate_idp_capabilities.py

idp_capabilities.lock.yaml 生成器。
src/tier1/lock/idp_capabilities_input.yaml を読み込み、認証 IdP capability 一覧を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 status: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# idp_capabilities_input.yaml の想定名
_INPUT_NAME = "idp_capabilities_input.yaml"

# IdP capability のスケルトン定義
_IDP_CAPABILITIES: list[dict[str, str]] = [
    # Keycloak OIDC プロバイダー（メイン IdP）
    {"idp_id": "keycloak_oidc", "auth_protocol": "oidc"},
    # DPoP（Demonstrating Proof of Possession）トークン検証
    {"idp_id": "dpop_token", "auth_protocol": "dpop"},
    # mTLS クライアント証明書認証
    {"idp_id": "mtls_client_cert", "auth_protocol": "mtls"},
    # JWT ベアラートークン検証（Envoy jwt_authn フィルター経由）
    {"idp_id": "jwt_bearer", "auth_protocol": "jwt"},
]


class IdpCapabilitiesGenerator(BaseGenerator):
    """idp_capabilities.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "idp_capabilities.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/idp_capabilities_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """IdP capabilities リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # capabilities キーを読み込む
        raw_caps: list[dict[str, Any]] = inputs.get("capabilities", [])

        if raw_caps:
            # 入力データから capabilities を正規化する
            capabilities = self._normalize_caps(raw_caps)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            capabilities = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_idp_capabilities.py"
            ),
            "total_capabilities": len(capabilities),
            "generated_at":       generated_at,
            "capabilities":       capabilities,
        }

    @staticmethod
    def _normalize_caps(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """IdP capability エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "idp_id":        str(entry.get("idp_id", "")),
                "auth_protocol": str(entry.get("auth_protocol", "")),
                "status":        str(entry.get("status", "pending")),
                "notes":         str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """IdP ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for cap in _IDP_CAPABILITIES:
            result.append({
                "idp_id":        cap["idp_id"],
                "auth_protocol": cap["auth_protocol"],
                "status":        "pending",
                "notes":         "",
            })
        return result
