# k1s0-proof: PROOF-formal-prog-007 -> IMPL-formal-0007
# k1s0-impl: IMPL-formal-0007 realizes=FR-formal-007
"""tools/lock_yaml_generator/generate_assumption.py

assumption.lock.yaml 生成器。
src/formal/lock/assumption_input.yaml から entries を読み込み正規化する。
存在しない場合は空 entries を返す。cap_slot_max=20。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# assumption_input.yaml の想定パス（lock_dir 内に置かれるため load_lock を使用）
_ASSUMPTION_INPUT_NAME = "assumption_input.yaml"
_CAP_SLOT_MAX = 20


class AssumptionGenerator(BaseGenerator):
    """assumption.lock.yaml 生成器。"""

    OUTPUT_NAME = "assumption.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/formal/lock/assumption_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _ASSUMPTION_INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """entries リスト（最大 20）を正規化して artifact dict を返す。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_entries: list[dict[str, Any]] = inputs.get("entries", [])
        entries = self._normalize_entries(raw_entries)

        # cap_slot_max=20 を超えていれば先頭 20 件に切り詰め
        if len(entries) > _CAP_SLOT_MAX:
            entries = entries[:_CAP_SLOT_MAX]

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_assumption.py"
            ),
            "cap_slot_max": _CAP_SLOT_MAX,
            "total_count":  len(entries),
            "generated_at": generated_at,
            "entries":      entries,
        }

    @staticmethod
    def _normalize_entries(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """entries エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "assumption_id": str(entry.get("assumption_id", "")),
                "description":   str(entry.get("description", "")),
                "status":        str(entry.get("status", "open")),
                "axis_name":     str(entry.get("axis_name", "")),
            })
        return result
