"""tools/lock_yaml_generator/generate_registry_pin.py

# registry_pin.lock.yaml 生成器。
# 複数言語の registry pin 設定ファイルを確認し、
# 各言語の pin 状態を lock artifact として生成する。
# config ファイルが存在する言語は 'pinned'、存在しない言語は 'declared' とする。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# 言語別の registry pin 設定ファイルパスの定義
# 各言語の config ファイルが存在するかどうかで pin 状態を判定する
# tier2 言語別サブディレクトリの設定ファイルを確認する
_LANG_CONFIG_PATHS: list[dict[str, Any]] = [
    # Rust: src/tier2/rust/.cargo/config.toml（内部 registry mirror 設定）
    {"lang": "rust",       "config_path": REPO_ROOT / "src/tier2/rust/.cargo/config.toml"},
    # Go: src/tier2/go/.golangci.yml（depguard 依存方向強制設定）
    {"lang": "go",         "config_path": REPO_ROOT / "src/tier2/go/.golangci.yml"},
    # C#: src/tier2/csharp/nuget.config（内部 NuGet フィード設定）
    {"lang": "csharp",     "config_path": REPO_ROOT / "src/tier2/csharp/nuget.config"},
    # TypeScript: src/tier2/.npmrc（内部 npm registry 設定）
    {"lang": "typescript", "config_path": REPO_ROOT / "src/tier2/.npmrc"},
]


class RegistryPinGenerator(BaseGenerator):
    """registry_pin.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "registry_pin.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """各言語の registry pin 設定ファイルの存在を確認する。
        存在する言語は 'pinned'、存在しない言語は 'declared' として返す。
        """
        # 言語別の pin 状態を収集する
        lang_statuses: list[dict[str, Any]] = []
        # 各言語の設定ファイルの存在を確認する
        for lang_config in _LANG_CONFIG_PATHS:
            # 言語名を取得する
            lang = lang_config["lang"]
            # 設定ファイルパスを取得する
            config_path: Path = lang_config["config_path"]
            # 設定ファイルが存在するかどうかで pin 状態を判定する
            pin_status = "pinned" if config_path.exists() else "declared"
            # 言語別の pin 状態を追加する
            lang_statuses.append({
                "lang":       lang,
                "pin_status": pin_status,
            })
        # 言語別の pin 状態を返す
        return {"languages": lang_statuses}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """各言語の registry pin 状態を表す artifact dict を返す。
        config ファイルが存在する言語は 'pinned'、存在しない言語は 'declared'。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # 言語別の pin 状態を取得する
        languages: list[dict[str, Any]] = inputs.get("languages", [])

        # 言語リストが空の場合はスケルトンを使用する
        if not languages:
            # フォールバック: 全言語を declared として登録する
            languages = [
                {"lang": "rust",       "pin_status": "declared"},
                {"lang": "go",         "pin_status": "declared"},
                {"lang": "csharp",     "pin_status": "declared"},
                {"lang": "typescript", "pin_status": "declared"},
            ]

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_registry_pin.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # 言語別の registry pin 状態一覧
            "languages": languages,
        }
