"""tools/lock_yaml_generator/generate_instruments.py

instruments.lock.yaml 生成器。
src/tier1/lock/instruments_input.yaml を読み込み、SLO drill 結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 drill_state: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# SLO instruments_input.yaml の想定パス
_INPUT_NAME = "instruments_input.yaml"

# 07_SLO適合仕様.md §v1 slo_class セット（6 class）
_SLO_CLASSES: list[str] = [
    # HTTP/gRPC API 可用性（SLO 99.9%、monthly budget 43.2 分）
    "v1_request_availability",
    # request 経路 p99 latency（class 別 threshold_ms、30d window）
    "v1_request_latency_p99",
    # cross-region write p99 latency（典型 1500ms、v1_cross_region_replicated 経路必須）
    "v1_request_latency_p99_cross_region",
    # server-driven event 配信 freshness（p95 ≤ target、7d window）
    "v1_event_freshness",
    # Temporal Workflow / Saga 完了率（99.5%、30d window）
    "v1_workflow_completion",
    # tenant data 永続性（11 nines + freeze_on_any_loss、365d window）
    "v1_data_durability",
]


class InstrumentsGenerator(BaseGenerator):
    """instruments.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "instruments.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/instruments_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """SLO drills リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # drills キーを読み込む
        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        if raw_drills:
            # 入力データから drills を正規化する
            drills = self._normalize_drills(raw_drills)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            drills = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_instruments.py"
            ),
            "total_drills": len(drills),
            "generated_at": generated_at,
            "drills":       drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """SLO drill エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "drill_id":   str(entry.get("drill_id", "")),
                "slo_class":  str(entry.get("slo_class", "")),
                "drill_state": str(entry.get("drill_state", "pending")),
                "notes":      str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """SLO class ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for slo_class in _SLO_CLASSES:
            result.append({
                "drill_id":   f"slo_drill__{slo_class}",
                "slo_class":  slo_class,
                "drill_state": "pending",
                "notes":      "",
            })
        return result
