"""tools/lock_yaml_generator/generate_dry_run.py

dry_run.lock.yaml 生成器。
src/tier1/lock/dry_run_input.yaml を読み込み、4 pair × 5 phase の migration dry-run 結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 last_green_at: ''）。

catalog SoT: src/tier1/schema/migration/pairs.yaml / src/tier1/schema/migration/phases.yaml
catalog が存在する場合、宣言された pair_id が全て drill 済みであることを検証する。
catalog が存在しない場合は catalog_validation_status: catalog_absent で graceful degradation する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT
from tools.lock_yaml_generator.lib.catalog_validator import (
    load_catalog,
    validate_catalog_against_input,
    build_catalog_metadata,
)

# dry_run_input.yaml の想定名
_INPUT_NAME = "dry_run_input.yaml"

# catalog SoT パス（REPO_ROOT 相対）
_CATALOG_CLASSES_PATH = "src/tier1/schema/migration/pairs.yaml"
_CATALOG_SCENARIOS_PATH = "src/tier1/schema/migration/phases.yaml"

# 4 primary pair 定義（02_移行Pair適合仕様.md の v1 primary pair セットと一致する）
_PAIRS: list[dict[str, str]] = [
    # PostgreSQL（CloudNativePG）→ PostgreSQL（StackGres）移行ペア
    {"pair_id": "relational_pg_pair", "from_oss": "cnpg_postgresql", "to_oss": "stackgres_postgresql"},
    # Apache Kafka（Strimzi）→ RedPanda 移行ペア
    {"pair_id": "messaging_kafka_pair", "from_oss": "strimzi_kafka", "to_oss": "redpanda"},
    # Temporal → Cadence 移行ペア
    {"pair_id": "workflow_pair", "from_oss": "temporal", "to_oss": "cadence"},
    # ZEN Engine → 自製 DSL backend（Rust 実装）移行ペア
    {"pair_id": "rule_engine_pair", "from_oss": "zen_engine", "to_oss": "custom_rust_dsl"},
]

# 5 phase 定義（順序固定、変更は破壊的変更）
_PHASES: list[str] = [
    # フェーズ 1: スキーマ差分検出
    "schema_diff",
    # フェーズ 2: 状態複製
    "state_replicate",
    # フェーズ 3: 二重書き込みランプアップ
    "dual_write_ramp",
    # フェーズ 4: カットオーバー
    "cutover",
    # フェーズ 5: ロールバック
    "rollback",
]


class DryRunGenerator(BaseGenerator):
    """dry_run.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "dry_run.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/dry_run_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """4 pair の dry-run 結果を正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        catalog SoT (migration/pairs.yaml) が存在する場合は cross-validation を実行する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # pairs キーを読み込む
        raw_pairs: list[dict[str, Any]] = inputs.get("pairs", [])

        if raw_pairs:
            # 入力データから pairs を正規化する
            pairs = self._normalize_pairs(raw_pairs)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            pairs = self._build_skeleton()

        # catalog SoT のパスを解決する
        classes_path = REPO_ROOT / _CATALOG_CLASSES_PATH
        scenarios_path = REPO_ROOT / _CATALOG_SCENARIOS_PATH

        # catalog yaml を読み込む（不在時は None）
        classes_catalog = load_catalog(classes_path)
        scenarios_catalog = load_catalog(scenarios_path)

        # pairs catalog の cross-validation: pairs[].pair_id vs input pairs[].pair_id
        # migration/pairs.yaml は "pair_id" をキーとして使う（"id" ではない）
        classes_result = validate_catalog_against_input(
            catalog=classes_catalog,
            input_data=inputs,
            class_key="pairs",
            input_id_key="pair_id",
            input_list_key="pairs",
            catalog_path=classes_path,
            catalog_id_key="pair_id",
        )

        # phases catalog の cross-validation（phase_id と drill id の対応がないため passed 扱い）
        scenarios_result = validate_catalog_against_input(
            catalog=scenarios_catalog,
            input_data={},
            class_key="phases",
            input_id_key="phase_id",
            input_list_key=None,
            catalog_path=scenarios_path,
            catalog_id_key="phase_id",
        )
        # phases は pairs 配下に埋め込まれているため直接突合しない
        if scenarios_catalog is not None:
            scenarios_result = {
                "status": "passed",
                "missing": [],
                "catalog_sot_hash": scenarios_result.get("catalog_sot_hash"),
            }

        # metadata を構築する
        catalog_meta = build_catalog_metadata(
            classes_result=classes_result,
            scenarios_result=scenarios_result,
            classes_path=_CATALOG_CLASSES_PATH,
            scenarios_path=_CATALOG_SCENARIOS_PATH,
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_dry_run.py"
            ),
            "total_pairs":  len(pairs),
            "total_phases": len(_PHASES),
            "total_cells":  len(pairs) * len(_PHASES),
            "generated_at": generated_at,
            "metadata":     catalog_meta,
            "pairs":        pairs,
        }

    @staticmethod
    def _normalize_pairs(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """pair エントリを正規化する。phases も正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            raw_phases: list[dict[str, Any]] = entry.get("phases", [])
            phases = [
                {
                    "phase_id":       str(p.get("phase_id", "")),
                    "drill_state":    str(p.get("drill_state", "pending")),
                    "last_green_at":  str(p.get("last_green_at", "")),
                    "notes":          str(p.get("notes", "")),
                }
                for p in raw_phases
            ]
            # last_green_at が全フェーズで記録されていれば pair 全体を green とする
            any_green_at = next(
                (p["last_green_at"] for p in phases if p["last_green_at"]), ""
            )
            # 全フェーズ green なら pair status = green
            all_green = all(p["drill_state"] == "green" for p in phases)
            result.append({
                "pair_id":       str(entry.get("pair_id", "")),
                "from_oss":      str(entry.get("from_oss", "")),
                "to_oss":        str(entry.get("to_oss", "")),
                "last_green_at": any_green_at,
                "status":        "green" if all_green else "pending",
                "phases":        phases,
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """4 pair × 5 phase のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for pair in _PAIRS:
            phases = [
                {
                    "phase_id":      phase,
                    "drill_state":   "pending",
                    "last_green_at": "",
                    "notes":         "",
                }
                for phase in _PHASES
            ]
            result.append({
                "pair_id":       pair["pair_id"],
                "from_oss":      pair["from_oss"],
                "to_oss":        pair["to_oss"],
                "last_green_at": "",
                "status":        "pending",
                "phases":        phases,
            })
        return result
