#!/usr/bin/env python3
"""tools/lock_yaml_generator/generate_release_gate.py

release_gate.lock.yaml 生成 skeleton。

[release_gate 体系](docs/04_詳細設計/05_lock_yaml体系/03_release_gate体系.md) に従い、
各軸の lock.yaml + cosign 署名 を入力として AND-gate を計算する。

実装 status: skeleton（spec のみ、実コードは別 PR で詳細実装）
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    print("ERROR: PyYAML required", file=sys.stderr)
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# 19 軸 + cross-cutting + meta の release_gate cell catalog
RELEASE_GATE_CELLS = [
    # formal
    {"axis_id": "formal", "cell_id": "formal.all_critical_verified",
     "source_lock_artifact": "proof_status.lock.yaml"},
    {"axis_id": "formal", "cell_id": "formal.proof_matrix_complete",
     "source_lock_artifact": "proof_matrix.lock.yaml"},
    {"axis_id": "formal", "cell_id": "formal.dual_review_completeness_100pct",
     "source_lock_artifact": "proof_review.lock.yaml"},
    # tier1
    {"axis_id": "tier1", "cell_id": "tier1.bidi_conformance_complete",
     "source_lock_artifact": "capabilities.lock.yaml"},
    {"axis_id": "tier1", "cell_id": "tier1.slo_compliance_quarterly_green",
     "source_lock_artifact": "instruments.lock.yaml"},
    {"axis_id": "tier1", "cell_id": "tier1.oss_lifecycle_drill_green",
     "source_lock_artifact": "oss_inventory.lock.yaml"},
    # tier2
    {"axis_id": "tier2", "cell_id": "tier2.tenant_isolation_drill_green",
     "source_lock_artifact": "migration.lock.yaml"},
    # tier3
    {"axis_id": "tier3", "cell_id": "tier3.client_state_conformance_complete",
     "source_lock_artifact": "conflict_tree.lock.yaml"},
    # client
    {"axis_id": "client", "cell_id": "client.sdk_distribution_5class_green",
     "source_lock_artifact": "sdk_conformance.lock.yaml"},
    # infra / data / security / ops / test
    {"axis_id": "infra", "cell_id": "infra.topology_class_drill_green",
     "source_lock_artifact": "topology_class.lock.yaml"},
    {"axis_id": "infra", "cell_id": "infra.clock_integrity_drill_green",
     "source_lock_artifact": "clock_causality_proof.lock.yaml"},
    {"axis_id": "data", "cell_id": "data.preservation_class_drill_green",
     "source_lock_artifact": "preservation_substrates.lock.yaml"},
    {"axis_id": "security", "cell_id": "security.threat_model_coverage_100pct",
     "source_lock_artifact": "threat_model.lock.yaml"},
    {"axis_id": "security", "cell_id": "security.build_provenance_slsa_l3plus",
     "source_lock_artifact": "artifact_inventory.lock.yaml"},
    {"axis_id": "ops", "cell_id": "ops.loop_closure_complete",
     "source_lock_artifact": "ops_loop.lock.yaml"},
    {"axis_id": "test", "cell_id": "test.coverage_matrix_complete",
     "source_lock_artifact": "coverage_matrix.lock.yaml"},
    # meta
    {"axis_id": "meta", "cell_id": "meta.axis_registry_complete",
     "source_lock_artifact": "axis_registry.lock.yaml"},
    {"axis_id": "meta", "cell_id": "meta.docs_lint_green",
     "source_lock_artifact": "docs_lint.lock.yaml"},
    {"axis_id": "meta", "cell_id": "meta.repository_layout_integrity",
     "source_lock_artifact": "repository_layout.lock.yaml"},
    {"axis_id": "meta", "cell_id": "meta.release_gate_dual_signoff_complete",
     "source_lock_artifact": "release_gate.lock.yaml"},
]


def evaluate_cell(cell: dict) -> dict:
    """単一 cell の status を評価する skeleton。

    実装は各軸の lock.yaml を読み込み、cell ごとの green/red 判定。
    skeleton のため red 初期値で返す。
    """
    return {
        "axis_id": cell["axis_id"],
        "cell_id": cell["cell_id"],
        "status": "red",  # skeleton: 全 cell red 初期値
        "last_evaluated_at": datetime.now(timezone.utc).isoformat(),
        "source_lock_artifact": cell["source_lock_artifact"],
        "source_field_path": "skeleton",
    }


def generate(output_path: Path) -> None:
    cells = [evaluate_cell(c) for c in RELEASE_GATE_CELLS]
    red_cells = [c["cell_id"] for c in cells if c["status"] != "green"]
    artifact = {
        "_AUTO_GENERATED": "DO NOT EDIT. Generated by tools/lock_yaml_generator/generate_release_gate.py",
        "release_version": "1.0.0",
        "release_gate_status": "green" if not red_cells else "red",
        "cells": cells,
        "red_cells": red_cells,
        "cosign_signature_pointers": [],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    output_path.write_text(yaml.safe_dump(artifact, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"Generated: {output_path}")
    print(f"release_gate_status: {artifact['release_gate_status']}")
    print(f"red_cells: {len(red_cells)} / {len(cells)}")


if __name__ == "__main__":
    output = REPO_ROOT / "tools/lock_yaml_generator/samples/release_gate.lock.yaml"
    output.parent.mkdir(parents=True, exist_ok=True)
    generate(output)
