"""tools/lock_yaml_generator/generate_evidence_coverage.py

evidence_coverage.lock.yaml 生成器。

proof_trace.lock.yaml の PROOF-ID セットと build_evidence.lock.yaml のエントリを照合し、
各軸（axis）について build evidence が存在するかを判定する。
proof_to_evidence_ratio = (証拠付き PROOF-ID 数) / (全 PROOF-ID 数) を計算して出力する。

マッチング方式: 軸（axis）プレフィクス照合
  PROOF-<axis>-<pclass>-<NNN> の <axis> 部が、
  build_evidence の cell_id の先頭部（<axis>.* 形式）と一致すれば証拠あり と判定する。

フェーズ別達成目標:
  R5 完了: proof_to_evidence_ratio >= 1.0（全軸に build evidence が存在）
"""

from __future__ import annotations

import datetime
import re
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    raise ImportError("PyYAML required: pip install PyYAML")

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# PROOF-ID から axis を抽出するパターン
_PROOF_AXIS_PATTERN = re.compile(
    r"^PROOF-([a-z][a-z0-9_]*)-(?:tsafe|tlive|refn|prog|rtmc)-[0-9]{3}$"
)


def _extract_axis(proof_id: str) -> str | None:
    """PROOF-ID から axis 名を抽出する。"""
    m = _PROOF_AXIS_PATTERN.match(proof_id)
    return m.group(1) if m else None


def _normalize_cell_axis(cell_id: str) -> str | None:
    """build_evidence の cell_id から axis プレフィクスを抽出する。"""
    # cell_id は "<axis>.<rest>" 形式
    if "." in cell_id:
        return cell_id.split(".")[0]
    return None


class EvidenceCoverageGenerator(BaseGenerator):
    """evidence_coverage.lock.yaml 生成器。

    proof_trace.lock.yaml の PROOF-ID と build_evidence.lock.yaml のエントリを照合し、
    proof_to_evidence_ratio（axis プレフィクス照合）を計算する。

    release_gate cell meta.evidence_coverage_ratchet はこの lock を参照する。
    """

    # 出力ファイル名
    OUTPUT_NAME = "evidence_coverage.lock.yaml"
    # 依存する入力 lock.yaml
    REQUIRED_INPUTS: list[str] = ["proof_trace.lock.yaml", "build_evidence.lock.yaml"]
    # jsonschema 検証（スキーマは将来追加）
    SCHEMA_PATH: Path | None = None
    # デフォルト出力先
    DEFAULT_OUTPUT_DIR = "src/_meta/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """proof_trace.lock.yaml と build_evidence.lock.yaml を読み込む。"""
        proof_trace = self.load_lock(lock_dir, "proof_trace.lock.yaml")
        build_evidence = self.load_lock(lock_dir, "build_evidence.lock.yaml")
        return {"proof_trace": proof_trace, "build_evidence": build_evidence}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """PROOF-ID ↔ evidence 照合を実行して evidence_coverage artifact を構築する。"""
        proof_trace: dict[str, Any] = inputs.get("proof_trace", {})
        build_evidence: dict[str, Any] = inputs.get("build_evidence", {})

        # proof_trace から全 PROOF-ID と axis を収集する
        proof_edges = proof_trace.get("proof_edges") or []
        proof_ids: set[str] = {e.get("proof_id", "") for e in proof_edges
                               if isinstance(e, dict) and e.get("proof_id")}
        total_proof_ids = len(proof_ids)

        # build_evidence の全エントリから covered axes を収集する
        evidence_entries = build_evidence.get("entries") or build_evidence.get("evidence_entries") or []
        covered_axes: set[str] = set()
        for entry in evidence_entries:
            if not isinstance(entry, dict):
                continue
            cell_id = entry.get("cell_id") or entry.get("id") or ""
            axis = _normalize_cell_axis(cell_id)
            if axis:
                covered_axes.add(axis)

        # 各 PROOF-ID について axis プレフィクスで coverage を判定する
        proof_ids_with_evidence: set[str] = set()
        uncovered_proofs: list[str] = []
        for proof_id in sorted(proof_ids):
            axis = _extract_axis(proof_id)
            if axis and axis in covered_axes:
                proof_ids_with_evidence.add(proof_id)
            else:
                uncovered_proofs.append(proof_id)

        # proof_to_evidence_ratio を計算する（0 除算回避）
        proof_to_evidence_ratio = (
            round(len(proof_ids_with_evidence) / total_proof_ids, 4)
            if total_proof_ids > 0
            else 0.0
        )

        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by tools/lock_yaml_generator/generate_evidence_coverage.py"
            ),
            "schema_version": "v1",
            "generated_at":   generated_at,
            "summary": {
                "total_proof_ids":           total_proof_ids,
                "proof_ids_with_evidence":   len(proof_ids_with_evidence),
                "proof_to_evidence_ratio":   proof_to_evidence_ratio,
                "covered_axes":              sorted(covered_axes),
                "uncovered_proof_count":     len(uncovered_proofs),
            },
            "uncovered_proofs": uncovered_proofs,
        }
