"""tools/lock_yaml_generator/generate_proof_inventory.py

proof_inventory.lock.yaml 生成器。
src/formal/proof_inventory/inventory.yaml を読み込み、95 cell catalog を正規化する。
inventory.yaml が存在しない場合は 19 軸 × 5 proof_class = 95 entry のスケルトンを生成する。
全エントリのデフォルト cell_state は v1_unverified_handled。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# proof_inventory.yaml の想定パス
_INVENTORY_YAML = REPO_ROOT / "src/formal/proof_inventory/inventory.yaml"

# 19 軸名
_AXIS_NAMES = [
    "tier1", "tier2", "tier3", "infra", "data",
    "security", "ops", "client", "test", "formal",
    "cross_http2", "cross_kek", "cross_schema", "cross_fsm",
    "cross_slo", "cross_bff", "cross_pii", "cross_edge", "meta",
]

# 5 proof_class と短縮形（obligation_id 生成用）
_PROOF_CLASSES: list[tuple[str, str]] = [
    ("v1_temporal_safety_proof",      "tsp"),
    ("v1_program_correctness_proof",  "pcp"),
    ("v1_refinement_proof",           "rfp"),
    ("v1_runtime_model_check",        "rmc"),
    ("v1_property_axiom",             "pax"),
]


class ProofInventoryGenerator(BaseGenerator):
    """proof_inventory.lock.yaml 生成器。"""

    OUTPUT_NAME = "proof_inventory.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/formal/proof_inventory/inventory.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _INVENTORY_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_INVENTORY_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """95 cell catalog を正規化して返す。
        inputs が空の場合はスケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_obligations: list[dict[str, Any]] = inputs.get("obligations", [])

        if raw_obligations:
            obligations = self._normalize_obligations(raw_obligations)
        else:
            obligations = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_proof_inventory.py"
            ),
            "total_cells":   len(obligations),
            "axis_count":    len(_AXIS_NAMES),
            "class_count":   len(_PROOF_CLASSES),
            "generated_at":  generated_at,
            "obligations":   obligations,
        }

    @staticmethod
    def _normalize_obligations(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """obligations エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "obligation_id": str(entry.get("obligation_id", "")),
                "axis_name":     str(entry.get("axis_name", "")),
                "proof_class":   str(entry.get("proof_class", "")),
                "cell_state":    str(entry.get("cell_state", "v1_unverified_handled")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """19 軸 × 5 proof_class = 95 entry のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for axis_name in _AXIS_NAMES:
            for proof_class, short in _PROOF_CLASSES:
                obligation_id = f"{axis_name}_{short}"
                result.append({
                    "obligation_id": obligation_id,
                    "axis_name":     axis_name,
                    "proof_class":   proof_class,
                    "cell_state":    "v1_unverified_handled",
                })
        return result
