"""tools/lock_yaml_generator/generate_coverage_matrix.py

coverage_matrix.lock.yaml 生成器。
src/test/coverage_matrix/scaffold.yaml を読み込み、90 cell matrix を正規化する。
scaffold.yaml が存在しない場合は 18 軸 × 5 class = 90 cell のスケルトンを生成する。
全エントリのデフォルト drill_state は v1_pending_with_artifact。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# scaffold.yaml の想定パス
_SCAFFOLD_YAML = REPO_ROOT / "src/test/coverage_matrix/scaffold.yaml"

# 18 軸（formal を除く 19 軸のうち 18 軸）
_AXIS_NAMES_18 = [
    "tier1", "tier2", "tier3", "infra", "data",
    "security", "ops", "client", "test",
    "cross_http2", "cross_kek", "cross_schema", "cross_fsm",
    "cross_slo", "cross_bff", "cross_pii", "cross_edge", "meta",
]

# 5 verification class
_VERIFICATION_CLASSES: list[str] = [
    "v1_type_invariant",
    "v1_property_axiom",
    "v1_contract_pair",
    "v1_scenario_replay",
    "v1_fault_chaos",
]


class CoverageMatrixGenerator(BaseGenerator):
    """coverage_matrix.lock.yaml 生成器。"""

    OUTPUT_NAME = "coverage_matrix.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/coverage_matrix/scaffold.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _SCAFFOLD_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_SCAFFOLD_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """90 cell matrix を正規化して artifact dict を返す。
        inputs が空の場合はスケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_cells: list[dict[str, Any]] = inputs.get("cells", [])

        if raw_cells:
            cells = self._normalize_cells(raw_cells)
        else:
            cells = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_coverage_matrix.py"
            ),
            "axis_count":               len(_AXIS_NAMES_18),
            "verification_class_count": len(_VERIFICATION_CLASSES),
            "total_cells":              len(cells),
            "generated_at":             generated_at,
            "cells":                    cells,
        }

    @staticmethod
    def _normalize_cells(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """cells エントリを正規化する。
        artifact_pointer と last_green_at が scaffold.yaml に記載されている場合は引き継ぐ。
        """
        result: list[dict[str, Any]] = []
        for entry in raw:
            # artifact_pointer: scaffold.yaml の値を引き継ぐ（存在しない場合は None）
            artifact_pointer = entry.get("artifact_pointer")
            # last_green_at: scaffold.yaml の値を引き継ぐ（存在しない場合は None）
            last_green_at = entry.get("last_green_at")
            # wsl2_constraint: WSL2 制約による accepted_with_assumption の記録
            wsl2_constraint = entry.get("wsl2_constraint")
            # drill_state: scaffold.yaml の値を引き継ぐ（存在しない場合はデフォルト値）
            drill_state = str(entry.get("drill_state", "v1_pending_with_artifact"))
            # cell エントリを構築する
            cell: dict[str, Any] = {
                "cell_id":            str(entry.get("cell_id", "")),
                "axis_name":          str(entry.get("axis_name", entry.get("axis", ""))),
                "verification_class": str(entry.get("verification_class", "")),
                "drill_state":        drill_state,
            }
            # artifact_pointer が存在する場合は追加する
            if artifact_pointer is not None:
                cell["artifact_pointer"] = str(artifact_pointer)
            # last_green_at が存在する場合は追加する
            if last_green_at is not None:
                cell["last_green_at"] = str(last_green_at)
            # wsl2_constraint が存在する場合は追加する
            if wsl2_constraint is not None:
                cell["wsl2_constraint"] = str(wsl2_constraint)
            result.append(cell)
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """18 軸 × 5 class = 90 cell のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for axis_name in _AXIS_NAMES_18:
            for vc in _VERIFICATION_CLASSES:
                cell_id = f"{axis_name}__{vc}"
                result.append({
                    "cell_id":            cell_id,
                    "axis_name":          axis_name,
                    "verification_class": vc,
                    "drill_state":        "v1_pending_with_artifact",
                })
        return result
