# k1s0-proof: PROOF-cross_edge-prog-004 -> IMPL-cross_edge-0004
"""tools/lock_yaml_generator/generate_weaver.py

# weaver.lock.yaml 生成器。
# src/tier2/observability/ ディレクトリを確認し、
# Weaver semantic convention の宣言状態を lock artifact として生成する。
# observability/weaver/ が存在しない場合は status='declared' (証拠未収集)。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# observability ディレクトリの想定パス
_OBSERVABILITY_DIR = REPO_ROOT / "src/tier2/observability"
# weaver サブディレクトリの想定パス
_WEAVER_DIR = _OBSERVABILITY_DIR / "weaver"


class WeaverGenerator(BaseGenerator):
    """weaver.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "weaver.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/observability/weaver/ ディレクトリの存在を確認する。
        存在する場合はディレクトリパスを返す。存在しない場合は空 dict を返す。
        """
        # weaver ディレクトリが存在する場合は存在フラグを返す
        if _WEAVER_DIR.exists() and _WEAVER_DIR.is_dir():
            # weaver ディレクトリが存在することを示すフラグを返す
            return {"weaver_dir_exists": True}
        # ディレクトリが存在しない場合は空 dict を返す（証拠未収集）
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Weaver semantic convention の宣言状態を表す artifact dict を返す。
        weaver ディレクトリが存在しない場合は status='declared' (green ではない)。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # weaver ディレクトリの存在を確認する
        weaver_dir_exists = inputs.get("weaver_dir_exists", False)

        # weaver ディレクトリが存在する場合は green、存在しない場合は declared とする
        if weaver_dir_exists:
            # weaver ディレクトリが存在する場合は証拠ありとして green にする
            semconv_status = "green"
            # golden files の状態も green にする
            golden_files_status = "green"
            # 総合ステータスも green にする
            overall_status = "green"
        else:
            # weaver ディレクトリが存在しない場合は証拠未収集として declared にする
            semconv_status = "declared"
            # golden files の状態も declared にする
            golden_files_status = "declared"
            # 総合ステータスも declared にする（Stage 3 で証拠収集予定）
            overall_status = "declared"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_weaver.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # semantic convention の状態
            "semconv_tier2_status": semconv_status,
            # golden files の状態
            "golden_files_status": golden_files_status,
            # 総合ステータス（証拠未収集の場合は declared）
            "status": overall_status,
        }
