"""tools/lock_yaml_generator/generate_oss_conformance_check.py

oss_conformance_check.lock.yaml 生成器。
src/tier1/lock/oss_conformance_check_input.yaml を読み込み、四半期 L2* 適合チェック結果を正規化する。
存在しない場合はフォールバックスケルトンを生成する（status: pending）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# oss_conformance_check_input.yaml の想定名
_INPUT_NAME = "oss_conformance_check_input.yaml"


class OssConformanceCheckGenerator(BaseGenerator):
    """oss_conformance_check.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "oss_conformance_check.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/oss_conformance_check_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から oss_conformance_check_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """OSS 適合チェック結果を正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # check_quarter キーを読み込む（デフォルトは空文字列）
        check_quarter: str = str(inputs.get("check_quarter", ""))
        # total_oss_checked キーを読み込む（デフォルトは 0）
        total_oss_checked: int = int(inputs.get("total_oss_checked", 0))
        # conformant_count キーを読み込む（デフォルトは 0）
        conformant_count: int = int(inputs.get("conformant_count", 0))
        # non_conformant_count キーを読み込む（デフォルトは 0）
        non_conformant_count: int = int(inputs.get("non_conformant_count", 0))
        # status キーを読み込む（デフォルトは pending）
        status: str = str(inputs.get("status", "pending"))
        # last_check_at キーを読み込む（デフォルトは null）
        last_check_at = inputs.get("last_check_at", None)

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_oss_conformance_check.py"
            ),
            # チェック対象四半期（YYYY-QN 形式）
            "check_quarter": check_quarter,
            # チェック対象 OSS 総数
            "total_oss_checked": total_oss_checked,
            # 適合 OSS 数
            "conformant_count": conformant_count,
            # 非適合 OSS 数
            "non_conformant_count": non_conformant_count,
            # 全体ステータス（green / pending / red）
            "status": status,
            # 最終チェック実行日時（ISO 8601 または null）
            "last_check_at": last_check_at,
            # ロック生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
        }


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    OssConformanceCheckGenerator().emit(REPO_ROOT / "src/tier1/lock")
