"""tools/lock_yaml_generator/generate_sbom_triage.py

sbom_triage.lock.yaml 生成器。
src/tier1/lock/sbom_triage_input.yaml を読み込み、月次 SBOM/CVE トリアージログを正規化する。
存在しない場合はフォールバックスケルトンを生成する（triage_status: pending）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# sbom_triage_input.yaml の想定名
_INPUT_NAME = "sbom_triage_input.yaml"


class SbomTriageGenerator(BaseGenerator):
    """sbom_triage.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "sbom_triage.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/sbom_triage_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から sbom_triage_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """SBOM トリアージログを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # triage_month キーを読み込む（デフォルトは空文字列）
        triage_month: str = str(inputs.get("triage_month", ""))
        # cve_critical_count キーを読み込む（デフォルトは 0）
        cve_critical_count: int = int(inputs.get("cve_critical_count", 0))
        # cve_high_count キーを読み込む（デフォルトは 0）
        cve_high_count: int = int(inputs.get("cve_high_count", 0))
        # cve_medium_count キーを読み込む（デフォルトは 0）
        cve_medium_count: int = int(inputs.get("cve_medium_count", 0))
        # medium_accepted_with_justification キーを読み込む（デフォルトは 0）
        medium_accepted_with_justification: int = int(inputs.get("medium_accepted_with_justification", 0))
        # triage_status キーを読み込む（デフォルトは pending）
        triage_status: str = str(inputs.get("triage_status", "pending"))

        # status: triage_status をそのまま使用する
        status = triage_status

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_sbom_triage.py"
            ),
            # トリアージ対象月（YYYY-MM 形式）
            "triage_month": triage_month,
            # CRITICAL CVE 件数
            "cve_critical_count": cve_critical_count,
            # HIGH CVE 件数
            "cve_high_count": cve_high_count,
            # MEDIUM CVE 件数
            "cve_medium_count": cve_medium_count,
            # 正当化理由付きで受容した MEDIUM CVE 件数
            "medium_accepted_with_justification": medium_accepted_with_justification,
            # トリアージステータス（green / pending / red）
            "triage_status": triage_status,
            # 全体ステータス（= triage_status）
            "status": status,
            # ロック生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
        }


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    SbomTriageGenerator().emit(REPO_ROOT / "src/tier1/lock")
