# k1s0-proof: PROOF-infra-prog-003 -> IMPL-infra-0003
# k1s0-impl: IMPL-infra-0003 realizes=FR-infra-003
"""tools/lock_yaml_generator/generate_failover_drill.py

failover_drill.lock.yaml 生成器。
src/infra/topology/failover_drill.yaml を読み込み、drills リストを正規化する。
各 drill は drill_id, topology_class, drill_state: pending を持つ。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# failover_drill.yaml の想定パス
_DRILL_YAML = REPO_ROOT / "src/infra/topology/failover_drill.yaml"

# 5 topology_class（スケルトン生成用）
_TOPOLOGY_CLASSES: list[str] = [
    "v1_single_zone",
    "v1_multi_zone_per_cluster",
    "v1_active_passive_dr",
    "v1_multi_region_active_passive",
    "v1_multi_region_active_active",
]


class FailoverDrillGenerator(BaseGenerator):
    """failover_drill.lock.yaml 生成器。"""

    OUTPUT_NAME = "failover_drill.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/infra/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/infra/topology/failover_drill.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _DRILL_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_DRILL_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """drills リストを正規化して artifact dict を返す。
        inputs が空の場合は topology_class に対応するスケルトンを生成する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_drills: list[dict[str, Any]] = inputs.get("drills", [])

        if raw_drills:
            drills = self._normalize_drills(raw_drills)
        else:
            drills = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_failover_drill.py"
            ),
            "total_drills": len(drills),
            "generated_at": generated_at,
            "drills":       drills,
        }

    @staticmethod
    def _normalize_drills(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """drill エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "drill_id":       str(entry.get("drill_id", "")),
                "topology_class": str(entry.get("topology_class", "")),
                "drill_state":    str(entry.get("drill_state", "pending")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """5 topology_class に対応するスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for tc in _TOPOLOGY_CLASSES:
            result.append({
                "drill_id":       f"failover__{tc}",
                "topology_class": tc,
                "drill_state":    "pending",
            })
        return result
