# k1s0-proof: PROOF-data-prog-004 -> IMPL-data-0003
# k1s0-impl: IMPL-data-0003 realizes=FR-data-003
"""tools/lock_yaml_generator/generate_sbom_catalog.py

sbom_catalog.lock.yaml 生成器。
src/tier1/lock/sbom_catalog_input.yaml を読み込み、Syft で生成された SBOM カタログ状態を正規化する。
存在しない場合はフォールバックスケルトンを生成する（catalog_status: pending）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# sbom_catalog_input.yaml の想定名
_INPUT_NAME = "sbom_catalog_input.yaml"


class SbomCatalogGenerator(BaseGenerator):
    """sbom_catalog.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "sbom_catalog.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/sbom_catalog_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から sbom_catalog_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """SBOM カタログ状態を正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # component_count キーを読み込む（デフォルトは 0）
        component_count: int = int(inputs.get("component_count", 0))
        # ecosystems キーを読み込む（デフォルトは空リスト）
        ecosystems: list[str] = list(inputs.get("ecosystems", []))
        # sbom_format キーを読み込む（デフォルトは CycloneDX_1.4）
        sbom_format: str = str(inputs.get("sbom_format", "CycloneDX_1.4"))
        # catalog_status キーを読み込む（デフォルトは pending）
        catalog_status: str = str(inputs.get("catalog_status", "pending"))
        # generated_at_sbom キーを読み込む（デフォルトは null）
        generated_at_sbom = inputs.get("generated_at", None)

        # status: catalog_status をそのまま使用する
        status = catalog_status

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_sbom_catalog.py"
            ),
            # コンポーネント総数
            "component_count": component_count,
            # エコシステム一覧
            "ecosystems": ecosystems,
            # SBOM フォーマット（CycloneDX_1.4 等）
            "sbom_format": sbom_format,
            # 全体ステータス（= catalog_status）
            "status": status,
            # SBOM 生成日時（UTC ISO 8601 形式）
            "sbom_generated_at": generated_at_sbom,
            # ロック生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
        }


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    SbomCatalogGenerator().emit(REPO_ROOT / "src/tier1/lock")
