"""tools/lock_yaml_generator/generate_docs_lint.py

docs_lint.lock.yaml 生成器。
src/_meta/lock/docs_lint_result.yaml を読み込み、lint 結果を正規化して出力する。
docs_lint_result.yaml が存在して status: green なら green、なければ yellow (pending)。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# lint 結果ファイルの想定パス（lock_dir 内）
_LINT_RESULT_NAME = "docs_lint_result.yaml"


class DocsLintGenerator(BaseGenerator):
    """docs_lint.lock.yaml 生成器。"""

    OUTPUT_NAME = "docs_lint.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/_meta/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """lock_dir 内の docs_lint_result.yaml を読み込む。
        存在しない場合は空 dict を返す（ツールを直接 import・実行しない）。
        """
        return self.load_lock(lock_dir, _LINT_RESULT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """lint 結果を正規化して artifact dict を返す。
        inputs が green なら green、それ以外は yellow (pending)。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        if inputs and inputs.get("status") == "green":
            status = "green"
            # 既存 checks リストがあれば引き継ぐ
            checks: list[dict[str, Any]] = inputs.get("checks", [])
            detail = "docs_lint_result.yaml reports green"
        else:
            # docs_lint_result.yaml が存在しないか、green 以外の場合
            status = "yellow"
            checks = []
            detail = "docs_lint_result.yaml not found or not green (pending)"

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_docs_lint.py"
            ),
            "status":       status,
            "detail":       detail,
            "checks":       checks,
            "generated_at": generated_at,
        }
