"""tools/lock_yaml_generator/generate_notifications_property.py

# notifications_property.lock.yaml 生成器。
# src/tier3/typescript/packages/notifications/ ディレクトリを確認し、
# Notifications パッケージのプロパティベーステスト状態を lock artifact として生成する。
# パッケージが存在しない場合は property_status='declared' を返す。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# notifications パッケージディレクトリの想定パス
_NOTIFICATIONS_DIR = REPO_ROOT / "src/tier3/typescript/packages/notifications"
# notifications パッケージの package.json パス
_NOTIFICATIONS_PACKAGE_JSON = _NOTIFICATIONS_DIR / "package.json"


class NotificationsPropertyGenerator(BaseGenerator):
    """notifications_property.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "notifications_property.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier3/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier3/typescript/packages/notifications/ の存在を確認する。
        存在する場合はパッケージ情報を返す。存在しない場合は空 dict を返す。
        """
        # notifications パッケージディレクトリが存在するか確認する
        notifications_dir_exists = _NOTIFICATIONS_DIR.exists() and _NOTIFICATIONS_DIR.is_dir()
        # package.json が存在するか確認する
        package_json_exists = _NOTIFICATIONS_PACKAGE_JSON.exists()
        # 確認結果を返す
        return {
            "notifications_dir_exists":    notifications_dir_exists,
            "package_json_exists":         package_json_exists,
        }

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Notifications パッケージのプロパティテスト状態を表す artifact dict を返す。
        パッケージが存在しない場合は全て 'declared'。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # package.json の存在を確認する
        package_json_exists = inputs.get("package_json_exists", False)

        # package.json が存在する場合は 'ready'、存在しない場合は 'declared' とする
        notifications_package_status = "ready" if package_json_exists else "declared"

        # プロパティテストのステータス（物理テストは Stage 4 で実施）
        property_status = "declared"

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_notifications_property.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # プロパティテストのステータス（冪等性 / 順序保証の物理検証は Stage 4）
            "property_status": property_status,
            # notifications パッケージの状態（package.json の有無で判定）
            "notifications_package_status": notifications_package_status,
        }
