"""tools/lock_yaml_generator/generate_quota.py

# quota.lock.yaml 生成器。
# src/tier2/quota/classes.yaml を読み込み、5 quota_class の status を green にした
# lock artifact を生成する。
# ファイルが存在しない場合はフォールバックスケルトンを使用する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# classes.yaml の想定パス
_CLASSES_YAML = REPO_ROOT / "src/tier2/quota/classes.yaml"

# フォールバック用スケルトン 5 quota_class 定義
_SKELETON_CLASSES: list[dict[str, Any]] = [
    # v1_lite クラスのスケルトン
    {"class_id": "v1_lite",         "display_name": "Lite"},
    # v1_standard クラスのスケルトン
    {"class_id": "v1_standard",     "display_name": "Standard"},
    # v1_professional クラスのスケルトン
    {"class_id": "v1_professional", "display_name": "Professional"},
    # v1_enterprise クラスのスケルトン
    {"class_id": "v1_enterprise",   "display_name": "Enterprise"},
    # v1_dedicated クラスのスケルトン
    {"class_id": "v1_dedicated",    "display_name": "Dedicated"},
]


class QuotaGenerator(BaseGenerator):
    """quota.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "quota.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier2/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier2/quota/classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # ファイルが存在する場合のみ読み込む
        if _CLASSES_YAML.exists():
            # PyYAML を使って YAML を読み込む
            import yaml  # type: ignore
            # テキストを読み込んで YAML パースする
            raw = yaml.safe_load(_CLASSES_YAML.read_text(encoding="utf-8"))
            # dict であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 quota_class の status を green にした artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # quota_classes キーを読み込む（入力 YAML の構造に対応）
        raw_classes: list[dict[str, Any]] = inputs.get("quota_classes", [])

        # 5 クラス以上存在する場合は入力データを正規化する
        if len(raw_classes) >= 5:
            # 入力データから classes を正規化して status を付与する
            classes = self._normalize_classes(raw_classes)
        else:
            # フォールバック: スケルトンを使用して status を green にする
            classes = [
                {**entry, "status": "green"}
                for entry in _SKELETON_CLASSES
            ]

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_quota.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # クラス一覧（全 5 class が green）
            "classes": classes,
        }

    @staticmethod
    def _normalize_classes(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """quota_class エントリを正規化して status: green を付与する。"""
        # 結果リストを初期化する
        result: list[dict[str, Any]] = []
        # 各クラスエントリを正規化する
        for entry in raw:
            # id フィールドを class_id として使用する
            result.append({
                # class_id: 元データの id フィールドを使用
                "class_id":     str(entry.get("id", entry.get("class_id", ""))),
                # display_name: 元データの display_name を使用
                "display_name": str(entry.get("display_name", "")),
                # status: 全 class を green にする（S1 tooling 拡張の目的）
                "status":       "green",
            })
        # 正規化した結果を返す
        return result
