"""tools/lock_yaml_generator/generate_snapshot_masks.py

snapshot_masks.lock.yaml 生成器。
src/test/snapshot/masks.yaml を読み込み masks リストを正規化する。
存在しない場合は空の masks リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# masks.yaml の想定パス
_MASKS_YAML = REPO_ROOT / "src/test/snapshot/masks.yaml"


class SnapshotMasksGenerator(BaseGenerator):
    """snapshot_masks.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "snapshot_masks.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/test/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/test/snapshot/masks.yaml を読み込む。存在しない場合は空 dict を返す。"""
        # masks.yaml が存在する場合は読み込む
        if _MASKS_YAML.exists():
            # yaml モジュールをインポートする
            import yaml  # type: ignore
            # ファイル内容を読み込んでパースする
            raw = yaml.safe_load(_MASKS_YAML.read_text(encoding="utf-8"))
            # dict 型であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """masks リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # masks リストを inputs から取得する (なければ空リスト)
        raw_masks: list[dict[str, Any]] = inputs.get("masks", [])
        # masks リストを正規化する
        masks = [
            {
                # mask 識別子
                "mask_id": str(m.get("mask_id", "")),
                # マスクパターン（正規表現）
                "pattern": str(m.get("pattern", "")),
                # 置換文字列
                "replacement": str(m.get("replacement", "<masked>")),
                # 理由
                "reason": str(m.get("reason", "")),
            }
            for m in raw_masks
            if isinstance(m, dict)
        ]
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_snapshot_masks.py"
            ),
            # mask 総数
            "total_masks": len(masks),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # mask リスト
            "masks": masks,
        }
