"""tools/lock_yaml_generator/generate_cross_cutting_registry.py

cross_cutting_registry.lock.yaml 生成器。
13 spec の cluster bundle map を axis_registry.lock.yaml から構築する。
8 cluster: cross_http2/cross_kek/cross_schema/cross_fsm/cross_slo/cross_bff/cross_pii/cross_edge
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# 13 spec 定義: (spec_id, cluster_id, primary_axis)
_SPEC_CATALOG: list[tuple[str, str, str]] = [
    ("c01", "cross_http2",  "cross_http2"),
    ("c02", "cross_kek",    "cross_kek"),
    ("c03", "cross_schema", "cross_schema"),
    ("c04", "cross_fsm",    "cross_fsm"),
    ("c05", "cross_slo",    "cross_slo"),
    ("c06", "cross_bff",    "cross_bff"),
    ("c07", "cross_bff",    "cross_bff"),
    ("c08", "cross_pii",    "cross_pii"),
    ("c09", "cross_pii",    "cross_pii"),
    ("c10", "cross_edge",   "cross_edge"),
    ("c11", "cross_edge",   "cross_edge"),
    ("c12", "cross_edge",   "cross_edge"),
    ("c13", "cross_edge",   "cross_edge"),
]

# クラスター一覧（8 個）
_CLUSTERS = [
    "cross_http2",
    "cross_kek",
    "cross_schema",
    "cross_fsm",
    "cross_slo",
    "cross_bff",
    "cross_pii",
    "cross_edge",
]


class CrossCuttingRegistryGenerator(BaseGenerator):
    """cross_cutting_registry.lock.yaml 生成器。"""

    OUTPUT_NAME = "cross_cutting_registry.lock.yaml"
    REQUIRED_INPUTS: list[str] = ["axis_registry.lock.yaml"]
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/_meta/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """axis_registry.lock.yaml を読み込む。存在しない場合は空 dict。"""
        return self.load_lock(lock_dir, "axis_registry.lock.yaml")

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """13 spec + 8 cluster の bundle map を構築する。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # 13 spec エントリを生成（docs/04_詳細設計/03_クロスカッティング適合仕様/*.md の published 化に伴い published）
        specs: list[dict[str, Any]] = [
            {
                "spec_id":      spec_id,
                "cluster_id":   cluster_id,
                "primary_axis": primary_axis,
                "status":       "published",
            }
            for spec_id, cluster_id, primary_axis in _SPEC_CATALOG
        ]

        # 8 cluster エントリを生成（各 cluster に属する spec_id リストを付与）
        clusters: list[dict[str, Any]] = []
        for cluster_id in _CLUSTERS:
            member_specs = [s["spec_id"] for s in specs if s["cluster_id"] == cluster_id]
            clusters.append({
                "cluster_id": cluster_id,
                "spec_ids":   member_specs,
                "spec_count": len(member_specs),
            })

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_cross_cutting_registry.py"
            ),
            "specs_count":    len(specs),
            "clusters_count": len(clusters),
            "generated_at":   generated_at,
            "specs":          specs,
            "clusters":       clusters,
        }
