"""tools/lock_yaml_generator/generate_counter_example.py

counter_example.lock.yaml 生成器。
src/formal/lock/counter_example_input.yaml を読み込み、entries リストを正規化する。
存在しない場合は空 entries を返す。open 件数を集計する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# counter_example_input.yaml は lock_dir 内に置かれる
_INPUT_NAME = "counter_example_input.yaml"


class CounterExampleGenerator(BaseGenerator):
    """counter_example.lock.yaml 生成器。"""

    OUTPUT_NAME = "counter_example.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/formal/lock/counter_example_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """entries リストを正規化して open 件数を集計する。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_entries: list[dict[str, Any]] = inputs.get("entries", [])
        entries = self._normalize_entries(raw_entries)

        # open 件数を集計
        open_count = sum(1 for e in entries if e.get("status") == "open")

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_counter_example.py"
            ),
            "total_count":  len(entries),
            "open_count":   open_count,
            "generated_at": generated_at,
            "entries":      entries,
        }

    @staticmethod
    def _normalize_entries(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """counter_example entries を正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "counter_example_id": str(entry.get("counter_example_id", "")),
                "obligation_id":      str(entry.get("obligation_id", "")),
                "severity":           str(entry.get("severity", "low")),
                "status":             str(entry.get("status", "open")),
                "description":        str(entry.get("description", "")),
            })
        return result
