"""tools/lock_yaml_generator/generate_idp_capabilities.py

idp_capabilities.lock.yaml 生成器。
src/tier1/lock/idp_capabilities_input.yaml を読み込み、認証 IdP capability 一覧を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 status: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# idp_capabilities_input.yaml の想定名
_INPUT_NAME = "idp_capabilities_input.yaml"

# 04_認証適合仕様.md §v1 auth_class セット（5 class）に基づく IdP capability 定義
_IDP_CAPABILITIES: list[dict[str, str]] = [
    # v1_human_session: OIDC code flow + DPoP 鍵束縛（RFC 9449）、rotating refresh
    {"idp_id": "v1_human_session", "auth_protocol": "oidc_dpop_bound"},
    # v1_workload_jwt: K8s ServiceAccount projection or SPIFFE/SPIRE SVID、短 TTL
    {"idp_id": "v1_workload_jwt", "auth_protocol": "jwt_svid"},
    # v1_device_attest: TPM / HSM / WebAuthn platform authenticator device cert、長 TTL、one_shot refresh
    {"idp_id": "v1_device_attest", "auth_protocol": "jwt_attested"},
    # v1_federated_exchange: RFC 8693 token exchange、audience-restricted 短命 JWT
    {"idp_id": "v1_federated_exchange", "auth_protocol": "token_exchange"},
    # v1_emergency_step_up: break-glass、always step_up + always step_up WebAuthn/FIDO2、<10m、no refresh
    {"idp_id": "v1_emergency_step_up", "auth_protocol": "oidc_dpop_stepup"},
]


class IdpCapabilitiesGenerator(BaseGenerator):
    """idp_capabilities.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "idp_capabilities.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/idp_capabilities_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """IdP capabilities リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # capabilities キーを読み込む
        raw_caps: list[dict[str, Any]] = inputs.get("capabilities", [])

        if raw_caps:
            # 入力データから capabilities を正規化する
            capabilities = self._normalize_caps(raw_caps)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            capabilities = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_idp_capabilities.py"
            ),
            "total_capabilities": len(capabilities),
            "generated_at":       generated_at,
            "capabilities":       capabilities,
        }

    @staticmethod
    def _normalize_caps(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """IdP capability エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "idp_id":        str(entry.get("idp_id", "")),
                "auth_protocol": str(entry.get("auth_protocol", "")),
                "status":        str(entry.get("status", "pending")),
                "notes":         str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """IdP ごとのスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for cap in _IDP_CAPABILITIES:
            result.append({
                "idp_id":        cap["idp_id"],
                "auth_protocol": cap["auth_protocol"],
                "status":        "pending",
                "notes":         "",
            })
        return result
