"""tools/lock_yaml_generator/generate_forms_lint.py

# forms_lint.lock.yaml 生成器。
# src/tier3/typescript/packages/forms/ ディレクトリを確認し、
# Forms パッケージの lint 状態を lock artifact として生成する。
# package.json が存在する場合は 'ready'、存在しない場合は 'declared'。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# forms パッケージディレクトリの想定パス
_FORMS_DIR = REPO_ROOT / "src/tier3/typescript/packages/forms"
# forms パッケージの package.json パス
_FORMS_PACKAGE_JSON = _FORMS_DIR / "package.json"


class FormsLintGenerator(BaseGenerator):
    """forms_lint.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "forms_lint.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier3/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier3/typescript/packages/forms/ ディレクトリと package.json の存在を確認する。
        package.json が存在する場合は 'ready' フラグを返す。
        """
        # forms パッケージディレクトリが存在するか確認する
        forms_dir_exists = _FORMS_DIR.exists() and _FORMS_DIR.is_dir()
        # package.json が存在するか確認する
        package_json_exists = _FORMS_PACKAGE_JSON.exists()
        # 確認結果を返す
        return {
            "forms_dir_exists":    forms_dir_exists,
            "package_json_exists": package_json_exists,
        }

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Forms パッケージの lint 状態を表す artifact dict を返す。
        package.json が存在する場合は 'ready'、存在しない場合は 'declared'。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # package.json の存在を確認する
        package_json_exists = inputs.get("package_json_exists", False)

        # package.json が存在する場合は 'ready'、存在しない場合は 'declared' とする
        forms_package_status = "ready" if package_json_exists else "declared"

        # 検査件数を計算する（package.json の有無で判定）
        total_checks = 3 if package_json_exists else 0
        # 合格件数（全検査項目が合格の場合は total_checks と同数）
        passed_checks = total_checks
        # 違反件数（現フェーズでは 0 = 物理 lint は Stage 4 で実施）
        violations_count = 0

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_forms_lint.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # 検査総件数（package.json 存在時は 3 件: tenant_id 禁止 / schema / exports）
            "total_checks": total_checks,
            # 合格件数
            "passed_checks": passed_checks,
            # 違反件数（物理 lint は Stage 4 で実施）
            "violations_count": violations_count,
            # ESLint 違反数（後方互換のため残す）
            "violations": violations_count,
            # forms パッケージの状態（package.json の有無で判定）
            "forms_package_status": forms_package_status,
        }
