"""tools/lock_yaml_generator/generate_supply_chain_incident.py

supply_chain_incident.lock.yaml 生成器。
src/tier1/lock/supply_chain_incident_input.yaml を読み込み、サプライチェーンインシデントログと drill 履歴を正規化する。
存在しない場合はフォールバックスケルトンを生成する（incidents: [], drill_status: pending）。
"""

# future annotations: 型アノテーションの前方参照を許可する
from __future__ import annotations

# datetime: 生成日時の記録に使用する
import datetime
# Path: ファイルパス操作に使用する
from pathlib import Path
# Any: 型アノテーションに使用する
from typing import Any

# BaseGenerator: 共通生成器基底クラスをインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# supply_chain_incident_input.yaml の想定名
_INPUT_NAME = "supply_chain_incident_input.yaml"


class SupplyChainIncidentGenerator(BaseGenerator):
    """supply_chain_incident.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "supply_chain_incident.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/supply_chain_incident_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # lock_dir から supply_chain_incident_input.yaml を読み込む
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """サプライチェーンインシデントログを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        # 生成日時を UTC ISO 8601 形式で記録する（status 記録目的の wall-clock: TTL 計算禁止）
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # incidents キーを読み込む（空リストがデフォルト）
        incidents: list[dict[str, Any]] = inputs.get("incidents", [])
        # drill_status キーを読み込む（デフォルトは pending）
        drill_status: str = str(inputs.get("drill_status", "pending"))
        # last_drill_at キーを読み込む（デフォルトは null）
        last_drill_at = inputs.get("last_drill_at", None)

        # incident_count: インシデント総数
        incident_count = len(incidents)
        # status: drill_status が green なら green、それ以外は red
        status = "green" if drill_status == "green" else "red"

        # artifact dict を返す
        return {
            # 自動生成ヘッダー: 手書き編集禁止を明示する
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_supply_chain_incident.py"
            ),
            # インシデント総数
            "incident_count": incident_count,
            # drill ステータス（green / pending / red）
            "drill_status": drill_status,
            # 最終 drill 実行日時（ISO 8601 または null）
            "last_drill_at": last_drill_at,
            # 全体ステータス（green / red）
            "status": status,
            # 生成日時（UTC ISO 8601 形式）
            "generated_at": generated_at,
            # インシデント一覧（空リストが通常状態）
            "incidents": incidents,
        }


# メインガード: 直接実行時に emit() を呼び出す
if __name__ == "__main__":
    SupplyChainIncidentGenerator().emit(REPO_ROOT / "src/tier1/lock")
