"""tools/lock_yaml_generator/generate_runbook_catalog.py

runbook_catalog.lock.yaml 生成器。
src/ops/runbook_catalog/ 配下の .md ファイルを走査して runbooks リストを構築する。
存在しない場合は空の runbooks リストを含む skeleton を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# runbook_catalog ディレクトリの想定パス
_RUNBOOK_DIR = REPO_ROOT / "src/ops/runbook_catalog"


class RunbookCatalogGenerator(BaseGenerator):
    """runbook_catalog.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "runbook_catalog.lock.yaml"
    # 必須入力ファイルなし
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/ops/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/ops/runbook_catalog/ 配下の .md ファイルを走査する。"""
        # runbook_catalog ディレクトリが存在する場合は走査する
        if _RUNBOOK_DIR.exists():
            # .md ファイルのリストを構築する
            runbooks = [
                {"runbook_id": p.stem, "path": str(p.relative_to(REPO_ROOT))}
                for p in sorted(_RUNBOOK_DIR.glob("*.md"))
            ]
            # runbooks リストを含む dict を返す
            return {"runbooks": runbooks}
        # ディレクトリが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """runbooks リストを正規化して artifact dict を返す。"""
        # 生成日時を取得する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        # runbooks リストを inputs から取得する (なければ空リスト)
        runbooks: list[dict[str, Any]] = inputs.get("runbooks", [])
        # artifact dict を返す
        return {
            # 自動生成ヘッダー
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_runbook_catalog.py"
            ),
            # runbook 総数
            "total_runbooks": len(runbooks),
            # 生成日時
            "generated_at": generated_at,
            # 全体ステータス
            "status": "green",
            # runbook リスト
            "runbooks": runbooks,
        }
