"""tools/lock_yaml_generator/generate_signals.py

signals.lock.yaml 生成器。
src/tier1/lock/signals_input.yaml を読み込み、5 signal class の観測実装状況を正規化する。
存在しない場合はフォールバックスケルトンを生成する（全 status: pending）。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# signals_input.yaml の想定名
_INPUT_NAME = "signals_input.yaml"

# 5 signal class 定義（03_観測適合仕様.md の v1 signal class セットと一致する）
_SIGNAL_CLASSES: list[dict[str, str]] = [
    # logs: ClickHouse logs table が SoR
    {"signal_id": "logs", "sor": "clickhouse_logs", "collector": "otel_collector"},
    # metrics: Prometheus が SoR
    {"signal_id": "metrics", "sor": "prometheus", "collector": "otel_collector"},
    # traces: ClickHouse traces table が SoR（Jaeger v2 UI 経由）
    {"signal_id": "traces", "sor": "clickhouse_traces", "collector": "otel_collector_loadbalancing"},
    # profiles: Parca が SoR（eBPF / native pull）
    {"signal_id": "profiles", "sor": "parca", "collector": "parca_agent"},
    # audit: ClickHouse audit table が SoR（PostgreSQL audit_local → Audit relay 経由）
    {"signal_id": "audit", "sor": "clickhouse_audit", "collector": "audit_relay"},
]


class SignalsGenerator(BaseGenerator):
    """signals.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "signals.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier1/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier1/lock/signals_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        return self.load_lock(lock_dir, _INPUT_NAME)

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """5 signal class リストを正規化して artifact dict を返す。
        inputs が空の場合はフォールバックスケルトンを使用する。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # signals キーを読み込む
        raw_signals: list[dict[str, Any]] = inputs.get("signals", [])

        if raw_signals:
            # 入力データから signals を正規化する
            signals = self._normalize_signals(raw_signals)
        else:
            # フォールバック: 全 pending のスケルトンを生成する
            signals = self._build_skeleton()

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_signals.py"
            ),
            "total_signals": len(signals),
            "generated_at":  generated_at,
            "signals":       signals,
        }

    @staticmethod
    def _normalize_signals(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """signal エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "signal_id":  str(entry.get("signal_id", "")),
                "sor":        str(entry.get("sor", "")),
                "collector":  str(entry.get("collector", "")),
                "status":     str(entry.get("status", "pending")),
                "notes":      str(entry.get("notes", "")),
            })
        return result

    @staticmethod
    def _build_skeleton() -> list[dict[str, Any]]:
        """5 signal class のスケルトンを生成する。"""
        result: list[dict[str, Any]] = []
        for sig in _SIGNAL_CLASSES:
            result.append({
                "signal_id":  sig["signal_id"],
                "sor":        sig["sor"],
                "collector":  sig["collector"],
                "status":     "pending",
                "notes":      "",
            })
        return result
