# k1s0-proof: PROOF-meta-prog-007 -> IMPL-meta-0007
# k1s0-impl: IMPL-meta-0007 realizes=FR-meta-007
"""tools/lock_yaml_generator/generate_artifact_inventory.py

artifact_inventory.lock.yaml 生成器。
src/security/cosign/signed_artifacts.yaml を読み込み、artifacts リストを返す。
存在しない場合は空 artifacts + total_signed=0 を返す。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# signed_artifacts.yaml の想定パス
_SIGNED_ARTIFACTS_YAML = REPO_ROOT / "src/security/cosign/signed_artifacts.yaml"


class ArtifactInventoryGenerator(BaseGenerator):
    """artifact_inventory.lock.yaml 生成器。"""

    OUTPUT_NAME = "artifact_inventory.lock.yaml"
    REQUIRED_INPUTS: list[str] = []
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/security/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/security/cosign/signed_artifacts.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _SIGNED_ARTIFACTS_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_SIGNED_ARTIFACTS_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """artifacts リストを正規化して artifact dict を返す。
        inputs が空の場合は空 artifacts + total_signed=0 を返す。
        """
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        raw_artifacts: list[dict[str, Any]] = inputs.get("artifacts", [])
        artifacts = self._normalize_artifacts(raw_artifacts)

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_artifact_inventory.py"
            ),
            "total_signed":  len(artifacts),
            "generated_at":  generated_at,
            "artifacts":     artifacts,
        }

    @staticmethod
    def _normalize_artifacts(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """artifact エントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            result.append({
                "artifact_id":     str(entry.get("artifact_id", "")),
                "artifact_type":   str(entry.get("artifact_type", "")),
                "digest":          str(entry.get("digest", "")),
                "cosign_verified": bool(entry.get("cosign_verified", False)),
                "slsa_level":      str(entry.get("slsa_level", "")),
            })
        return result
