# k1s0-proof: PROOF-meta-prog-001 -> IMPL-meta-0001
# k1s0-impl: IMPL-meta-0001 realizes=FR-meta-001
"""tools/lock_yaml_generator/generate_axis_registry.py

axis_registry.lock.yaml 生成器。
19 軸の登録情報を src/_meta/axis_registry/registry.yaml から読み込み、
正規化して出力する。registry.yaml が存在しない場合はハードコードした
19 軸スケルトンを返す。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# 19 軸スケルトン（registry.yaml が存在しない場合のフォールバック）
def _ax(axis_id: str, axis_name: str, kind: str, cap_slot: int) -> dict[str, Any]:
    """軸スケルトンエントリを生成する（必須フィールドを全て含む）。"""
    return {
        "axis_id": axis_id,
        "axis_name": axis_name,
        "kind": kind,
        "conformance_specs": [],
        "lock_artifacts": [],
        "defense_in_depth_layers": [],
        "cap_slot": cap_slot,
    }


_FALLBACK_AXES: list[dict[str, Any]] = [
    _ax("01", "tier1",       "primary_layer",        1),
    _ax("02", "tier2",       "primary_layer",        2),
    _ax("03", "tier3",       "primary_layer",        3),
    _ax("04", "infra",       "primary_layer",        4),
    _ax("05", "data",        "primary_layer",        5),
    _ax("06", "security",    "primary_layer",        6),
    _ax("07", "ops",         "primary_layer",        7),
    _ax("08", "client",      "primary_layer",        8),
    _ax("09", "test",        "primary_layer",        9),
    _ax("10", "formal",      "primary_layer",        10),
    _ax("11", "cross_http2", "cross_cutting_cluster", 11),
    _ax("12", "cross_kek",   "cross_cutting_cluster", 12),
    _ax("13", "cross_schema","cross_cutting_cluster", 13),
    _ax("14", "cross_fsm",   "cross_cutting_cluster", 14),
    _ax("15", "cross_slo",   "cross_cutting_cluster", 15),
    _ax("16", "cross_bff",   "cross_cutting_cluster", 16),
    _ax("17", "cross_pii",   "cross_cutting_cluster", 17),
    _ax("18", "cross_edge",  "cross_cutting_cluster", 18),
    _ax("19", "meta",        "meta",                 19),
]

_REGISTRY_YAML = REPO_ROOT / "src/_meta/axis_registry/registry.yaml"


class AxisRegistryGenerator(BaseGenerator):
    """axis_registry.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "axis_registry.lock.yaml"
    # 依存する入力 lock（なし）
    REQUIRED_INPUTS: list[str] = []
    # JSON スキーマパス
    SCHEMA_PATH: Path | None = (
        REPO_ROOT / "tools/lock_yaml_generator/schemas/axis_registry.schema.yaml"
    )
    # REPO_ROOT からの相対パス
    DEFAULT_OUTPUT_DIR = "src/_meta/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/_meta/axis_registry/registry.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        if _REGISTRY_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_REGISTRY_YAML.read_text(encoding="utf-8"))
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """19 軸を正規化して artifact dict を構築する。
        inputs に axes が揃っていない場合はフォールバックスケルトンを使用する。
        """
        # inputs から axes リストを取得
        raw_axes: list[dict[str, Any]] = inputs.get("axes", [])

        # 19 entry が揃っているか検証
        if len(raw_axes) >= 19:
            axes = self._normalize_axes(raw_axes)
        else:
            # 足りなければフォールバック
            axes = list(_FALLBACK_AXES)

        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by tools/lock_yaml_generator/generate_axis_registry.py"
            ),
            "axes_count": len(axes),
            "cap_slot_max": 20,
            "cap_slot_remaining": 20 - len(axes),
            "generated_at": generated_at,
            "axes": axes,
        }

    @staticmethod
    def _normalize_axes(raw_axes: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """axes エントリを正規化し、必須フィールドを補完する。"""
        normalized: list[dict[str, Any]] = []
        for entry in raw_axes:
            normalized.append({
                "axis_id":   str(entry.get("axis_id", "")).zfill(2),
                "axis_name": str(entry.get("axis_name", "")),
                "kind":      str(entry.get("kind", "primary_layer")),
                "cap_slot":  int(entry.get("cap_slot", 0)),
            })
        return normalized
