# k1s0-proof: PROOF-formal-prog-003 -> IMPL-formal-0003
# k1s0-impl: IMPL-formal-0003 realizes=FR-formal-003
"""tools/lock_yaml_generator/generate_proof_review.py

proof_review.lock.yaml 生成器。
proof_status.lock.yaml と src/formal/dual_review/ 配下の
*.dual_review.lock.yaml を読み込み、v1_baseline_verified な obligation に
dual_review が存在するか確認して reviews リストを返す。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# dual_review ファイルが格納されるディレクトリ
_DUAL_REVIEW_DIR = REPO_ROOT / "src/formal/dual_review"


class ProofReviewGenerator(BaseGenerator):
    """proof_review.lock.yaml 生成器。"""

    OUTPUT_NAME = "proof_review.lock.yaml"
    REQUIRED_INPUTS: list[str] = ["proof_status.lock.yaml"]
    SCHEMA_PATH: Path | None = None
    DEFAULT_OUTPUT_DIR = "src/formal/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """proof_status.lock.yaml と dual_review ファイルを読み込む。"""
        import yaml  # type: ignore

        # proof_status.lock.yaml を読む
        proof_status = self.load_lock(lock_dir, "proof_status.lock.yaml")

        # src/formal/dual_review/ 配下の *.dual_review.lock.yaml を収集
        dual_reviews: list[dict[str, Any]] = []
        if _DUAL_REVIEW_DIR.exists():
            for review_file in sorted(_DUAL_REVIEW_DIR.glob("*.dual_review.lock.yaml")):
                raw = yaml.safe_load(review_file.read_text(encoding="utf-8")) or {}
                raw["_source_file"] = review_file.name
                dual_reviews.append(raw)

        return {
            "proof_status": proof_status,
            "dual_reviews": dual_reviews,
        }

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """verified な obligation に対して dual_review の有無を確認し reviews リストを返す。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        proof_status: dict[str, Any] = inputs.get("proof_status", {})
        dual_reviews: list[dict[str, Any]] = inputs.get("dual_reviews", [])

        # dual_review のインデックスを obligation_id で構築
        review_index: dict[str, dict[str, Any]] = {}
        for dr in dual_reviews:
            ob_id = str(dr.get("obligation_id", ""))
            if ob_id:
                review_index[ob_id] = dr

        # v1_baseline_verified な cell を抽出し、dual_review 有無を確認
        cells: list[dict[str, Any]] = proof_status.get("cells", [])
        reviews: list[dict[str, Any]] = []

        for cell in cells:
            if cell.get("cell_state") == "v1_baseline_verified":
                ob_id = str(cell.get("obligation_id", ""))
                has_review = ob_id in review_index
                reviews.append({
                    "obligation_id":  ob_id,
                    "axis_name":      str(cell.get("axis_name", "")),
                    "has_dual_review": has_review,
                    "review_file":    review_index[ob_id].get("_source_file", "") if has_review else "",
                })

        # dual_review 未完了数
        missing_review_count = sum(1 for r in reviews if not r["has_dual_review"])

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_proof_review.py"
            ),
            "verified_obligations_count": len(reviews),
            "missing_review_count":       missing_review_count,
            "generated_at":               generated_at,
            "reviews":                    reviews,
        }
