"""tools/lock_yaml_generator/generate_forbidden_export_symbols.py

forbidden_export_symbols.lock.yaml 生成器。
src/tier3/forbidden_symbols_input.yaml を読み込み、
status='banned' のシンボルカタログを集約した lock artifact を生成する。
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# 入力 SoT yaml のパス
_FORBIDDEN_SYMBOLS_YAML = REPO_ROOT / "src/tier3/forbidden_symbols_input.yaml"


class ForbiddenExportSymbolsGenerator(BaseGenerator):
    """forbidden_export_symbols.lock.yaml 生成器。

    tier3 強制機構の禁止 export symbol カタログを lock artifact に変換する。
    """

    # 出力ファイル名
    OUTPUT_NAME = "forbidden_export_symbols.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/tier3/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/tier3/forbidden_symbols_input.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # 入力 SoT yaml が存在する場合は読み込む
        if _FORBIDDEN_SYMBOLS_YAML.exists():
            import yaml  # type: ignore
            raw = yaml.safe_load(_FORBIDDEN_SYMBOLS_YAML.read_text(encoding="utf-8"))
            # dict でない場合は空 dict を返す
            return raw if isinstance(raw, dict) else {}
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """禁止 export symbol カタログを生成して artifact dict を返す。"""
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # inputs から symbols リストを取得する
        raw_symbols: list[dict[str, Any]] = inputs.get("symbols", [])

        # banned ステータスの symbol を集約する
        symbols = self._normalize_symbols(raw_symbols)

        # banned 件数を集計する
        banned_count = sum(1 for s in symbols if s.get("status") == "banned")

        return {
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_forbidden_export_symbols.py"
            ),
            # 適合仕様 SoT リファレンス
            "spec_ref": inputs.get(
                "spec_ref",
                "docs/04_詳細設計/01_適合仕様/11_クライアント状態適合仕様.md",
            ),
            # 強制機構 SoT リファレンス
            "enforcement_ref": inputs.get(
                "enforcement_ref",
                "docs/04_詳細設計/02_強制機構/03_tier3強制機構.md",
            ),
            # 生成日時
            "generated_at": generated_at,
            # 禁止シンボル総数
            "total_symbols": len(symbols),
            # banned ステータス件数
            "banned_count": banned_count,
            # 禁止シンボルカタログ
            "symbols": symbols,
        }

    @staticmethod
    def _normalize_symbols(raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """禁止シンボルエントリを正規化する。"""
        result: list[dict[str, Any]] = []
        for entry in raw:
            # 各フィールドを文字列に正規化する
            result.append({
                "symbol_id":         str(entry.get("symbol_id", "")),
                "pattern":           str(entry.get("pattern", "")),
                "reason":            str(entry.get("reason", "")),
                "scope":             str(entry.get("scope", "")),
                "enforcement_layer": int(entry.get("enforcement_layer", 0)),
                "status":            str(entry.get("status", "unknown")),
            })
        return result
