"""tools/lock_yaml_generator/generate_capability_matrix.py

# capability_matrix.lock.yaml 生成器。
# src/client/classes.yaml を読み込み、SDK 機能マトリクスの
# 宣言状態を lock artifact として生成する。
# classes.yaml が存在しない場合は total_classes=5 のスケルトンを使用する。
"""

# 標準ライブラリのインポート
from __future__ import annotations

# datetime モジュール: generated_at タイムスタンプ生成に使用
import datetime
# Path: ファイルパス操作に使用
from pathlib import Path
# Any: 型ヒントに使用
from typing import Any

# BaseGenerator と REPO_ROOT をインポートする
from tools.lock_yaml_generator.base_generator import BaseGenerator, REPO_ROOT

# classes.yaml の想定パス（sdk_inventory と共有）
_CLASSES_YAML = REPO_ROOT / "src/client/classes.yaml"


class CapabilityMatrixGenerator(BaseGenerator):
    """capability_matrix.lock.yaml 生成器。"""

    # 出力ファイル名
    OUTPUT_NAME = "capability_matrix.lock.yaml"
    # 必須入力なし（フォールバックあり）
    REQUIRED_INPUTS: list[str] = []
    # スキーマ検証なし
    SCHEMA_PATH: Path | None = None
    # 出力先ディレクトリ
    DEFAULT_OUTPUT_DIR = "src/client/lock"

    def load_inputs(self, lock_dir: Path) -> dict[str, Any]:
        """src/client/classes.yaml を読み込む。
        存在しない場合は空 dict を返す。
        """
        # ファイルが存在する場合のみ読み込む
        if _CLASSES_YAML.exists():
            # PyYAML を使って YAML を読み込む
            import yaml  # type: ignore
            # テキストを読み込んで YAML パースする
            raw = yaml.safe_load(_CLASSES_YAML.read_text(encoding="utf-8"))
            # dict であれば返す、そうでなければ空 dict を返す
            return raw if isinstance(raw, dict) else {}
        # ファイルが存在しない場合は空 dict を返す
        return {}

    def build_artifact(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """SDK 機能マトリクスの宣言状態を表す artifact dict を返す。
        inputs が空の場合はフォールバック（total_classes=5）を使用する。
        """
        # 現在時刻を UTC で生成する
        generated_at = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

        # classes キーからクラス一覧を取得する（複数のキー名に対応）
        raw_classes: list[dict[str, Any]] = (
            inputs.get("classes") or
            inputs.get("sdk_classes") or
            []
        )

        # クラス数を決定する（入力がある場合はその数、なければデフォルト 5）
        total_classes = len(raw_classes) if raw_classes else 5

        # artifact dict を構築して返す
        return {
            # 自動生成ヘッダ（手書き禁止の明示）
            "_AUTO_GENERATED": (
                "DO NOT EDIT. Generated by"
                " tools/lock_yaml_generator/generate_capability_matrix.py"
            ),
            # 生成日時
            "generated_at": generated_at,
            # 機能マトリクスのステータス（物理マトリクス検証は Stage 5 で実施）
            "capability_status": "declared",
            # クラス数（5 class 固定または入力から算出）
            "total_classes": total_classes,
        }
