# infra/kong/kong.dev.yaml
# ローカル開発用 Kong Declarative Config (DB-less mode)
#
# 本番環境では kong.yaml を decK で管理し、Redis バックエンドの rate-limiting や
# JWT プラグインを有効にするが、ローカル開発環境では以下の点が異なる:
#   - サービス URL は docker-compose サービス名で参照
#   - rate-limiting は local policy（Redis 不要）
#   - JWT プラグインは有効（Keycloak JWKS 連携、ヘルスチェックエンドポイントは除外）
#   - CORS は localhost:3000 を許可

_format_version: "3.0"

services:
  # ============================================================
  # Auth Service
  # ============================================================
  - name: auth-v1
    url: http://auth-rust:8080
    routes:
      - name: auth-token-route
        paths:
          - /api/v1/auth
        strip_path: false
      - name: auth-users-route
        paths:
          - /api/v1/users
        strip_path: false
      - name: auth-audit-route
        paths:
          - /api/v1/audit
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local
      - name: request-size-limiting
        config:
          allowed_payload_size: 10

  # ============================================================
  # Config Service
  # ============================================================
  - name: config-v1
    url: http://config-rust:8080
    routes:
      - name: config-route
        paths:
          - /api/v1/config
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 2000
          policy: local

  # ============================================================
  # Saga Service
  # ============================================================
  - name: saga-v1
    url: http://saga-rust:8080
    routes:
      - name: saga-route
        paths:
          - /api/v1/sagas
        strip_path: false
      - name: saga-workflow-route
        paths:
          - /api/v1/workflows
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local

  # ============================================================
  # DLQ Manager Service
  # ============================================================
  - name: dlq-manager-v1
    url: http://dlq-manager-rust:8080
    routes:
      - name: dlq-route
        paths:
          - /api/v1/dlq
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local

  # ============================================================
  # Master Service
  # ============================================================
  - name: master-v1
    url: http://master-rust:8080
    routes:
      - name: master-route
        paths:
          - /api/v1/master
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 2000
          policy: local

  # ============================================================
  # Accounting Ledger Service (business Tier)
  # ============================================================
  - name: accounting-ledger-v1
    url: http://ledger-rust:8080
    routes:
      - name: ledger-route
        paths:
          - /api/v1/accounting/ledger
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local

  # ============================================================
  # Accounts Service (business Tier)
  # ============================================================
  - name: accounts-v1
    url: http://accounts-rust:8080
    routes:
      - name: accounts-route
        paths:
          - /api/v1/accounts
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local

  # ============================================================
  # Order Service (service Tier)
  # ============================================================
  - name: order-v1
    url: http://order-rust:8080
    routes:
      - name: order-route
        paths:
          - /api/v1/orders
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local

  # ============================================================
  # Dashboard Service (service Tier)
  # ============================================================
  - name: dashboard-v1
    url: http://dashboard-rust:8080
    routes:
      - name: dashboard-route
        paths:
          - /api/v1/dashboard
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          policy: local

  # ============================================================
  # Health Endpoints (no auth required)
  # ============================================================
  - name: auth-health
    url: http://auth-rust:8080
    routes:
      - name: auth-health-check
        paths:
          - /healthz
          - /readyz
        strip_path: false
        plugins:
          - name: jwt
            enabled: false

  - name: config-health
    url: http://config-rust:8080
    routes:
      - name: config-health-check
        paths:
          - /config/healthz
          - /config/readyz
        strip_path: false
        plugins:
          - name: jwt
            enabled: false

  - name: saga-health
    url: http://saga-rust:8080
    routes:
      - name: saga-health-check
        paths:
          - /saga/healthz
          - /saga/readyz
        strip_path: false
        plugins:
          - name: jwt
            enabled: false

  - name: dlq-manager-health
    url: http://dlq-manager-rust:8080
    routes:
      - name: dlq-manager-health-check
        paths:
          - /dlq/healthz
          - /dlq/readyz
        strip_path: false
        plugins:
          - name: jwt
            enabled: false

# ============================================================
# Global Plugins
# ============================================================
plugins:
  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "http://localhost:5173"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Authorization
        - Content-Type
        - X-Request-ID
      exposed_headers:
        - X-RateLimit-Limit
        - X-RateLimit-Remaining
        - X-RateLimit-Reset
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 5000
      policy: local
      fault_tolerant: true
      hide_client_headers: false

  # JWT Plugin - Keycloak JWKS 連携（ローカル開発用）
  # 本番では infra/kong/plugins/auth.yaml で管理
  - name: jwt
    config:
      uri_param_names: []
      cookie_names: []
      key_claim_name: kid
      claims_to_verify:
        - exp
      maximum_expiration: 900           # 15分（Access Token のライフタイム）
      header_names:
        - Authorization

  # Post Function - JWT Claims をバックエンドへのリクエストヘッダーに転送
  - name: post-function
    config:
      header_filter:
        - |
          local jwt = kong.ctx.shared.authenticated_jwt_token
          if jwt then
            kong.service.request.set_header("X-User-Id", jwt.claims.sub)
            local roles = ""
            local ra = jwt.claims.realm_access
            if ra and ra.roles then
              roles = table.concat(ra.roles, ",")
            end
            kong.service.request.set_header("X-User-Roles", roles)
            kong.service.request.set_header("X-User-Email", jwt.claims.email or "")
          end

  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true

# ============================================================
# Consumers - Keycloak JWKS 連携
# ============================================================
consumers:
  - username: keycloak
    jwt_secrets:
      - algorithm: RS256
        key: "http://keycloak:8080/realms/k1s0"
        # ローカル開発では Keycloak の内部URL を使用
        # JWKS URL: http://keycloak:8080/realms/k1s0/protocol/openid-connect/certs
