_format_version: "3.0"

services:
  # system Tier
  - name: auth-v1
    url: http://auth-server.k1s0-system.svc.cluster.local:80
    routes:
      - name: auth-v1-route
        paths:
          - /api/v1/auth
        strip_path: false
      - name: auth-v1-login
        paths:
          - /api/v1/auth/login
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 30                  # ブルートフォース防止（API設計.md 参照）
              policy: redis
              redis_host: redis.k1s0-system.svc.cluster.local

  # business Tier
  - name: accounting-ledger-v1
    url: http://ledger-server.k1s0-business.svc.cluster.local:80
    routes:
      - name: ledger-v1-route
        paths:
          - /api/v1/accounting/ledger
        strip_path: false

  # service Tier
  - name: order-v1
    url: http://order-server.k1s0-service.svc.cluster.local:80
    routes:
      - name: order-v1-route
        paths:
          - /api/v1/orders
        strip_path: false

plugins:
  # グローバルプラグイン
  - name: rate-limiting
    config:
      minute: 500                    # デフォルト（service Tier）
      second: 20                     # 秒あたりの上限（バースト制御）
      policy: redis                  # Redis で共有状態を管理
      redis_host: redis.k1s0-system.svc.cluster.local
      redis_port: 6379
      redis_database: 1
      fault_tolerant: true           # Redis 障害時は制限なしで通過
      hide_client_headers: false     # X-RateLimit-* ヘッダーを返却

  - name: jwt
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
      maximum_expiration: 900           # 15分（Access Token のライフタイム）
      header_names:
        - Authorization

  - name: cors
    config:
      origins:
        - "https://*.k1s0.internal.example.com"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Authorization
        - Content-Type
        - X-Request-ID
      exposed_headers:
        - X-RateLimit-Limit
        - X-RateLimit-Remaining
        - X-RateLimit-Reset
      credentials: true
      max_age: 3600

  - name: post-function
    config:
      header_filter:
        - |
          local jwt = kong.ctx.shared.authenticated_jwt_token
          if jwt then
            kong.service.request.set_header("X-User-Id", jwt.claims.sub)
            kong.service.request.set_header("X-User-Roles", table.concat(jwt.claims.realm_access.roles, ","))
            kong.service.request.set_header("X-User-Email", jwt.claims.email or "")
          end

  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
