apiVersion: v1
kind: Service
metadata:
  name: envoy-grpcweb
  namespace: k1s0-tier1
spec:
  type: ClusterIP
  selector:
    app: envoy-grpcweb
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
