// 本ファイルは tier1 公開 Secrets API の正式 proto。
// OpenBao 経由でテナントスコープのシークレットを取得・ローテーションする。
//
// 設計正典:
//   docs/03_要件定義/20_機能要件/40_tier1_API契約IDL/04_Secrets_API.md
//   docs/03_要件定義/20_機能要件/10_tier1_API要件/04_Secrets_API.md
//
// 関連要件: FR-T1-SECRETS-001〜004
// proto 構文宣言（proto3）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: k1s0/tier1/secrets/v1/secrets_service.proto

// パッケージ命名規約: k1s0.tier1.<api>.v<n>

package secretsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsService_Get_FullMethodName        = "/k1s0.tier1.secrets.v1.SecretsService/Get"
	SecretsService_BulkGet_FullMethodName    = "/k1s0.tier1.secrets.v1.SecretsService/BulkGet"
	SecretsService_GetDynamic_FullMethodName = "/k1s0.tier1.secrets.v1.SecretsService/GetDynamic"
	SecretsService_Rotate_FullMethodName     = "/k1s0.tier1.secrets.v1.SecretsService/Rotate"
	SecretsService_Encrypt_FullMethodName    = "/k1s0.tier1.secrets.v1.SecretsService/Encrypt"
	SecretsService_Decrypt_FullMethodName    = "/k1s0.tier1.secrets.v1.SecretsService/Decrypt"
	SecretsService_RotateKey_FullMethodName  = "/k1s0.tier1.secrets.v1.SecretsService/RotateKey"
)

// SecretsServiceClient is the client API for SecretsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Secrets API。OpenBao をバックエンドとし、tier1 が PII / アクセス制御を強制する。
type SecretsServiceClient interface {
	// 単一シークレット取得（テナント越境参照は即 PermissionDenied、FR-T1-SECRETS-001）
	Get(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// 一括取得（テナントに割当された全シークレット）
	BulkGet(ctx context.Context, in *BulkGetSecretRequest, opts ...grpc.CallOption) (*BulkGetSecretResponse, error)
	// 動的シークレット発行（FR-T1-SECRETS-002）。
	// engine="postgres" 等の Database Engine から TTL 付き credential を都度発行する。
	// TTL 経過後は OpenBao が backend ユーザを自動失効（drop）させる。
	GetDynamic(ctx context.Context, in *GetDynamicSecretRequest, opts ...grpc.CallOption) (*GetDynamicSecretResponse, error)
	// ローテーション実行（FR-T1-SECRETS-004）
	// 成功時は new_version を返し、旧バージョンは grace_period_sec まで Get 可能。
	// 失敗時は K1s0Error を返し OpenBao 側は不変（トランザクショナル）。
	Rotate(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error)
	// Transit 暗号化（FR-T1-SECRETS-003）。AES-256-GCM 固定。
	// 鍵名は tier1 が <tenant_id>.<key_label> で自動 prefix する。
	// 鍵バージョンは ciphertext に埋め込まれ、Decrypt 時に自動的に正しい版で復号される。
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	// Transit 復号（FR-T1-SECRETS-003）。
	// ciphertext から鍵バージョンを取り出し、対応する鍵で復号する。
	// ローテーション後の旧版 ciphertext も自動で復号できる。
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	// Transit 鍵ローテーション（FR-T1-SECRETS-003 受け入れ基準「鍵バージョン管理が自動」）。
	// 新バージョン鍵を生成して current にする。以降の Encrypt は新版で行うが、
	// 旧版 ciphertext は引き続き Decrypt 可能（旧版鍵を保持）。
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error)
}

type secretsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsServiceClient(cc grpc.ClientConnInterface) SecretsServiceClient {
	return &secretsServiceClient{cc}
}

func (c *secretsServiceClient) Get(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) BulkGet(ctx context.Context, in *BulkGetSecretRequest, opts ...grpc.CallOption) (*BulkGetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkGetSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_BulkGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetDynamic(ctx context.Context, in *GetDynamicSecretRequest, opts ...grpc.CallOption) (*GetDynamicSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDynamicSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) Rotate(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_Rotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, SecretsService_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, SecretsService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeyResponse)
	err := c.cc.Invoke(ctx, SecretsService_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsServiceServer is the server API for SecretsService service.
// All implementations should embed UnimplementedSecretsServiceServer
// for forward compatibility.
//
// Secrets API。OpenBao をバックエンドとし、tier1 が PII / アクセス制御を強制する。
type SecretsServiceServer interface {
	// 単一シークレット取得（テナント越境参照は即 PermissionDenied、FR-T1-SECRETS-001）
	Get(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// 一括取得（テナントに割当された全シークレット）
	BulkGet(context.Context, *BulkGetSecretRequest) (*BulkGetSecretResponse, error)
	// 動的シークレット発行（FR-T1-SECRETS-002）。
	// engine="postgres" 等の Database Engine から TTL 付き credential を都度発行する。
	// TTL 経過後は OpenBao が backend ユーザを自動失効（drop）させる。
	GetDynamic(context.Context, *GetDynamicSecretRequest) (*GetDynamicSecretResponse, error)
	// ローテーション実行（FR-T1-SECRETS-004）
	// 成功時は new_version を返し、旧バージョンは grace_period_sec まで Get 可能。
	// 失敗時は K1s0Error を返し OpenBao 側は不変（トランザクショナル）。
	Rotate(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error)
	// Transit 暗号化（FR-T1-SECRETS-003）。AES-256-GCM 固定。
	// 鍵名は tier1 が <tenant_id>.<key_label> で自動 prefix する。
	// 鍵バージョンは ciphertext に埋め込まれ、Decrypt 時に自動的に正しい版で復号される。
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	// Transit 復号（FR-T1-SECRETS-003）。
	// ciphertext から鍵バージョンを取り出し、対応する鍵で復号する。
	// ローテーション後の旧版 ciphertext も自動で復号できる。
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	// Transit 鍵ローテーション（FR-T1-SECRETS-003 受け入れ基準「鍵バージョン管理が自動」）。
	// 新バージョン鍵を生成して current にする。以降の Encrypt は新版で行うが、
	// 旧版 ciphertext は引き続き Decrypt 可能（旧版鍵を保持）。
	RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error)
}

// UnimplementedSecretsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsServiceServer struct{}

func (UnimplementedSecretsServiceServer) Get(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSecretsServiceServer) BulkGet(context.Context, *BulkGetSecretRequest) (*BulkGetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkGet not implemented")
}
func (UnimplementedSecretsServiceServer) GetDynamic(context.Context, *GetDynamicSecretRequest) (*GetDynamicSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDynamic not implemented")
}
func (UnimplementedSecretsServiceServer) Rotate(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rotate not implemented")
}
func (UnimplementedSecretsServiceServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedSecretsServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedSecretsServiceServer) RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedSecretsServiceServer) testEmbeddedByValue() {}

// UnsafeSecretsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsServiceServer will
// result in compilation errors.
type UnsafeSecretsServiceServer interface {
	mustEmbedUnimplementedSecretsServiceServer()
}

func RegisterSecretsServiceServer(s grpc.ServiceRegistrar, srv SecretsServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecretsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsService_ServiceDesc, srv)
}

func _SecretsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).Get(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_BulkGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkGetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).BulkGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_BulkGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).BulkGet(ctx, req.(*BulkGetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDynamicSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetDynamic(ctx, req.(*GetDynamicSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_Rotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).Rotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_Rotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).Rotate(ctx, req.(*RotateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsService_ServiceDesc is the grpc.ServiceDesc for SecretsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k1s0.tier1.secrets.v1.SecretsService",
	HandlerType: (*SecretsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SecretsService_Get_Handler,
		},
		{
			MethodName: "BulkGet",
			Handler:    _SecretsService_BulkGet_Handler,
		},
		{
			MethodName: "GetDynamic",
			Handler:    _SecretsService_GetDynamic_Handler,
		},
		{
			MethodName: "Rotate",
			Handler:    _SecretsService_Rotate_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _SecretsService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _SecretsService_Decrypt_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _SecretsService_RotateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k1s0/tier1/secrets/v1/secrets_service.proto",
}
