"""tools/impl_substance_check/cli.py

python -m tools.impl_substance_check で呼ばれるエントリポイント。
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install PyYAML", file=sys.stderr)
    sys.exit(1)

from tools.impl_substance_check.scanner import scan_all


def _auto_repo_root() -> Path:
    """このファイルの位置から REPO_ROOT を推定する。"""
    # tools/impl_substance_check/cli.py → 2 階層上が REPO_ROOT
    return Path(__file__).parent.parent.parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="src/ の実装実体を集計して impl_substance.lock.yaml を生成する。"
    )
    parser.add_argument(
        "--repo-root", type=Path,
        default=None,
        help="リポジトリルートのパス（省略時は自動推定）",
    )
    parser.add_argument(
        "--out", type=Path,
        default=Path("src/_meta/lock/impl_substance.lock.yaml"),
        help="出力ファイルパス（リポジトリルートからの相対パス）",
    )
    parser.add_argument(
        "--facade-paths", type=Path,
        default=Path("src/_meta/lint/facade_paths.yaml"),
        help="facade_paths.yaml のパス（リポジトリルートからの相対パス）",
    )
    args = parser.parse_args(argv)

    repo_root = args.repo_root or _auto_repo_root()
    facade_file = repo_root / args.facade_paths
    out_path = repo_root / args.out

    data = scan_all(repo_root, facade_file if facade_file.exists() else None)

    artifact = {
        "_AUTO_GENERATED": "DO NOT EDIT. Generated by tools/impl_substance_check/cli.py",
        "schema_version": "v1",
        "generated_at": datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        **data,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        yaml.dump(artifact, allow_unicode=True, default_flow_style=False, sort_keys=False),
        encoding="utf-8",
    )
    print(f"Generated: {out_path}")

    # 簡易サマリを表示
    summary = data["summary"]
    print("--- LOC summary ---")
    for key, val in summary.items():
        print(f"  {key}: {val}")
    print(f"readme_only_count: {data['readme_only_count']}")
    print(f"  dirs: {data['readme_only_dirs']}")
    print(f"facade_below_floor_count: {data['facade_below_floor_count']}")
    for f in data["facade_files"]:
        mark = "OK" if f.get("meets_floor") else "BELOW_FLOOR"
        print(f"  [{mark}] {f['path']} ({f['loc']} lines / floor={f['floor']})")

    floor_violations = data.get("axis_floor_violations", [])
    print(f"axis_floor_violation_count: {data.get('axis_floor_violation_count', 0)}")
    for v in floor_violations:
        print(f"  BELOW_FLOOR  {v['axis']}: {v['loc']} LoC (floor={v['floor']}, deficit={v['deficit']})")

    print(f"yaml_only_axis_count: {data.get('yaml_only_axis_count', 0)}")
    print(f"  axes: {data.get('yaml_only_axes', [])}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
