// 本ファイルは tier1 公開 PII API の正式 proto。
// PII（個人情報）の検出（Classify）とマスキング（Mask）を提供する。
//
// 設計正典:
//   docs/03_要件定義/20_機能要件/40_tier1_API契約IDL/10_Audit_Pii_API.md（PiiService 部）
//   docs/03_要件定義/20_機能要件/10_tier1_API要件/10_Audit_Pii_API.md
//
// 関連要件: FR-T1-PII-001〜002
//
// 担当 Pod: t1-pii（Rust 純関数実装、ステートレス、DS-SW-COMP-009）
//
// 注: 正典 IDL では AuditService と PiiService を 1 ファイル（package
//     k1s0.tier1.audit.v1）にまとめているが、ディレクトリ設計と Pod 構成に従い、
//     本リポジトリでは pii.v1 パッケージに分離する。
// proto 構文宣言（proto3）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: k1s0/tier1/pii/v1/pii_service.proto

// パッケージ命名規約: k1s0.tier1.<api>.v<n>

package piiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PiiService_Classify_FullMethodName     = "/k1s0.tier1.pii.v1.PiiService/Classify"
	PiiService_Mask_FullMethodName         = "/k1s0.tier1.pii.v1.PiiService/Mask"
	PiiService_Pseudonymize_FullMethodName = "/k1s0.tier1.pii.v1.PiiService/Pseudonymize"
)

// PiiServiceClient is the client API for PiiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PII API。t1-pii Pod は純関数（ステートレス）で副作用なし。
type PiiServiceClient interface {
	// PII 種別の検出（テキスト → findings 列）
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	// マスキング（テキスト → 置換後テキスト + findings）
	Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error)
	// 仮名化（FR-T1-PII-002）。HMAC-SHA256(salt, value) を URL-safe base64 で返す。
	// 同一 salt + 同一入力で同一出力（決定論的）。salt は OpenBao 等で管理し直接露出しない。
	Pseudonymize(ctx context.Context, in *PseudonymizeRequest, opts ...grpc.CallOption) (*PseudonymizeResponse, error)
}

type piiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPiiServiceClient(cc grpc.ClientConnInterface) PiiServiceClient {
	return &piiServiceClient{cc}
}

func (c *piiServiceClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, PiiService_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piiServiceClient) Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskResponse)
	err := c.cc.Invoke(ctx, PiiService_Mask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piiServiceClient) Pseudonymize(ctx context.Context, in *PseudonymizeRequest, opts ...grpc.CallOption) (*PseudonymizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PseudonymizeResponse)
	err := c.cc.Invoke(ctx, PiiService_Pseudonymize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PiiServiceServer is the server API for PiiService service.
// All implementations should embed UnimplementedPiiServiceServer
// for forward compatibility.
//
// PII API。t1-pii Pod は純関数（ステートレス）で副作用なし。
type PiiServiceServer interface {
	// PII 種別の検出（テキスト → findings 列）
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	// マスキング（テキスト → 置換後テキスト + findings）
	Mask(context.Context, *MaskRequest) (*MaskResponse, error)
	// 仮名化（FR-T1-PII-002）。HMAC-SHA256(salt, value) を URL-safe base64 で返す。
	// 同一 salt + 同一入力で同一出力（決定論的）。salt は OpenBao 等で管理し直接露出しない。
	Pseudonymize(context.Context, *PseudonymizeRequest) (*PseudonymizeResponse, error)
}

// UnimplementedPiiServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPiiServiceServer struct{}

func (UnimplementedPiiServiceServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedPiiServiceServer) Mask(context.Context, *MaskRequest) (*MaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mask not implemented")
}
func (UnimplementedPiiServiceServer) Pseudonymize(context.Context, *PseudonymizeRequest) (*PseudonymizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pseudonymize not implemented")
}
func (UnimplementedPiiServiceServer) testEmbeddedByValue() {}

// UnsafePiiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PiiServiceServer will
// result in compilation errors.
type UnsafePiiServiceServer interface {
	mustEmbedUnimplementedPiiServiceServer()
}

func RegisterPiiServiceServer(s grpc.ServiceRegistrar, srv PiiServiceServer) {
	// If the following call pancis, it indicates UnimplementedPiiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PiiService_ServiceDesc, srv)
}

func _PiiService_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiiServiceServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiiService_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiiServiceServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiiService_Mask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiiServiceServer).Mask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiiService_Mask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiiServiceServer).Mask(ctx, req.(*MaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiiService_Pseudonymize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PseudonymizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiiServiceServer).Pseudonymize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiiService_Pseudonymize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiiServiceServer).Pseudonymize(ctx, req.(*PseudonymizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PiiService_ServiceDesc is the grpc.ServiceDesc for PiiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PiiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k1s0.tier1.pii.v1.PiiService",
	HandlerType: (*PiiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _PiiService_Classify_Handler,
		},
		{
			MethodName: "Mask",
			Handler:    _PiiService_Mask_Handler,
		},
		{
			MethodName: "Pseudonymize",
			Handler:    _PiiService_Pseudonymize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k1s0/tier1/pii/v1/pii_service.proto",
}
