# Loki stack Helm values
# Deployed via Terraform observability module

loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: ceph-block
    size: 50Gi
  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    schema_config:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      retention_period: 168h  # 7 days
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
      retention_enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

promtail:
  enabled: true
  config:
    lokiAddress: http://loki:3100/loki/api/v1/push
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
