mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 5s
      send_batch_size: 512
      send_batch_max_size: 1024
    tail_sampling:
      decision_wait: 10s
      num_traces: 100
      policies:
        - name: errors-policy
          type: status_code
          status_code:
            status_codes:
              - ERROR
        - name: slow-traces-policy
          type: latency
          latency:
            threshold_ms: 1000
        - name: probabilistic-policy
          type: probabilistic
          probabilistic:
            sampling_percentage: 10

  exporters:
    otlp/jaeger:
      endpoint: jaeger-collector.observability.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, tail_sampling]
        exporters: [otlp/jaeger]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/jaeger]

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
