use super::super::validate::config_schema::{validate_config_schema, CategoryYaml, ConfigSchemaYaml};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};

pub struct GeneratedTypesTarget<'a> {
    pub target: &'a str,
    pub output_dir: &'a Path,
}

#[derive(Serialize)]
struct PushConfigSchemaRequest<'a> {
    namespace_prefix: &'a str,
    categories: &'a [CategoryYaml],
}

pub fn generate_typescript_types(schema: &ConfigSchemaYaml) -> String {
    let mut out = String::new();
    out.push_str(
        "// src/config/__generated__/config-types.ts\n\
         // This file is generated by k1s0 generate config-types.\n\
         // Do not edit manually.\n\n",
    );

    out.push_str("export const ConfigKeys = {\n");
    for cat in &schema.categories {
        let cat_const = cat.id.to_uppercase();
        out.push_str(&format!("  {cat_const}: {{\n"));
        for field in &cat.fields {
            let field_const = field.key.to_uppercase();
            out.push_str(&format!("    {field_const}: '{}',\n", field.key));
        }
        out.push_str("  },\n");
    }
    out.push_str("} as const;\n\n");

    out.push_str("export type ConfigValues = {\n");
    for cat in &schema.categories {
        for field in &cat.fields {
            out.push_str(&format!(
                "  '{}.{}': {};\n",
                cat.id,
                field.key,
                typescript_type(field)
            ));
        }
    }
    out.push_str("};\n");

    out
}

pub fn generate_dart_types(schema: &ConfigSchemaYaml) -> String {
    let mut out = String::new();
    out.push_str(
        "// lib/config/__generated__/config_types.dart\n\
         // This file is generated by k1s0 generate config-types.\n\
         // Do not edit manually.\n\n",
    );

    for cat in &schema.categories {
        let cat_pascal = to_pascal_case(&cat.id);

        out.push_str(&format!("enum {cat_pascal}ConfigKey {{\n"));
        for (index, field) in cat.fields.iter().enumerate() {
            let suffix = if index + 1 == cat.fields.len() { ";" } else { "," };
            out.push_str(&format!("  {}{suffix}\n", to_camel_case(&field.key)));
        }
        out.push_str("\n  String get key => switch (this) {\n");
        for field in &cat.fields {
            let camel = to_camel_case(&field.key);
            out.push_str(&format!(
                "    {cat_pascal}ConfigKey.{camel} => '{}',\n",
                field.key
            ));
        }
        out.push_str("  };\n");
        out.push_str("}\n\n");

        for field in &cat.fields {
            if field.field_type.as_deref() == Some("enum") {
                if let Some(options) = &field.options {
                    let enum_name = to_pascal_case(&field.key);
                    let values = options
                        .iter()
                        .map(|option| to_camel_case(option))
                        .collect::<Vec<_>>()
                        .join(", ");
                    out.push_str(&format!("enum {enum_name} {{ {values} }}\n\n"));
                }
            }
        }
    }

    out
}

pub fn build_push_request(
    schema: &ConfigSchemaYaml,
    server_url: &str,
    token: &str,
) -> Result<(String, String, Vec<(String, String)>, String), Box<dyn std::error::Error>> {
    let url = format!(
        "{}/api/v1/config-schema/{}",
        server_url.trim_end_matches('/'),
        schema.service
    );
    let body = serde_json::to_string_pretty(&PushConfigSchemaRequest {
        namespace_prefix: &schema.namespace_prefix,
        categories: &schema.categories,
    })?;

    let mut headers = vec![("Content-Type".to_string(), "application/json".to_string())];
    if !token.trim().is_empty() {
        headers.push(("Authorization".to_string(), format!("Bearer {token}")));
    }

    Ok(("PUT".to_string(), url, headers, body))
}

pub fn push_config_schema(
    schema: &ConfigSchemaYaml,
    server_url: &str,
    token: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if token.trim().is_empty() {
        return Err("K1S0_TOKEN is required when push is enabled".into());
    }

    let (_, url, _, _) = build_push_request(schema, server_url, token)?;
    ureq::put(&url)
        .header("Authorization", &format!("Bearer {token}"))
        .header("Content-Type", "application/json")
        .send_json(PushConfigSchemaRequest {
            namespace_prefix: &schema.namespace_prefix,
            categories: &schema.categories,
        })?;

    Ok(())
}

pub fn load_validated_schema_from_file(
    path: &Path,
) -> Result<ConfigSchemaYaml, Box<dyn std::error::Error>> {
    let path_str = path
        .to_str()
        .ok_or("schema path must be valid UTF-8")?;
    let errors = validate_config_schema(path_str)?;
    if errors > 0 {
        return Err(format!("config schema validation failed with {errors} error(s)").into());
    }

    let content = fs::read_to_string(path)?;
    let schema: ConfigSchemaYaml = serde_yaml::from_str(&content)?;
    Ok(schema)
}

pub fn generate_typescript_types_from_file(
    path: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    let schema = load_validated_schema_from_file(Path::new(path))?;
    Ok(generate_typescript_types(&schema))
}

pub fn generate_dart_types_from_file(path: &str) -> Result<String, Box<dyn std::error::Error>> {
    let schema = load_validated_schema_from_file(Path::new(path))?;
    Ok(generate_dart_types(&schema))
}

pub fn write_typescript_types_file(
    schema: &ConfigSchemaYaml,
    output_dir: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;
    let output_path = output_dir.join("config-types.ts");
    fs::write(&output_path, generate_typescript_types(schema))?;
    Ok(output_path)
}

pub fn write_dart_types_file(
    schema: &ConfigSchemaYaml,
    output_dir: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;
    let output_path = output_dir.join("config_types.dart");
    fs::write(&output_path, generate_dart_types(schema))?;
    Ok(output_path)
}

pub fn write_generated_types_to_targets(
    schema: &ConfigSchemaYaml,
    targets: &[GeneratedTypesTarget<'_>],
) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let mut written = Vec::new();
    for spec in targets {
        let path = match spec.target {
            "typescript" => write_typescript_types_file(schema, spec.output_dir)?,
            "dart" => write_dart_types_file(schema, spec.output_dir)?,
            other => return Err(format!("unsupported target: {other}").into()),
        };
        written.push(path);
    }
    Ok(written)
}

pub fn write_generated_types_to_targets_from_file(
    schema_path: &Path,
    targets: &[GeneratedTypesTarget<'_>],
) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let schema = load_validated_schema_from_file(schema_path)?;
    write_generated_types_to_targets(&schema, targets)
}

pub fn write_generated_types_from_file(
    schema_path: &Path,
    output_dir: &Path,
    targets: &[&str],
) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let target_specs = targets
        .iter()
        .map(|target| GeneratedTypesTarget {
            target,
            output_dir,
        })
        .collect::<Vec<_>>();
    write_generated_types_to_targets_from_file(schema_path, &target_specs)
}

fn typescript_type(field: &super::super::validate::config_schema::FieldYaml) -> String {
    match field.field_type.as_deref().unwrap_or("string") {
        "string" => "string".to_string(),
        "integer" | "float" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "enum" => field
            .options
            .as_ref()
            .map(|options| {
                options
                    .iter()
                    .map(|option| format!("\"{option}\""))
                    .collect::<Vec<_>>()
                    .join(" | ")
            })
            .unwrap_or_else(|| "string".to_string()),
        "object" => "Record<string, unknown>".to_string(),
        "array" => "unknown[]".to_string(),
        other => other.to_string(),
    }
}

fn to_pascal_case(value: &str) -> String {
    value
        .split(['_', '-'])
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut out = first.to_uppercase().collect::<String>();
                    out.push_str(chars.as_str());
                    out
                }
            }
        })
        .collect()
}

fn to_camel_case(value: &str) -> String {
    let mut segments = value.split(['_', '-']).filter(|segment| !segment.is_empty());
    let Some(first) = segments.next() else {
        return String::new();
    };

    let mut result = first.to_string();
    for segment in segments {
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            result.push_str(&first.to_uppercase().collect::<String>());
            result.push_str(chars.as_str());
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::validate::config_schema::{CategoryYaml, FieldYaml};
    use mockito::Matcher;
    use tempfile::{tempdir, NamedTempFile};

    fn sample_schema() -> ConfigSchemaYaml {
        ConfigSchemaYaml {
            version: 1,
            service: "my-service".to_string(),
            namespace_prefix: "service.myservice".to_string(),
            categories: vec![CategoryYaml {
                id: "general".to_string(),
                label: "General".to_string(),
                icon: Some("settings".to_string()),
                namespaces: vec!["service.myservice.general".to_string()],
                fields: vec![
                    FieldYaml {
                        key: "enable_feature".to_string(),
                        label: "Enable Feature".to_string(),
                        description: None,
                        field_type: Some("boolean".to_string()),
                        min: None,
                        max: None,
                        options: None,
                        pattern: None,
                        unit: None,
                        default: Some(serde_yaml::Value::Bool(false)),
                    },
                    FieldYaml {
                        key: "max_connections".to_string(),
                        label: "Max Connections".to_string(),
                        description: None,
                        field_type: Some("integer".to_string()),
                        min: Some(1.0),
                        max: Some(100.0),
                        options: None,
                        pattern: None,
                        unit: None,
                        default: Some(serde_yaml::Value::Number(serde_yaml::Number::from(10))),
                    },
                    FieldYaml {
                        key: "ssl_mode".to_string(),
                        label: "SSL Mode".to_string(),
                        description: None,
                        field_type: Some("enum".to_string()),
                        min: None,
                        max: None,
                        options: Some(vec![
                            "disable".to_string(),
                            "require".to_string(),
                            "verify-ca".to_string(),
                            "verify-full".to_string(),
                        ]),
                        pattern: None,
                        unit: None,
                        default: Some(serde_yaml::Value::String("require".to_string())),
                    },
                ],
            }],
        }
    }

    fn write_schema_file(content: &str) -> NamedTempFile {
        use std::io::Write;

        let mut file = NamedTempFile::new().unwrap();
        file.write_all(content.as_bytes()).unwrap();
        file
    }

    #[test]
    fn test_generate_typescript_types() {
        let schema = sample_schema();
        let ts = generate_typescript_types(&schema);

        assert!(ts.contains("export const ConfigKeys"));
        assert!(ts.contains("GENERAL: {"));
        assert!(ts.contains("ENABLE_FEATURE: 'enable_feature'"));
        assert!(ts.contains("'general.enable_feature': boolean"));
        assert!(ts.contains("'general.max_connections': number"));
        assert!(ts.contains("\"verify-ca\" | \"verify-full\""));
    }

    #[test]
    fn test_generate_dart_types() {
        let schema = sample_schema();
        let dart = generate_dart_types(&schema);

        assert!(dart.contains("enum GeneralConfigKey {"));
        assert!(dart.contains("  enableFeature,"));
        assert!(dart.contains("  maxConnections,"));
        assert!(dart.contains("  sslMode;"));
        assert!(dart.contains("GeneralConfigKey.enableFeature => 'enable_feature'"));
        assert!(dart.contains("GeneralConfigKey.sslMode => 'ssl_mode'"));
        assert!(dart.contains("enum SslMode { disable, require, verifyCa, verifyFull }"));
    }

    #[test]
    fn test_build_push_request() {
        let schema = sample_schema();
        let (method, url, headers, body) =
            build_push_request(&schema, "https://config.example.com", "test-token").unwrap();

        assert_eq!(method, "PUT");
        assert_eq!(
            url,
            "https://config.example.com/api/v1/config-schema/my-service"
        );
        assert!(headers.iter().any(|(key, value)| {
            key == "Authorization" && value == "Bearer test-token"
        }));
        assert!(headers.iter().any(|(key, value)| {
            key == "Content-Type" && value == "application/json"
        }));

        let body_json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(body_json["namespace_prefix"], "service.myservice");
        assert!(body_json.get("service").is_none());
        assert_eq!(body_json["categories"][0]["fields"][2]["type"], "enum");
    }

    #[test]
    fn test_push_config_schema() {
        let schema = sample_schema();
        let mut server = mockito::Server::new();
        let mock = server
            .mock("PUT", "/api/v1/config-schema/my-service")
            .match_header("authorization", "Bearer test-token")
            .match_header("content-type", "application/json")
            .match_body(Matcher::PartialJson(serde_json::json!({
                "namespace_prefix": "service.myservice",
                "categories": [{
                    "id": "general"
                }]
            })))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                serde_json::json!({
                    "service": "my-service",
                    "namespace_prefix": "service.myservice",
                    "categories": []
                })
                .to_string(),
            )
            .create();

        push_config_schema(&schema, &server.url(), "test-token").unwrap();
        mock.assert();
    }

    #[test]
    fn test_write_generated_types_to_targets_from_file() {
        let schema_file = write_schema_file(
            r#"
version: 1
service: my-service
namespace_prefix: service.myservice
categories:
  - id: general
    label: General
    namespaces:
      - service.myservice.general
    fields:
      - key: flag
        label: Flag
        type: boolean
        default: false
"#,
        );
        let temp = tempdir().unwrap();
        let ts_dir = temp.path().join("react");
        let dart_dir = temp.path().join("flutter");
        let targets = vec![
            GeneratedTypesTarget {
                target: "typescript",
                output_dir: ts_dir.as_path(),
            },
            GeneratedTypesTarget {
                target: "dart",
                output_dir: dart_dir.as_path(),
            },
        ];

        let written =
            write_generated_types_to_targets_from_file(schema_file.path(), &targets).unwrap();

        assert_eq!(written.len(), 2);
        assert!(written.iter().any(|path| path.ends_with("config-types.ts")));
        assert!(written.iter().any(|path| path.ends_with("config_types.dart")));
        assert!(ts_dir.join("config-types.ts").exists());
        assert!(dart_dir.join("config_types.dart").exists());
    }

    #[test]
    fn test_generate_types_from_file_rejects_invalid_schema() {
        let schema_file = write_schema_file(
            r#"
version: 1
service: bad-service
namespace_prefix: service.bad
categories:
  - id: general
    label: General
    namespaces:
      - service.bad.general
    fields:
      - key: flag
        label: Flag
"#,
        );

        let error = generate_typescript_types_from_file(
            schema_file.path().to_str().unwrap(),
        )
        .unwrap_err();

        assert!(error.to_string().contains("validation failed"));
    }

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("enable_feature"), "enableFeature");
        assert_eq!(to_camel_case("verify-ca"), "verifyCa");
        assert_eq!(to_camel_case("verify-full"), "verifyFull");
        assert_eq!(to_camel_case("simple"), "simple");
    }
}
