apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"gitea","namespace":"gitops"},"spec":{"ports":[{"name":"http","port":3000,"targetPort":3000}],"selector":{"app":"gitea"}}}
  name: gitea
  namespace: gitops
spec:
  - 10.96.134.44
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
