FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /{{ service_name }}-bff ./cmd

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /{{ service_name }}-bff /{{ service_name }}-bff
ENTRYPOINT ["/{{ service_name }}-bff"]
