# cert-manager (Helm chart values)
# helm repo add jetstack https://charts.jetstack.io
# helm install cert-manager jetstack/cert-manager -n cert-manager --version v1.20.2 -f values.yaml

crds:
  enabled: true
  keep: true

replicaCount: 1
webhook:
  replicaCount: 1
cainjector:
  replicaCount: 1

prometheus:
  enabled: false

extraArgs:
  - --enable-gateway-api

resources:
  requests:
    cpu: 50m
    memory: 64Mi
