-- L-003/H-007 監査対応: init-db スクリプト番号の欠番に関する記録
--
-- 番号 16 は意図的に欠番となっています。
-- 経緯: search-db の初期化スクリプトが以前この番号で存在していましたが、
--        search サービスが Elasticsearch/OpenSearch ベースに移行したため
--        PostgreSQL 初期化スクリプトは不要となり削除されました。
--        将来のスクリプト追加時は 22 番以降を使用してください。
--
-- ※ このファイルは PostgreSQL init-db として実行されますが、
--    SQL 文を含まないため実際の操作は何も行いません。
SELECT 1 AS placeholder_marker WHERE FALSE;
