// 本ファイルは tier1 公開 Binding API の正式 proto。
// 外部システム（HTTP / SMTP / S3 等）への出力バインディング呼出を提供する。
//
// 設計正典:
//   docs/03_要件定義/20_機能要件/40_tier1_API契約IDL/05_Binding_API.md
//   docs/03_要件定義/20_機能要件/10_tier1_API要件/05_Binding_API.md
//
// 関連要件: FR-T1-BINDING-001〜004
// proto 構文宣言（proto3）

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file k1s0/tier1/binding/v1/binding_service.proto (package k1s0.tier1.binding.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// パッケージ命名規約: k1s0.tier1.<api>.v<n>

import { InvokeBindingRequest, InvokeBindingResponse } from "./binding_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Binding API。バインディング名は運用側で事前設定（s3-archive / smtp-notify 等）。
 *
 * @generated from service k1s0.tier1.binding.v1.BindingService
 */
export const BindingService = {
  typeName: "k1s0.tier1.binding.v1.BindingService",
  methods: {
    /**
     * 出力バインディング呼出（tier1 → 外部システムへ送信）
     *
     * @generated from rpc k1s0.tier1.binding.v1.BindingService.Invoke
     */
    invoke: {
      name: "Invoke",
      I: InvokeBindingRequest,
      O: InvokeBindingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

