// This file is @generated by prost-build.
/// GetNavigationRequest はナビゲーション設定取得リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNavigationRequest {
    /// 省略時は公開ルートのみ返す
    #[prost(string, tag = "1")]
    pub bearer_token: ::prost::alloc::string::String,
}
/// NavigationResponse はナビゲーション設定取得レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NavigationResponse {
    #[prost(message, repeated, tag = "1")]
    pub routes: ::prost::alloc::vec::Vec<Route>,
    #[prost(message, repeated, tag = "2")]
    pub guards: ::prost::alloc::vec::Vec<Guard>,
}
/// Route はルーティング定義。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Route {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub component_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub guard_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "5")]
    pub children: ::prost::alloc::vec::Vec<Route>,
    #[prost(message, optional, tag = "6")]
    pub transition: ::core::option::Option<TransitionConfig>,
    #[prost(message, repeated, tag = "7")]
    pub params: ::prost::alloc::vec::Vec<Param>,
    #[prost(string, tag = "8")]
    pub redirect_to: ::prost::alloc::string::String,
}
/// Guard はルートガード定義。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Guard {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "GuardType", tag = "2")]
    pub r#type: i32,
    #[prost(string, tag = "3")]
    pub redirect_to: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Param はルートパラメータ定義。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Param {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ParamType", tag = "2")]
    pub r#type: i32,
}
/// TransitionConfig はページ遷移アニメーション設定。
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransitionConfig {
    #[prost(enumeration = "TransitionType", tag = "1")]
    pub r#type: i32,
    #[prost(uint32, tag = "2")]
    pub duration_ms: u32,
}
/// GuardType はガードの種別を表す。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GuardType {
    Unspecified = 0,
    AuthRequired = 1,
    RoleRequired = 2,
    RedirectIfAuthenticated = 3,
}
impl GuardType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "GUARD_TYPE_UNSPECIFIED",
            Self::AuthRequired => "GUARD_TYPE_AUTH_REQUIRED",
            Self::RoleRequired => "GUARD_TYPE_ROLE_REQUIRED",
            Self::RedirectIfAuthenticated => "GUARD_TYPE_REDIRECT_IF_AUTHENTICATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GUARD_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "GUARD_TYPE_AUTH_REQUIRED" => Some(Self::AuthRequired),
            "GUARD_TYPE_ROLE_REQUIRED" => Some(Self::RoleRequired),
            "GUARD_TYPE_REDIRECT_IF_AUTHENTICATED" => Some(Self::RedirectIfAuthenticated),
            _ => None,
        }
    }
}
/// TransitionType はページ遷移アニメーションの種別を表す。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TransitionType {
    Unspecified = 0,
    Fade = 1,
    Slide = 2,
    Modal = 3,
}
impl TransitionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRANSITION_TYPE_UNSPECIFIED",
            Self::Fade => "TRANSITION_TYPE_FADE",
            Self::Slide => "TRANSITION_TYPE_SLIDE",
            Self::Modal => "TRANSITION_TYPE_MODAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSITION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "TRANSITION_TYPE_FADE" => Some(Self::Fade),
            "TRANSITION_TYPE_SLIDE" => Some(Self::Slide),
            "TRANSITION_TYPE_MODAL" => Some(Self::Modal),
            _ => None,
        }
    }
}
/// ParamType はルートパラメータの型を表す。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ParamType {
    Unspecified = 0,
    String = 1,
    Int = 2,
    Uuid = 3,
}
impl ParamType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PARAM_TYPE_UNSPECIFIED",
            Self::String => "PARAM_TYPE_STRING",
            Self::Int => "PARAM_TYPE_INT",
            Self::Uuid => "PARAM_TYPE_UUID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PARAM_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "PARAM_TYPE_STRING" => Some(Self::String),
            "PARAM_TYPE_INT" => Some(Self::Int),
            "PARAM_TYPE_UUID" => Some(Self::Uuid),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod navigation_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with NavigationServiceServer.
    #[async_trait]
    pub trait NavigationService: std::marker::Send + std::marker::Sync + 'static {
        /// ナビゲーション設定取得
        async fn get_navigation(
            &self,
            request: tonic::Request<super::GetNavigationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::NavigationResponse>,
            tonic::Status,
        >;
    }
    /// NavigationService はクライアントアプリのルーティング設定を提供する。
    #[derive(Debug)]
    pub struct NavigationServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> NavigationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for NavigationServiceServer<T>
    where
        T: NavigationService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/k1s0.system.navigation.v1.NavigationService/GetNavigation" => {
                    #[allow(non_camel_case_types)]
                    struct GetNavigationSvc<T: NavigationService>(pub Arc<T>);
                    impl<
                        T: NavigationService,
                    > tonic::server::UnaryService<super::GetNavigationRequest>
                    for GetNavigationSvc<T> {
                        type Response = super::NavigationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetNavigationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NavigationService>::get_navigation(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetNavigationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for NavigationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "k1s0.system.navigation.v1.NavigationService";
    impl<T> tonic::server::NamedService for NavigationServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
