# MySQL Helm values - prod environment
# Bitnami MySQL chart

auth:
  rootPassword: ""  # Override via Vault secret
  database: k1s0
  username: k1s0

primary:
  persistence:
    enabled: true
    storageClass: ceph-block-fast
    size: 100Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 8Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - mysql
          topologyKey: kubernetes.io/hostname

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: ceph-block-fast
    size: 100Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: observability

tls:
  enabled: true
  autoGenerated: true
