use std::path::PathBuf;

pub fn generate(name: &str) -> Vec<(PathBuf, String)> {
    vec![
        (PathBuf::from("pubspec.yaml"), pubspec_yaml(name)),
        (PathBuf::from("lib/main.dart"), main_dart(name)),
        (PathBuf::from("test/widget_test.dart"), widget_test_dart(name)),
        (PathBuf::from("README.md"), readme(name)),
        (PathBuf::from(".github/workflows/ci.yml"), ci_yml()),
        (PathBuf::from("Dockerfile"), dockerfile()),
        (PathBuf::from(".dockerignore"), dockerignore()),
    ]
}

pub fn dockerfile() -> String {
    r#"FROM ghcr.io/cirruslabs/flutter:stable AS build
WORKDIR /app
COPY . .
RUN flutter pub get
RUN flutter build web

FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"#
    .to_string()
}

pub fn dockerignore() -> String {
    r#".dart_tool
build
.git
.github
.env
"#
    .to_string()
}

fn pubspec_yaml(name: &str) -> String {
    format!(
        r#"name: {name}
description: A Flutter project generated by k1s0.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
"#
    )
}

fn main_dart(name: &str) -> String {
    format!(
        r#"import 'package:flutter/material.dart';

void main() {{
  runApp(const MyApp());
}}

class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{name}',
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(title: '{name}'),
    );
  }}
}}

class MyHomePage extends StatelessWidget {{
  const MyHomePage({{super.key, required this.title}});

  final String title;

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: const Center(
        child: Text('Welcome to {name}!'),
      ),
    );
  }}
}}
"#
    )
}

fn widget_test_dart(name: &str) -> String {
    format!(
        r#"import 'package:flutter_test/flutter_test.dart';
import 'package:{name}/main.dart';

void main() {{
  testWidgets('App renders correctly', (WidgetTester tester) async {{
    await tester.pumpWidget(const MyApp());
    expect(find.text('{name}'), findsWidgets);
  }});
}}
"#
    )
}

fn readme(name: &str) -> String {
    format!(
        r#"# {name}

A Flutter frontend project generated by k1s0.

## Getting Started

```bash
flutter pub get
flutter run
```

## Testing

```bash
flutter test
```

## Building

```bash
flutter build apk
flutter build ios
```
"#
    )
}

fn ci_yml() -> String {
    r#"name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - run: flutter pub get
      - run: flutter test
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generates_expected_files() {
        let files = generate("my-flutter-app");
        let paths: Vec<PathBuf> = files.iter().map(|(p, _)| p.clone()).collect();

        assert!(paths.contains(&PathBuf::from("pubspec.yaml")));
        assert!(paths.contains(&PathBuf::from("lib/main.dart")));
        assert!(paths.contains(&PathBuf::from("test/widget_test.dart")));
        assert!(paths.contains(&PathBuf::from("README.md")));
        assert!(paths.contains(&PathBuf::from(".github/workflows/ci.yml")));
        assert!(paths.contains(&PathBuf::from("Dockerfile")));
        assert!(paths.contains(&PathBuf::from(".dockerignore")));
    }

    #[test]
    fn test_dockerfile_uses_flutter_and_nginx() {
        let content = dockerfile();
        assert!(content.contains("ghcr.io/cirruslabs/flutter"));
        assert!(content.contains("nginx:alpine"));
        assert!(content.contains("flutter build web"));
        assert!(content.contains("EXPOSE 80"));
    }

    #[test]
    fn test_dockerignore_excludes_dart_tool() {
        let content = dockerignore();
        assert!(content.contains(".dart_tool"));
    }

    #[test]
    fn test_pubspec_contains_name() {
        let files = generate("my-flutter-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("pubspec.yaml")).unwrap();
        assert!(content.contains("name: my-flutter-app"));
        assert!(content.contains("flutter"));
    }

    #[test]
    fn test_main_dart_contains_name() {
        let files = generate("my-flutter-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("lib/main.dart")).unwrap();
        assert!(content.contains("my-flutter-app"));
        assert!(content.contains("MaterialApp"));
    }

    #[test]
    fn test_widget_test_exists() {
        let files = generate("my-flutter-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("test/widget_test.dart")).unwrap();
        assert!(content.contains("testWidgets"));
    }

    #[test]
    fn test_ci_yml_runs_flutter_test() {
        let files = generate("my-flutter-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from(".github/workflows/ci.yml")).unwrap();
        assert!(content.contains("flutter test"));
    }
}
