use std::path::PathBuf;

pub fn generate(name: &str) -> Vec<(PathBuf, String)> {
    vec![
        (PathBuf::from("package.json"), package_json(name)),
        (PathBuf::from("src/index.tsx"), index_tsx()),
        (PathBuf::from("src/App.tsx"), app_tsx(name)),
        (PathBuf::from("src/App.test.tsx"), app_test_tsx()),
        (PathBuf::from("README.md"), readme(name)),
        (PathBuf::from(".github/workflows/ci.yml"), ci_yml()),
    ]
}

fn package_json(name: &str) -> String {
    format!(
        r#"{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^5.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0"
  }},
  "scripts": {{
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  }},
  "browserslist": {{
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }}
}}"#
    )
}

fn index_tsx() -> String {
    r#"import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
"#
    .to_string()
}

fn app_tsx(name: &str) -> String {
    format!(
        r#"import React from 'react';

function App() {{
  return (
    <div>
      <h1>{name}</h1>
      <p>Welcome to {name}!</p>
    </div>
  );
}}

export default App;
"#
    )
}

fn app_test_tsx() -> String {
    r#"import React from 'react';
import { render, screen } from '@testing-library/react';
import App from './App';

test('renders app', () => {
  render(<App />);
  const element = screen.getByRole('heading');
  expect(element).toBeInTheDocument();
});
"#
    .to_string()
}

fn readme(name: &str) -> String {
    format!(
        r#"# {name}

A React frontend project generated by k1s0.

## Getting Started

```bash
npm install
npm start
```

## Testing

```bash
npm test
```

## Building

```bash
npm run build
```
"#
    )
}

fn ci_yml() -> String {
    r#"name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test -- --watchAll=false
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generates_expected_files() {
        let files = generate("my-react-app");
        let paths: Vec<PathBuf> = files.iter().map(|(p, _)| p.clone()).collect();

        assert!(paths.contains(&PathBuf::from("package.json")));
        assert!(paths.contains(&PathBuf::from("src/index.tsx")));
        assert!(paths.contains(&PathBuf::from("src/App.tsx")));
        assert!(paths.contains(&PathBuf::from("src/App.test.tsx")));
        assert!(paths.contains(&PathBuf::from("README.md")));
        assert!(paths.contains(&PathBuf::from(".github/workflows/ci.yml")));
    }

    #[test]
    fn test_package_json_contains_name() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("package.json")).unwrap();
        assert!(content.contains("\"name\": \"my-react-app\""));
        assert!(content.contains("react"));
        assert!(content.contains("react-dom"));
    }

    #[test]
    fn test_app_tsx_contains_name() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("src/App.tsx")).unwrap();
        assert!(content.contains("my-react-app"));
    }

    #[test]
    fn test_ci_yml_runs_npm_test() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from(".github/workflows/ci.yml")).unwrap();
        assert!(content.contains("npm install"));
        assert!(content.contains("npm test"));
    }

    #[test]
    fn test_index_tsx_has_react_root() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("src/index.tsx")).unwrap();
        assert!(content.contains("ReactDOM.createRoot"));
        assert!(content.contains("<App />"));
    }
}
