use std::path::PathBuf;

pub fn generate(name: &str) -> Vec<(PathBuf, String)> {
    vec![
        (PathBuf::from("package.json"), package_json(name)),
        (PathBuf::from("index.html"), index_html(name)),
        (PathBuf::from("vite.config.ts"), vite_config()),
        (PathBuf::from("tsconfig.json"), tsconfig()),
        (PathBuf::from("src/main.tsx"), main_tsx()),
        (PathBuf::from("src/App.tsx"), app_tsx(name)),
        (PathBuf::from("src/App.test.tsx"), app_test_tsx()),
        (PathBuf::from("README.md"), readme(name)),
        (PathBuf::from(".github/workflows/ci.yml"), ci_yml()),
        (PathBuf::from("Dockerfile"), dockerfile()),
        (PathBuf::from(".dockerignore"), dockerignore()),
    ]
}

pub fn dockerfile() -> String {
    r#"FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"#
    .to_string()
}

pub fn dockerignore() -> String {
    r#"node_modules
dist
.git
.github
.env
"#
    .to_string()
}

fn package_json(name: &str) -> String {
    format!(
        r#"{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }},
  "devDependencies": {{
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.3.0",
    "typescript": "^5.5.0",
    "vite": "^6.0.0",
    "vitest": "^3.0.0",
    "@testing-library/react": "^16.0.0",
    "@testing-library/jest-dom": "^6.0.0",
    "jsdom": "^25.0.0"
  }},
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "vitest run"
  }}
}}"#
    )
}

fn index_html(name: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
"#
    )
}

fn vite_config() -> String {
    r#"import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
  },
});
"#
    .to_string()
}

fn tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "jsx": "react-jsx",
    "strict": true,
    "moduleResolution": "bundler",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["src"]
}
"#
    .to_string()
}

fn main_tsx() -> String {
    r#"import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
"#
    .to_string()
}

fn app_tsx(name: &str) -> String {
    format!(
        r#"function App() {{
  return (
    <div>
      <h1>{name}</h1>
      <p>Welcome to {name}!</p>
    </div>
  );
}}

export default App;
"#
    )
}

fn app_test_tsx() -> String {
    r#"import { render, screen } from '@testing-library/react';
import { expect, test } from 'vitest';
import App from './App';

test('renders app', () => {
  render(<App />);
  const element = screen.getByRole('heading');
  expect(element).toBeDefined();
});
"#
    .to_string()
}

fn readme(name: &str) -> String {
    format!(
        r#"# {name}

A React frontend project generated by k1s0.

## Getting Started

```bash
npm install
npm run dev
```

## Testing

```bash
npm test
```

## Building

```bash
npm run build
```
"#
    )
}

fn ci_yml() -> String {
    r#"name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generates_expected_files() {
        let files = generate("my-react-app");
        let paths: Vec<PathBuf> = files.iter().map(|(p, _)| p.clone()).collect();

        assert!(paths.contains(&PathBuf::from("package.json")));
        assert!(paths.contains(&PathBuf::from("index.html")));
        assert!(paths.contains(&PathBuf::from("vite.config.ts")));
        assert!(paths.contains(&PathBuf::from("tsconfig.json")));
        assert!(paths.contains(&PathBuf::from("src/main.tsx")));
        assert!(paths.contains(&PathBuf::from("src/App.tsx")));
        assert!(paths.contains(&PathBuf::from("src/App.test.tsx")));
        assert!(paths.contains(&PathBuf::from("README.md")));
        assert!(paths.contains(&PathBuf::from(".github/workflows/ci.yml")));
        assert!(paths.contains(&PathBuf::from("Dockerfile")));
        assert!(paths.contains(&PathBuf::from(".dockerignore")));
    }

    #[test]
    fn test_dockerfile_uses_nginx() {
        let content = dockerfile();
        assert!(content.contains("node:20-alpine"));
        assert!(content.contains("nginx:alpine"));
        assert!(content.contains("npm run build"));
        assert!(content.contains("/app/dist"));
        assert!(content.contains("EXPOSE 80"));
    }

    #[test]
    fn test_dockerignore_excludes_node_modules() {
        let content = dockerignore();
        assert!(content.contains("node_modules"));
        assert!(content.contains("dist"));
    }

    #[test]
    fn test_package_json_uses_vite() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("package.json")).unwrap();
        assert!(content.contains("\"name\": \"my-react-app\""));
        assert!(content.contains("react"));
        assert!(content.contains("react-dom"));
        assert!(content.contains("vite"));
        assert!(content.contains("vitest"));
        assert!(!content.contains("react-scripts"));
    }

    #[test]
    fn test_app_tsx_contains_name() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("src/App.tsx")).unwrap();
        assert!(content.contains("my-react-app"));
    }

    #[test]
    fn test_ci_yml_runs_npm_test() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from(".github/workflows/ci.yml")).unwrap();
        assert!(content.contains("npm ci"));
        assert!(content.contains("npm test"));
    }

    #[test]
    fn test_main_tsx_has_react_root() {
        let files = generate("my-react-app");
        let (_, content) = files.iter().find(|(p, _)| p == &PathBuf::from("src/main.tsx")).unwrap();
        assert!(content.contains("ReactDOM.createRoot"));
        assert!(content.contains("<App />"));
    }

    #[test]
    fn test_vite_config_has_react_plugin() {
        let content = vite_config();
        assert!(content.contains("react()"));
        assert!(content.contains("jsdom"));
    }

    #[test]
    fn test_index_html_has_root_div() {
        let content = index_html("my-react-app");
        assert!(content.contains("id=\"root\""));
        assert!(content.contains("src/main.tsx"));
        assert!(content.contains("my-react-app"));
    }
}
