// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluateFlagRequest {
    #[prost(string, tag = "1")]
    pub flag_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub context: ::core::option::Option<EvaluationContext>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluateFlagResponse {
    #[prost(string, tag = "1")]
    pub flag_key: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    #[prost(string, tag = "3")]
    pub variant: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluationContext {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFlagRequest {
    #[prost(string, tag = "1")]
    pub flag_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFlagResponse {
    #[prost(message, optional, tag = "1")]
    pub flag: ::core::option::Option<FeatureFlag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFlagRequest {
    #[prost(string, tag = "1")]
    pub flag_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "4")]
    pub variants: ::prost::alloc::vec::Vec<FlagVariant>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFlagResponse {
    #[prost(message, optional, tag = "1")]
    pub flag: ::core::option::Option<FeatureFlag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFlagRequest {
    #[prost(string, tag = "1")]
    pub flag_key: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFlagResponse {
    #[prost(message, optional, tag = "1")]
    pub flag: ::core::option::Option<FeatureFlag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureFlag {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub flag_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "5")]
    pub variants: ::prost::alloc::vec::Vec<FlagVariant>,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<super::super::common::v1::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<super::super::common::v1::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlagVariant {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub weight: i32,
}
/// Generated server implementations.
pub mod feature_flag_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with FeatureFlagServiceServer.
    #[async_trait]
    pub trait FeatureFlagService: std::marker::Send + std::marker::Sync + 'static {
        async fn evaluate_flag(
            &self,
            request: tonic::Request<super::EvaluateFlagRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EvaluateFlagResponse>,
            tonic::Status,
        >;
        async fn get_flag(
            &self,
            request: tonic::Request<super::GetFlagRequest>,
        ) -> std::result::Result<tonic::Response<super::GetFlagResponse>, tonic::Status>;
        async fn create_flag(
            &self,
            request: tonic::Request<super::CreateFlagRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateFlagResponse>,
            tonic::Status,
        >;
        async fn update_flag(
            &self,
            request: tonic::Request<super::UpdateFlagRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateFlagResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct FeatureFlagServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> FeatureFlagServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for FeatureFlagServiceServer<T>
    where
        T: FeatureFlagService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/k1s0.system.featureflag.v1.FeatureFlagService/EvaluateFlag" => {
                    #[allow(non_camel_case_types)]
                    struct EvaluateFlagSvc<T: FeatureFlagService>(pub Arc<T>);
                    impl<
                        T: FeatureFlagService,
                    > tonic::server::UnaryService<super::EvaluateFlagRequest>
                    for EvaluateFlagSvc<T> {
                        type Response = super::EvaluateFlagResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EvaluateFlagRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureFlagService>::evaluate_flag(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EvaluateFlagSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.featureflag.v1.FeatureFlagService/GetFlag" => {
                    #[allow(non_camel_case_types)]
                    struct GetFlagSvc<T: FeatureFlagService>(pub Arc<T>);
                    impl<
                        T: FeatureFlagService,
                    > tonic::server::UnaryService<super::GetFlagRequest>
                    for GetFlagSvc<T> {
                        type Response = super::GetFlagResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetFlagRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureFlagService>::get_flag(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetFlagSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.featureflag.v1.FeatureFlagService/CreateFlag" => {
                    #[allow(non_camel_case_types)]
                    struct CreateFlagSvc<T: FeatureFlagService>(pub Arc<T>);
                    impl<
                        T: FeatureFlagService,
                    > tonic::server::UnaryService<super::CreateFlagRequest>
                    for CreateFlagSvc<T> {
                        type Response = super::CreateFlagResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateFlagRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureFlagService>::create_flag(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateFlagSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.featureflag.v1.FeatureFlagService/UpdateFlag" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateFlagSvc<T: FeatureFlagService>(pub Arc<T>);
                    impl<
                        T: FeatureFlagService,
                    > tonic::server::UnaryService<super::UpdateFlagRequest>
                    for UpdateFlagSvc<T> {
                        type Response = super::UpdateFlagResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateFlagRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureFlagService>::update_flag(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateFlagSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for FeatureFlagServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "k1s0.system.featureflag.v1.FeatureFlagService";
    impl<T> tonic::server::NamedService for FeatureFlagServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
