// 本ファイルは tier1 公開 Service Invoke API の正式 proto。
// サービス間呼出を仲介する RPC を提供する（Dapr の app-to-app invoke 概念に対応）。
//
// 設計正典:
//   docs/03_要件定義/20_機能要件/40_tier1_API契約IDL/01_Service_Invoke_API.md
//   docs/03_要件定義/20_機能要件/10_tier1_API要件/01_Service_Invoke_API.md
//
// 関連要件: FR-T1-INVOKE-001〜005
//
// 注: 正典 IDL では package を `k1s0.tier1.invoke.v1` と記載しているが、
//     ディレクトリ設計（DS-DIR-* / IMP-DIR-*）と SDK 生成パスが
//     `serviceinvoke` で統一されているため、buf STANDARD lint の
//     PACKAGE_DIRECTORY_MATCH を満たすために本パッケージは
//     `k1s0.tier1.serviceinvoke.v1` とする。RPC / message / フィールドは
//     IDL 正典と完全一致させる。
// proto 構文宣言（proto3）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: k1s0/tier1/serviceinvoke/v1/serviceinvoke_service.proto

// パッケージ命名規約: k1s0.tier1.<api>.v<n>

package serviceinvokev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvokeService_Invoke_FullMethodName       = "/k1s0.tier1.serviceinvoke.v1.InvokeService/Invoke"
	InvokeService_InvokeStream_FullMethodName = "/k1s0.tier1.serviceinvoke.v1.InvokeService/InvokeStream"
)

// InvokeServiceClient is the client API for InvokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// サービス間呼出を仲介する。tier1 が allowlist / RBAC / 監査を一括強制する。
type InvokeServiceClient interface {
	// 任意サービスの任意メソッドを呼び出す（app_id は Dapr の app_id 概念と互換）
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// ストリーミング呼出（大容量応答や段階出力のため、サーバ → クライアントの単方向ストリーム）
	InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeChunk], error)
}

type invokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvokeServiceClient(cc grpc.ClientConnInterface) InvokeServiceClient {
	return &invokeServiceClient{cc}
}

func (c *invokeServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, InvokeService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokeServiceClient) InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InvokeService_ServiceDesc.Streams[0], InvokeService_InvokeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequest, InvokeChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InvokeService_InvokeStreamClient = grpc.ServerStreamingClient[InvokeChunk]

// InvokeServiceServer is the server API for InvokeService service.
// All implementations should embed UnimplementedInvokeServiceServer
// for forward compatibility.
//
// サービス間呼出を仲介する。tier1 が allowlist / RBAC / 監査を一括強制する。
type InvokeServiceServer interface {
	// 任意サービスの任意メソッドを呼び出す（app_id は Dapr の app_id 概念と互換）
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// ストリーミング呼出（大容量応答や段階出力のため、サーバ → クライアントの単方向ストリーム）
	InvokeStream(*InvokeRequest, grpc.ServerStreamingServer[InvokeChunk]) error
}

// UnimplementedInvokeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvokeServiceServer struct{}

func (UnimplementedInvokeServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInvokeServiceServer) InvokeStream(*InvokeRequest, grpc.ServerStreamingServer[InvokeChunk]) error {
	return status.Errorf(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedInvokeServiceServer) testEmbeddedByValue() {}

// UnsafeInvokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvokeServiceServer will
// result in compilation errors.
type UnsafeInvokeServiceServer interface {
	mustEmbedUnimplementedInvokeServiceServer()
}

func RegisterInvokeServiceServer(s grpc.ServiceRegistrar, srv InvokeServiceServer) {
	// If the following call pancis, it indicates UnimplementedInvokeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvokeService_ServiceDesc, srv)
}

func _InvokeService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokeServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvokeService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokeServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvokeService_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvokeServiceServer).InvokeStream(m, &grpc.GenericServerStream[InvokeRequest, InvokeChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InvokeService_InvokeStreamServer = grpc.ServerStreamingServer[InvokeChunk]

// InvokeService_ServiceDesc is the grpc.ServiceDesc for InvokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k1s0.tier1.serviceinvoke.v1.InvokeService",
	HandlerType: (*InvokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _InvokeService_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _InvokeService_InvokeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "k1s0/tier1/serviceinvoke/v1/serviceinvoke_service.proto",
}
