// @generated
// This file is @generated by prost-build.
/// EvaluateDecision の Request。
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluateDecisionRequest {
    /// テナント識別子（DS-SW-IIF-017、ルールセット参照のキー）
    #[prost(string, tag="1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// リクエスト追跡 ID（UUID v4）
    #[prost(string, tag="2")]
    pub request_id: ::prost::alloc::string::String,
    /// 分散トレース ID（W3C traceparent の trace-id 部）
    #[prost(string, tag="3")]
    pub trace_id: ::prost::alloc::string::String,
    /// 評価する rule_id（rule_loader が cache 済みのもの）
    #[prost(string, tag="4")]
    pub rule_id: ::prost::alloc::string::String,
    /// ルールセットのバージョン（空なら latest を採用）
    #[prost(string, tag="5")]
    pub rule_version: ::prost::alloc::string::String,
    /// 評価入力（JSON 互換、ZEN Engine の入力フォーマット）
    #[prost(message, optional, tag="6")]
    pub input: ::core::option::Option<::prost_types::Struct>,
    /// トレース取得を要求するか（true 時に DecisionTraceEntry を返却、デバッグ用）
    #[prost(bool, tag="7")]
    pub collect_trace: bool,
}
/// EvaluateDecision の Response。
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluateDecisionResponse {
    /// 評価結果（JSON 互換、ZEN Engine の出力フォーマット）
    #[prost(message, optional, tag="1")]
    pub output: ::core::option::Option<::prost_types::Struct>,
    /// 実際に使われた rule_version（リクエストで unspecified だった場合に確定）
    #[prost(string, tag="2")]
    pub rule_version: ::prost::alloc::string::String,
    /// 評価トレース（collect_trace=true 時のみ非空）
    #[prost(message, repeated, tag="3")]
    pub trace: ::prost::alloc::vec::Vec<DecisionTraceEntry>,
    /// cache hit だったかどうか（観測 / 性能チューニング用）
    #[prost(bool, tag="4")]
    pub cache_hit: bool,
    /// 評価所要時間（マイクロ秒、cache hit/miss 計測用）
    #[prost(int64, tag="5")]
    pub elapsed_micros: i64,
}
/// 評価トレース 1 ステップ（ZEN Engine の中間ノード単位）。
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionTraceEntry {
    /// ノード ID（JDM 上の一意識別子）
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// ノードタイプ（"decision_table" / "expression" / "function" 等）
    #[prost(string, tag="2")]
    pub node_type: ::prost::alloc::string::String,
    /// 当該ノードの入力（JSON 互換）
    #[prost(message, optional, tag="3")]
    pub input: ::core::option::Option<::prost_types::Struct>,
    /// 当該ノードの出力（JSON 互換）
    #[prost(message, optional, tag="4")]
    pub output: ::core::option::Option<::prost_types::Struct>,
    /// 当該ノードの所要時間（マイクロ秒）
    #[prost(int64, tag="5")]
    pub elapsed_micros: i64,
}
include!("k1s0.internal.decision.v1.tonic.rs");
// @@protoc_insertion_point(module)