// 本ファイルは tier1 公開 Workflow API の正式 proto。
// 短期 Dapr Workflow / 長期 Temporal の双方を抽象化した Workflow ライフサイクル API。
//
// 設計正典:
//   docs/03_要件定義/20_機能要件/40_tier1_API契約IDL/06_Workflow_API.md
//   docs/03_要件定義/20_機能要件/10_tier1_API要件/06_Workflow_API.md
//
// 関連要件: FR-T1-WORKFLOW-001〜005
// proto 構文宣言（proto3）

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js"
// @generated from file k1s0/tier1/workflow/v1/workflow_service.proto (package k1s0.tier1.workflow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// パッケージ命名規約: k1s0.tier1.<api>.v<n>

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ErrorDetail, TenantContext } from "../../common/v1/common_pb.js";

/**
 * バックエンド種別（FR-T1-WORKFLOW-001 の "短期は Dapr Workflow、長期実行は Temporal" 対応）。
 * SDK の RunShort / RunLong は本 enum を BACKEND_DAPR / BACKEND_TEMPORAL に固定する。
 * 注: zero 値は AUTO（明示指定なし、tier1 が workflow_type / 期待実行時間で振り分け）。
 * buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
 *
 * @generated from enum k1s0.tier1.workflow.v1.WorkflowBackend
 */
export enum WorkflowBackend {
  /**
   * 既定値: tier1 が workflow_type / 期待実行時間に基づいて自動選択する。
   *
   * @generated from enum value: BACKEND_AUTO = 0;
   */
  BACKEND_AUTO = 0,

  /**
   * 短期ワークフロー向け（Dapr Workflow building block、上限 7 日）。
   *
   * @generated from enum value: BACKEND_DAPR = 1;
   */
  BACKEND_DAPR = 1,

  /**
   * 長期ワークフロー向け（Temporal、上限なし）。
   *
   * @generated from enum value: BACKEND_TEMPORAL = 2;
   */
  BACKEND_TEMPORAL = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(WorkflowBackend)
proto3.util.setEnumType(WorkflowBackend, "k1s0.tier1.workflow.v1.WorkflowBackend", [
  { no: 0, name: "BACKEND_AUTO" },
  { no: 1, name: "BACKEND_DAPR" },
  { no: 2, name: "BACKEND_TEMPORAL" },
]);

/**
 * 実行状態の列挙。
 * 注: 正典 IDL は本 enum の zero value を `RUNNING = 0` と定義しているため、
 *     buf STANDARD lint の ENUM_ZERO_VALUE_SUFFIX / ENUM_VALUE_PREFIX を ignore する。
 * buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
 * buf:lint:ignore ENUM_VALUE_PREFIX
 *
 * @generated from enum k1s0.tier1.workflow.v1.WorkflowStatus
 */
export enum WorkflowStatus {
  /**
   * 実行中（既定値、Start 直後の状態）
   *
   * @generated from enum value: RUNNING = 0;
   */
  RUNNING = 0,

  /**
   * 正常完了
   *
   * @generated from enum value: COMPLETED = 1;
   */
  COMPLETED = 1,

  /**
   * 失敗終了
   *
   * @generated from enum value: FAILED = 2;
   */
  FAILED = 2,

  /**
   * Cancel による正常停止
   *
   * @generated from enum value: CANCELED = 3;
   */
  CANCELED = 3,

  /**
   * Terminate による強制停止
   *
   * @generated from enum value: TERMINATED = 4;
   */
  TERMINATED = 4,

  /**
   * Continue-as-New（長期ワークフローの履歴ローテーション）
   *
   * @generated from enum value: CONTINUED_AS_NEW = 5;
   */
  CONTINUED_AS_NEW = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(WorkflowStatus)
proto3.util.setEnumType(WorkflowStatus, "k1s0.tier1.workflow.v1.WorkflowStatus", [
  { no: 0, name: "RUNNING" },
  { no: 1, name: "COMPLETED" },
  { no: 2, name: "FAILED" },
  { no: 3, name: "CANCELED" },
  { no: 4, name: "TERMINATED" },
  { no: 5, name: "CONTINUED_AS_NEW" },
]);

/**
 * Start リクエスト
 *
 * @generated from message k1s0.tier1.workflow.v1.StartRequest
 */
export class StartRequest extends Message<StartRequest> {
  /**
   * ワークフロー種別（tier2 で登録されたコード名）
   *
   * @generated from field: string workflow_type = 1;
   */
  workflowType = "";

  /**
   * 実行 ID（指定なければ tier1 が UUID を生成）
   *
   * @generated from field: string workflow_id = 2;
   */
  workflowId = "";

  /**
   * 初期入力（任意 bytes、エンコーディングは tier2 側合意）
   *
   * @generated from field: bytes input = 3;
   */
  input = new Uint8Array(0);

  /**
   * 冪等性（同一 workflow_id の重複開始は既存実行を返す）
   *
   * @generated from field: bool idempotent = 4;
   */
  idempotent = false;

  /**
   * 呼出元コンテキスト
   *
   * @generated from field: k1s0.tier1.common.v1.TenantContext context = 5;
   */
  context?: TenantContext;

  /**
   * バックエンド hint（BACKEND_AUTO で tier1 が自動選択）。
   *
   * @generated from field: k1s0.tier1.workflow.v1.WorkflowBackend backend = 6;
   */
  backend = WorkflowBackend.BACKEND_AUTO;

  /**
   * 冪等性キー（共通規約 §「冪等性と再試行」: 24h TTL の dedup）
   * 同一キーでの再試行は副作用を重複させず初回 StartResponse を返す
   *
   * @generated from field: string idempotency_key = 7;
   */
  idempotencyKey = "";

  constructor(data?: PartialMessage<StartRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.StartRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "input", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "idempotent", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "context", kind: "message", T: TenantContext },
    { no: 6, name: "backend", kind: "enum", T: proto3.getEnumType(WorkflowBackend) },
    { no: 7, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartRequest {
    return new StartRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartRequest {
    return new StartRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartRequest {
    return new StartRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartRequest | PlainMessage<StartRequest> | undefined, b: StartRequest | PlainMessage<StartRequest> | undefined): boolean {
    return proto3.util.equals(StartRequest, a, b);
  }
}

/**
 * Start 応答
 *
 * @generated from message k1s0.tier1.workflow.v1.StartResponse
 */
export class StartResponse extends Message<StartResponse> {
  /**
   * ワークフロー ID（リクエストの workflow_id か、tier1 採番の UUID）
   *
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * 実行 ID（リトライや継続実行時に新しい値が割当）
   *
   * @generated from field: string run_id = 2;
   */
  runId = "";

  /**
   * 実際に選択された backend（AUTO で起動された場合の解決結果が入る）。
   *
   * @generated from field: k1s0.tier1.workflow.v1.WorkflowBackend backend = 3;
   */
  backend = WorkflowBackend.BACKEND_AUTO;

  constructor(data?: PartialMessage<StartResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.StartResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "backend", kind: "enum", T: proto3.getEnumType(WorkflowBackend) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartResponse {
    return new StartResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartResponse {
    return new StartResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartResponse {
    return new StartResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartResponse | PlainMessage<StartResponse> | undefined, b: StartResponse | PlainMessage<StartResponse> | undefined): boolean {
    return proto3.util.equals(StartResponse, a, b);
  }
}

/**
 * Signal リクエスト
 *
 * @generated from message k1s0.tier1.workflow.v1.SignalRequest
 */
export class SignalRequest extends Message<SignalRequest> {
  /**
   * 対象ワークフロー ID
   *
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * シグナル名（tier2 ワークフロー実装が listen している名前）
   *
   * @generated from field: string signal_name = 2;
   */
  signalName = "";

  /**
   * ペイロード（任意 bytes）
   *
   * @generated from field: bytes payload = 3;
   */
  payload = new Uint8Array(0);

  /**
   * 呼出元コンテキスト
   *
   * @generated from field: k1s0.tier1.common.v1.TenantContext context = 4;
   */
  context?: TenantContext;

  constructor(data?: PartialMessage<SignalRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.SignalRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "signal_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "context", kind: "message", T: TenantContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignalRequest {
    return new SignalRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignalRequest {
    return new SignalRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignalRequest {
    return new SignalRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SignalRequest | PlainMessage<SignalRequest> | undefined, b: SignalRequest | PlainMessage<SignalRequest> | undefined): boolean {
    return proto3.util.equals(SignalRequest, a, b);
  }
}

/**
 * Signal 応答（フィールド無し、成功は OK gRPC ステータスで表現）
 *
 * @generated from message k1s0.tier1.workflow.v1.SignalResponse
 */
export class SignalResponse extends Message<SignalResponse> {
  constructor(data?: PartialMessage<SignalResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.SignalResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignalResponse {
    return new SignalResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignalResponse {
    return new SignalResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignalResponse {
    return new SignalResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SignalResponse | PlainMessage<SignalResponse> | undefined, b: SignalResponse | PlainMessage<SignalResponse> | undefined): boolean {
    return proto3.util.equals(SignalResponse, a, b);
  }
}

/**
 * Query リクエスト
 *
 * @generated from message k1s0.tier1.workflow.v1.QueryRequest
 */
export class QueryRequest extends Message<QueryRequest> {
  /**
   * 対象ワークフロー ID
   *
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * クエリ名（tier2 ワークフロー実装が register しているクエリハンドラ名）
   *
   * @generated from field: string query_name = 2;
   */
  queryName = "";

  /**
   * ペイロード
   *
   * @generated from field: bytes payload = 3;
   */
  payload = new Uint8Array(0);

  /**
   * 呼出元コンテキスト
   *
   * @generated from field: k1s0.tier1.common.v1.TenantContext context = 4;
   */
  context?: TenantContext;

  constructor(data?: PartialMessage<QueryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.QueryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "query_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "context", kind: "message", T: TenantContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryRequest {
    return new QueryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryRequest {
    return new QueryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryRequest {
    return new QueryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryRequest | PlainMessage<QueryRequest> | undefined, b: QueryRequest | PlainMessage<QueryRequest> | undefined): boolean {
    return proto3.util.equals(QueryRequest, a, b);
  }
}

/**
 * Query 応答
 *
 * @generated from message k1s0.tier1.workflow.v1.QueryResponse
 */
export class QueryResponse extends Message<QueryResponse> {
  /**
   * クエリ結果
   *
   * @generated from field: bytes result = 1;
   */
  result = new Uint8Array(0);

  constructor(data?: PartialMessage<QueryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.QueryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryResponse {
    return new QueryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryResponse {
    return new QueryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryResponse {
    return new QueryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryResponse | PlainMessage<QueryResponse> | undefined, b: QueryResponse | PlainMessage<QueryResponse> | undefined): boolean {
    return proto3.util.equals(QueryResponse, a, b);
  }
}

/**
 * Cancel リクエスト
 *
 * @generated from message k1s0.tier1.workflow.v1.CancelRequest
 */
export class CancelRequest extends Message<CancelRequest> {
  /**
   * 対象ワークフロー ID
   *
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * キャンセル理由（監査用、自由記述）
   *
   * @generated from field: string reason = 2;
   */
  reason = "";

  /**
   * 呼出元コンテキスト
   *
   * @generated from field: k1s0.tier1.common.v1.TenantContext context = 3;
   */
  context?: TenantContext;

  constructor(data?: PartialMessage<CancelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.CancelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "context", kind: "message", T: TenantContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelRequest {
    return new CancelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelRequest {
    return new CancelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelRequest {
    return new CancelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelRequest | PlainMessage<CancelRequest> | undefined, b: CancelRequest | PlainMessage<CancelRequest> | undefined): boolean {
    return proto3.util.equals(CancelRequest, a, b);
  }
}

/**
 * Cancel 応答
 *
 * @generated from message k1s0.tier1.workflow.v1.CancelResponse
 */
export class CancelResponse extends Message<CancelResponse> {
  constructor(data?: PartialMessage<CancelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.CancelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelResponse {
    return new CancelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelResponse {
    return new CancelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelResponse {
    return new CancelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelResponse | PlainMessage<CancelResponse> | undefined, b: CancelResponse | PlainMessage<CancelResponse> | undefined): boolean {
    return proto3.util.equals(CancelResponse, a, b);
  }
}

/**
 * Terminate リクエスト
 *
 * @generated from message k1s0.tier1.workflow.v1.TerminateRequest
 */
export class TerminateRequest extends Message<TerminateRequest> {
  /**
   * 対象ワークフロー ID
   *
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * 強制終了理由（監査用、自由記述）
   *
   * @generated from field: string reason = 2;
   */
  reason = "";

  /**
   * 呼出元コンテキスト
   *
   * @generated from field: k1s0.tier1.common.v1.TenantContext context = 3;
   */
  context?: TenantContext;

  constructor(data?: PartialMessage<TerminateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.TerminateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "context", kind: "message", T: TenantContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TerminateRequest {
    return new TerminateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TerminateRequest {
    return new TerminateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TerminateRequest {
    return new TerminateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TerminateRequest | PlainMessage<TerminateRequest> | undefined, b: TerminateRequest | PlainMessage<TerminateRequest> | undefined): boolean {
    return proto3.util.equals(TerminateRequest, a, b);
  }
}

/**
 * Terminate 応答
 *
 * @generated from message k1s0.tier1.workflow.v1.TerminateResponse
 */
export class TerminateResponse extends Message<TerminateResponse> {
  constructor(data?: PartialMessage<TerminateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.TerminateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TerminateResponse {
    return new TerminateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TerminateResponse {
    return new TerminateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TerminateResponse {
    return new TerminateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: TerminateResponse | PlainMessage<TerminateResponse> | undefined, b: TerminateResponse | PlainMessage<TerminateResponse> | undefined): boolean {
    return proto3.util.equals(TerminateResponse, a, b);
  }
}

/**
 * GetStatus リクエスト
 *
 * @generated from message k1s0.tier1.workflow.v1.GetStatusRequest
 */
export class GetStatusRequest extends Message<GetStatusRequest> {
  /**
   * 対象ワークフロー ID
   *
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * 呼出元コンテキスト
   *
   * @generated from field: k1s0.tier1.common.v1.TenantContext context = 2;
   */
  context?: TenantContext;

  constructor(data?: PartialMessage<GetStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.GetStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "context", kind: "message", T: TenantContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined, b: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined): boolean {
    return proto3.util.equals(GetStatusRequest, a, b);
  }
}

/**
 * GetStatus 応答
 *
 * @generated from message k1s0.tier1.workflow.v1.GetStatusResponse
 */
export class GetStatusResponse extends Message<GetStatusResponse> {
  /**
   * 現在状態
   *
   * @generated from field: k1s0.tier1.workflow.v1.WorkflowStatus status = 1;
   */
  status = WorkflowStatus.RUNNING;

  /**
   * 直近の実行 ID（Continue-as-New 後は新 run_id を返す）
   *
   * @generated from field: string run_id = 2;
   */
  runId = "";

  /**
   * 完了時の出力（status = COMPLETED の時のみ）
   *
   * @generated from field: bytes output = 3;
   */
  output = new Uint8Array(0);

  /**
   * 失敗時のエラー詳細（status = FAILED の時のみ）
   *
   * @generated from field: k1s0.tier1.common.v1.ErrorDetail error = 4;
   */
  error?: ErrorDetail;

  constructor(data?: PartialMessage<GetStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "k1s0.tier1.workflow.v1.GetStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(WorkflowStatus) },
    { no: 2, name: "run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "output", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "error", kind: "message", T: ErrorDetail },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined, b: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined): boolean {
    return proto3.util.equals(GetStatusResponse, a, b);
  }
}

