// This file is @generated by prost-build.
/// CreateTenantRequest はテナント作成リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTenantRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub plan: ::prost::alloc::string::String,
}
/// CreateTenantResponse はテナント作成レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTenantResponse {
    #[prost(message, optional, tag = "1")]
    pub tenant: ::core::option::Option<Tenant>,
}
/// GetTenantRequest はテナント取得リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTenantRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// GetTenantResponse はテナント取得レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTenantResponse {
    #[prost(message, optional, tag = "1")]
    pub tenant: ::core::option::Option<Tenant>,
}
/// ListTenantsRequest はテナント一覧取得リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantsRequest {
    #[prost(message, optional, tag = "1")]
    pub pagination: ::core::option::Option<super::super::common::v1::Pagination>,
}
/// ListTenantsResponse はテナント一覧取得レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tenants: ::prost::alloc::vec::Vec<Tenant>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::super::common::v1::PaginationResult>,
}
/// AddMemberRequest はメンバー追加リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddMemberRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub role: ::prost::alloc::string::String,
}
/// AddMemberResponse はメンバー追加レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddMemberResponse {
    #[prost(message, optional, tag = "1")]
    pub member: ::core::option::Option<TenantMember>,
}
/// RemoveMemberRequest はメンバー削除リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMemberRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
/// RemoveMemberResponse はメンバー削除レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMemberResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// GetProvisioningStatusRequest はプロビジョニング状態取得リクエスト。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProvisioningStatusRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
/// GetProvisioningStatusResponse はプロビジョニング状態取得レスポンス。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProvisioningStatusResponse {
    #[prost(message, optional, tag = "1")]
    pub job: ::core::option::Option<ProvisioningJob>,
}
/// Tenant はテナント情報。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tenant {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub plan: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// TenantMember はテナントメンバー情報。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TenantMember {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub role: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub joined_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// ProvisioningJob はプロビジョニングジョブ情報。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProvisioningJob {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub current_step: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Generated server implementations.
pub mod tenant_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TenantServiceServer.
    #[async_trait]
    pub trait TenantService: std::marker::Send + std::marker::Sync + 'static {
        /// テナント作成
        async fn create_tenant(
            &self,
            request: tonic::Request<super::CreateTenantRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateTenantResponse>,
            tonic::Status,
        >;
        /// テナント取得
        async fn get_tenant(
            &self,
            request: tonic::Request<super::GetTenantRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTenantResponse>,
            tonic::Status,
        >;
        /// テナント一覧取得
        async fn list_tenants(
            &self,
            request: tonic::Request<super::ListTenantsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTenantsResponse>,
            tonic::Status,
        >;
        /// メンバー追加
        async fn add_member(
            &self,
            request: tonic::Request<super::AddMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddMemberResponse>,
            tonic::Status,
        >;
        /// メンバー削除
        async fn remove_member(
            &self,
            request: tonic::Request<super::RemoveMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveMemberResponse>,
            tonic::Status,
        >;
        /// プロビジョニング状態取得
        async fn get_provisioning_status(
            &self,
            request: tonic::Request<super::GetProvisioningStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProvisioningStatusResponse>,
            tonic::Status,
        >;
    }
    /// TenantService はテナント管理を提供する。
    #[derive(Debug)]
    pub struct TenantServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TenantServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TenantServiceServer<T>
    where
        T: TenantService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/k1s0.system.tenant.v1.TenantService/CreateTenant" => {
                    #[allow(non_camel_case_types)]
                    struct CreateTenantSvc<T: TenantService>(pub Arc<T>);
                    impl<
                        T: TenantService,
                    > tonic::server::UnaryService<super::CreateTenantRequest>
                    for CreateTenantSvc<T> {
                        type Response = super::CreateTenantResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateTenantRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TenantService>::create_tenant(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateTenantSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.tenant.v1.TenantService/GetTenant" => {
                    #[allow(non_camel_case_types)]
                    struct GetTenantSvc<T: TenantService>(pub Arc<T>);
                    impl<
                        T: TenantService,
                    > tonic::server::UnaryService<super::GetTenantRequest>
                    for GetTenantSvc<T> {
                        type Response = super::GetTenantResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTenantRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TenantService>::get_tenant(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTenantSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.tenant.v1.TenantService/ListTenants" => {
                    #[allow(non_camel_case_types)]
                    struct ListTenantsSvc<T: TenantService>(pub Arc<T>);
                    impl<
                        T: TenantService,
                    > tonic::server::UnaryService<super::ListTenantsRequest>
                    for ListTenantsSvc<T> {
                        type Response = super::ListTenantsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListTenantsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TenantService>::list_tenants(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListTenantsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.tenant.v1.TenantService/AddMember" => {
                    #[allow(non_camel_case_types)]
                    struct AddMemberSvc<T: TenantService>(pub Arc<T>);
                    impl<
                        T: TenantService,
                    > tonic::server::UnaryService<super::AddMemberRequest>
                    for AddMemberSvc<T> {
                        type Response = super::AddMemberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddMemberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TenantService>::add_member(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddMemberSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.tenant.v1.TenantService/RemoveMember" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveMemberSvc<T: TenantService>(pub Arc<T>);
                    impl<
                        T: TenantService,
                    > tonic::server::UnaryService<super::RemoveMemberRequest>
                    for RemoveMemberSvc<T> {
                        type Response = super::RemoveMemberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveMemberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TenantService>::remove_member(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveMemberSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/k1s0.system.tenant.v1.TenantService/GetProvisioningStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetProvisioningStatusSvc<T: TenantService>(pub Arc<T>);
                    impl<
                        T: TenantService,
                    > tonic::server::UnaryService<super::GetProvisioningStatusRequest>
                    for GetProvisioningStatusSvc<T> {
                        type Response = super::GetProvisioningStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetProvisioningStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TenantService>::get_provisioning_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetProvisioningStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TenantServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "k1s0.system.tenant.v1.TenantService";
    impl<T> tonic::server::NamedService for TenantServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
