FROM rust:1.82-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release && rm -rf src
COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc:nonroot
COPY --from=builder /app/target/release/{{ service_name }}-bff /{{ service_name }}-bff
ENTRYPOINT ["/{{ service_name }}-bff"]
