apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: invoice-generator
  description: tier2 請求書生成サービス（.NET 8）
  tags:
    - tier2
    - dotnet
    - invoice
    - billing
  annotations:
    backstage.io/techdocs-ref: dir:.
    k1s0.io/tier: tier2
    k1s0.io/component: invoice-generator
    k1s0.io/lang: csharp
    k1s0.io/env: dev
spec:
  type: service
  lifecycle: experimental
  owner: tier2-dev
  providesApis: []
  consumesApis:
    - k1s0-tier1-state
  dependsOn: []
