# business Tier のサービス定義
services:
  - name: ledger-v1
    url: http://ledger-server.k1s0-business.svc.cluster.local:80
    routes:
      - name: ledger-v1-route
        paths:
          - /api/v1/ledger
        strip_path: false

  - name: accounts-v1
    url: http://accounts-server.k1s0-business.svc.cluster.local:80
    routes:
      - name: accounts-v1-route
        paths:
          - /api/v1/accounts
        strip_path: false
