ALTER TABLE scheduler.scheduler_jobs
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
    ADD COLUMN IF NOT EXISTS target_type VARCHAR(50) NOT NULL DEFAULT 'kafka',
    ADD COLUMN IF NOT EXISTS target TEXT;
